### ISSUE TITLE
No librtlsdr-dev Raspbian Wheezy package available.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#1]
There is no librtlsdr-dev package available in the official Raspbian Wheezy package repositories which is causing a dependency issue when trying to build dump1090-mutability1.15~dev packages.

**Comment by jprochazka** [comment]
Debating even supporting old releases such as Wheezy at this point... Anyone see an issue with this? Until then support for older releases has been shelved at least for the time being if not for good.

**Comment by jprochazka** [comment]
@mgunther68

You are more familiar with setting up dump1090-mutability on Wheezy then I am. The following packages you suggested installing on the FlightAware forum should resolve this issue correct?

https://github.com/mutability/librtlsdr/releases/download/v0.5.4_git-1/librtlsdr0_0.5.4.git-1_armhf.deb
https://github.com/mutability/librtlsdr/releases/download/v0.5.4_git-1/librtlsdr-dev_0.5.4.git-1_armhf.deb

**Comment by mgunther68** [comment]
Yes I have these packages installed on my Wheezy Pi. I followed Oliver's directions here:
https://github.com/mutability/dump1090
>You will need a librtlsdr0 package for Raspbian. There is no standard build of this. I have built suitable packages that are available from this release page: https://github.com/mutability/librtlsdr/releases

From my Pi:
```
pi@raspberrypi ~ $ apt-cache show librtlsdr0
Package: librtlsdr0
Status: install ok installed
Priority: extra
Section: libs
Installed-Size: 136
Maintainer: Adam Cécile (Le_Vert) <gandalf@le-vert.net>
Architecture: armhf
Multi-Arch: same
Source: rtl-sdr
Version: 0.5.4~git-1
Depends: libc6 (>= 2.13-28), libgcc1 (>= 1:4.4.0), libusb-1.0-0 (>= 2:1.0.9)
Pre-Depends: multiarch-support
Conffiles:
 /etc/modprobe.d/rtl-sdr-blacklist.conf c05476dc82e6934185e8b55b4e84aa13
Description: Software defined radio receiver for Realtek RTL2832U (library)
 rtl-sdr is a software defined radio (SDR) receiver software for certain
 low-cost DVB-T/DAB(+) USB dongles based on the Realtek RTL2832U chip.
 .
 This package contains the shared library.
Homepage: http://sdr.osmocom.org/trac/wiki/rtl-sdr

pi@raspberrypi ~ $ apt-cache show librtlsdr-dev
Package: librtlsdr-dev
Status: install ok installed
Priority: extra
Section: libdevel
Installed-Size: 145
Maintainer: Adam Cécile (Le_Vert) <gandalf@le-vert.net>
Architecture: armhf
Source: rtl-sdr
Version: 0.5.4~git-1
Depends: librtlsdr0 (= 0.5.4~git-1)
Pre-Depends: multiarch-support
Description: Software defined radio receiver for Realtek RTL2832U (development files)
 rtl-sdr is a software defined radio (SDR) receiver software for certain
 low-cost DVB-T/DAB(+) USB dongles based on the Realtek RTL2832U chip.
 .
 This package contains development files.
Homepage: http://sdr.osmocom.org/trac/wiki/rtl-sdr
```

**Comment by mgunther68** [comment]
@jprochazka
I have created a basic (minimal install) Debian 7.9 (wheezy) VM on my laptop for testing. As expected, the dump1090 installation currently fails:
```
Checking if the package rtl-sdr is installed... [PREVIOUS INSTALLATION FAILED]
Attempting to Install the package rtl-sdr again in 5 seconds (ATTEMPT 5 OF 5)...

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package rtl-sdr
```
Let me know when you want me to test things again.

**Comment by mgunther68** [comment]
OK, I think I have found a generic solution (i.e. not tied to downloading any specific files from any specific location).
Steps:
1) Edit /etc/apt/sources.list
2) Add this to the end:
```
#wheezy-backports
deb http://ftp.debian.org/debian wheezy-backports main
```
3) `sudo apt-get update` (I think that is already part of the install scripts.)

After doing the above, dump1090-mutability installed without any issues. I leave it up to you to perform the required version (wheezy/jessy) tests and add the wheezy-backports source.

**Comment by mgunther68** [comment]
Thinking about this a bit more and reading https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=58836 I'm not so sure anymore if the above will be a good idea on a Pi, especially Pi1.

**Comment by mgunther68** [comment]
I think the best way is to determine if the script is running on a Wheezy Pi device (armhf) and install the two required packages from here:
```
~ $ wget https://github.com/mutability/librtlsdr/releases/download/v0.5.4_git-1/librtlsdr0_0.5.4.git-1_armhf.deb
~ $ wget https://github.com/mutability/librtlsdr/releases/download/v0.5.4_git-1/librtlsdr-dev_0.5.4.git-1_armhf.deb
~ $ sudo dpkg -i librtlsdr0_0.5.4.git-1_armhf.deb
~ $ sudo dpkg -i librtlsdr-dev_0.5.4.git-1_armhf.deb
```

You could also check first if the packages are already available:
```
apt-cache show librtlsdr0
apt-cache show librtlsdr-dev
```

I don't think the back port idea that I posted earlier is such a good idea after all.

**Comment by jprochazka** [comment]
I no longer see the point in supporting Wheezy based releases due to the age.
