### ISSUE TITLE
Installing Dump1090-mutability

### ISSUE THREAD

**Issue by slookabill** [jprochazka/adsb-receiver#102]
When running the script it seems to fail trying to install rtl-sdr, here's the commands it prints out:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package rtl-sdr

Note, I started from a base of the default raspbian/piaware image that's available on flightaware, and already have a fr24 feeder script running as well.

**Comment by mgunther68** [comment]
The default raspbian/piaware image is still based on the old Raspbian Wheezey version and this does not include the rtl-sdr package. See here for the open issue in relation to this: #1 
Also note that the Readme states: "... set of scripts and files which can be used to setup an ADS-B receiver on a **clean installation** of a Debian derived operating system."

Your best option is to start with a new Raspbian Jessie install, run the scripts here and then manually add FR24 feeder. 
Alternatively, you can install the two required rtl-sdr packages manually on your existing environment and then re-run the script here.  To this to install the packages:
```
~ $ wget https://github.com/mutability/librtlsdr/releases/download/v0.5.4_git-1/librtlsdr0_0.5.4.git-1_armhf.deb
~ $ wget https://github.com/mutability/librtlsdr/releases/download/v0.5.4_git-1/librtlsdr-dev_0.5.4.git-1_armhf.deb
~ $ sudo dpkg -i librtlsdr0_0.5.4.git-1_armhf.deb
~ $ sudo dpkg -i librtlsdr-dev_0.5.4.git-1_armhf.deb```

**Comment by mgunther68** [comment]
The issue here was that installation was attempted on an existing PiAware image and not a clean Raspbian Jessie install. This is not supported and I updated the Readme file accordingly.
