### ISSUE TITLE
Daily CPU/Noise spike

### ISSUE THREAD

**Issue by geofffox** [jprochazka/adsb-receiver#103]
I have noticed an interesting problem since installing Joe's ADSB receiver scripts.  Every day around 22z - 0z and 10z - 12z my CPU starts working a little harder.  At the same time the noise level goes up around 6db and my monitoring sees fewer planes, etc.

Is there a connection?  Does the CPU go up because the noise has risen or is the noise an artifact of the CPU?  I don't know, but found it curious.

None of this would have been possible to notice before this wonderfully high res graphing.  I have already used it to find a sweet spot for my indoor antenna.  A few inches can make a huge difference.

![ads b feeder performance graphs](https://cloud.githubusercontent.com/assets/3851061/13200605/3c5fabc6-d805-11e5-9f3a-7b0eb6bdf09b.png)

**Comment by mgunther68** [comment]
Hi geofffox, these are interesting observations but I'm unable to answer your questions. I guess this would be a good discussion topic on the Flightaware forum.

**Comment by jprochazka** [comment]
I can honestly say I have not seen spikes like this on my hardware (Raspberry Pi 2). Is something specified in your cron to run at those times which maybe executing a processor intensive job? Seems like the processor spike happens after a burst of heavy outgoing bandwidth traffic has occurred after which things settle down... Might want to check your logs focusing around that time to see if anything out of the ordinary is happening. Feel free to post anything interesting you may find.

**Comment by geofffox** [comment]
Joe -

The system is 100% pure Raspbian (full) and your install.sh script.  There
is nothing else installed on this particular Pi.  That's why I've come to
you.

There shouldn't be much, if any, traffic around 12z which is 4a here in
California.  Any spike of activity at 12z can't be a product of legit air
traffic.

I'm not adverse to reloading from scratch.  Suggestions will be appreciated.

Geoff

**Comment by jprochazka** [comment]
Yeah looks like dead times for the most part just the huge spike in outgoing bandwidth dropping down to not near as much that you pointed out which has me scratching my head and why I was wondering if something else was installed which was kicking off at those times.

I would say if it is a clean installation with only the software installed by these scripts give it another day and see if the spikes happen again. Maybe something downstream having to do with one of the aggregate sites? not sure...

**Comment by geofffox** [comment]
I will observe for a few days.

It is cool to hear a copter fly overhead, look on the computer and know who
it is!

**Comment by jprochazka** [comment]
I have not heard back on this issue so marking it as invalid.
