### ISSUE TITLE
Change to Messages/aircraft graph

### ISSUE THREAD

**Issue by caiusseverus** [jprochazka/adsb-receiver#109]
The current messages/aircraft graph is difficult to see - the number of aircraft dominates the graph and any variability in the rate (which is what should be of interest) is difficult to see.

This modification scales the rate and puts a second vertical scale to make it more visible:

aircraft_message_rate_graph() {
  rrdtool graph \
  "$1" \
  --start end-$4 \
  --width 480 \
  --height 200 \
  --step "$5" \
  --title "$3 Message Rate / Aircraft" \
  --vertical-label "Aircraft" \
  --right-axis-label "Messages/Aircraft/Second" \
  --lower-limit 0 \
  --units-exponent 0 \
  --right-axis 0.1:0 \
  "TEXTALIGN:center" \
  "DEF:aircrafts=$2/dump1090_aircraft-recent.rrd:total:AVERAGE" \
  "DEF:messages=$2/dump1090_messages-local_accepted.rrd:value:AVERAGE" \
  "CDEF:rate-provisional=messages,aircrafts,/,10,*" \
  "CDEF:rate=aircrafts,0,GT,rate-provisional,0,IF" \
  "VDEF:avgrate=rate,AVERAGE" \
  "VDEF:maxrate=rate,MAXIMUM" \
  "LINE1:rate#0000FF:Messages / AC (RH)" \
  "LINE1:avgrate#666666:Average\::dashes" \
  "GPRINT:avgrate:%3.1lf" \
  "LINE1:maxrate#FF0000:Maximum\:" \
  "GPRINT:maxrate:%3.1lf\c" \
  "LINE1:aircrafts#990000:Aircraft Seen / Tracked \c" \
  --watermark "Drawn: $nowlit";
}

It looks like this:

![dump1090-localhost-aircraft_message_rate-24h](https://cloud.githubusercontent.com/assets/7763268/13362939/fec9b662-dcbe-11e5-96e1-41ac4003bfd2.png)

**Comment by mgunther68** [comment]
You'll have to divide the Average and Maximum rate by 10 as well to fit in with the RHS axis.

**Comment by caiusseverus** [comment]
Ah yes. That's just a matter of changing these two lines:

"VDEF:avgrate=rate,AVERAGE" \
"VDEF:maxrate=rate,MAXIMUM" \

to

"VDEF:avgrate=rate,AVERAGE,10,/" \
"VDEF:maxrate=rate,MAXIMUM,10,/" \

**Comment by caiusseverus** [comment]
Yes - Changing the lines:

"VDEF:avgrate=rate,AVERAGE" \
"VDEF:maxrate=rate,MAXIMUM" \

to

  "CDEF:rate10=rate,10,/" \
  "VDEF:avgrate=rate10,AVERAGE" \
  "VDEF:maxrate=rate10,MAXIMUM" \

should correct it.

**Comment by mgunther68** [comment]
Yep, the lines now need to be moved as well:)
And, introducing a RHS axis, you need to reduce the width of the actual graph so that the overall size ends up as 577x298 like all the other ones. For me, this does the trick:
--width 428 \

I understand the rationale for your changes, but for me where I might see 30 a/c as a maximum, now the a/c line is very small at the bottom. The best way might be to adapt the RHS axis automatically according to the general level of a/c seen. But I don't know how to accomplish this.

**Comment by mgunther68** [comment]
Here, try this:
aircraft_message_rate_graph() {
  rrdtool graph \
  "$1" \
  --start end-$4 \
  --width 428 \
  --height 200 \
  --step "$5" \
  --title "$3 Message Rate / Aircraft" \
  --vertical-label "Messages/Aircraft/Second" \
  --right-axis-label "Messages/Aircraft/Second" \
  --lower-limit 0 \
  --units-exponent 0 \
  --right-axis 0.1:0 \
  "TEXTALIGN:center" \
  "DEF:aircrafts=$2/dump1090_aircraft-recent.rrd:total:AVERAGE" \
  "DEF:messages=$2/dump1090_messages-local_accepted.rrd:value:AVERAGE" \
  "CDEF:rate-provisional=messages,aircrafts,/,10,*" \
  "CDEF:rate=aircrafts,0,GT,rate-provisional,0,IF" \
  "CDEF:rate10=rate,10,/" \
  "VDEF:avgrate10=rate10,AVERAGE" \
  "VDEF:maxrate10=rate10,MAXIMUM" \
  "VDEF:avgrate=rate,AVERAGE" \
  "VDEF:maxrate=rate,MAXIMUM" \
  "LINE1:rate#0000FF:Messages / AC" \
  "LINE1:avgrate#666666:Average\::dashes" \
  "GPRINT:avgrate10:%3.1lf" \
  "LINE1:maxrate#FF0000:Maximum\:" \
  "GPRINT:maxrate10:%3.1lf\c" \
  "LINE1:aircrafts#990000:Aircraft Seen / Tracked \c" \
  --watermark "Drawn: $nowlit";
}

**Comment by caiusseverus** [comment]
This seems to work OK for the lines:

aircraft_message_rate_graph() {
  rrdtool graph \
  "$1" \
  --start end-$4 \
  --width 428 \
  --height 200 \
  --step "$5" \
  --title "$3 Message Rate / Aircraft" \
  --vertical-label "Aircraft" \
  --right-axis-label "Messages/Aircraft/Second" \
  --lower-limit 0 \
  --units-exponent 0 \
  --right-axis 0.1:0 \
  "TEXTALIGN:center" \
  "DEF:aircrafts=$2/dump1090_aircraft-recent.rrd:total:AVERAGE" \
  "DEF:messages=$2/dump1090_messages-local_accepted.rrd:value:AVERAGE" \
  "CDEF:rate-provisional=messages,aircrafts,/" \
  "CDEF:rate=aircrafts,0,GT,rate-provisional,0,IF" \
  "CDEF:rate10=rate,10,*" \
  "VDEF:avgrate=rate,AVERAGE" \
  "VDEF:maxrate=rate,MAXIMUM" \
  "VDEF:avgrate10=rate10,AVERAGE" \
  "VDEF:maxrate10=rate10,MAXIMUM" \
  "LINE1:rate10#0000FF:Messages / AC (RH)" \
  "LINE1:avgrate10#666666:Average\::dashes" \
  "GPRINT:avgrate:%3.1lf" \
  "LINE1:maxrate10#FF0000:Maximum\:" \
  "GPRINT:maxrate:%3.1lf\c" \
  "LINE1:aircrafts#990000:Aircraft Seen / Tracked \c" \
  --watermark "Drawn: $nowlit";
}


I don't think it is possible to dynamically scale the right hand side, since that is set at the top before any data is acquired.

**Comment by mgunther68** [comment]
OK, make it RHS to be consistent with other graphs and remove one ':' before 'dashes' and my graph looks like this below. This is my secondary Pi with not as good a reception as the primary one.
<img width="546" alt="screen shot 2016-02-26 at 21 58 31" src="https://cloud.githubusercontent.com/assets/13157289/13366603/5a2d9734-dcd4-11e5-9805-cf7dfc961611.png">
And yeah you are probably right about the right hand side. It's fine for me that way now and should improve the graph for people that see many aircraft.

@jprochazka , what does the graph look like for you and do you think we are better off scaling it like the examples given here?

**Comment by jprochazka** [comment]
I will leave that up to you two.
I was honestly thinking the same earlier today how Aircraft Seen drowns out the other lines.
Good work!

**Comment by mgunther68** [comment]
Closing via latest commit. Thanks @caiusseverus for the suggestions!
