### ISSUE TITLE
Keep JS running on tab not focussed in Chrome

### ISSUE THREAD

**Issue by cy80rg101** [jprochazka/adsb-receiver#114]
From what I know, Chrome will shut down or throttle JS sscripts running in non-focussed tabs (i.e background tabs).

As such, I believe dump1090 maps will become out of date if left in a background tab...

Have found a couple of solutions:

1. Set as Background Page
https://developer.chrome.com/extensions/background_pages

2. Set as Event Page
https://developer.chrome.com/extensions/event_pages

Of the two, I believe the older background page is more relevant...

"Running code eveny second means that the background page must be loaded all the time. Then you must use a background page, not an event page.".

**Comment by jprochazka** [comment]
The documentation you point out refers to extensions. Browsers stopping JavaScript execution when a tab is not "focused" on seems to be the norm anymore. Honestly don't think beyond going a totally different route involving recoding everything will resolve this issue I am sorry to say.
