### ISSUE TITLE
Add option to show / hide right hand section (live aircraft list/ update clocks)

### ISSUE THREAD

**Issue by cy80rg101** [jprochazka/adsb-receiver#115]
Simple chekbox etc function to show or hide the right hand controls / aircraft list.

**Comment by jprochazka** [comment]
I will see if I can add some JavaScript to the portal page to control this however I am not sure I will be able to without having to modify dump1090-mutability files which I am trying to stay away from doing so at this time.

**Comment by jprochazka** [comment]
I have been messing around trying to do this using JavaScript and CSS residing in the page containing the iframe holding the stock dump1090 map. I have been able to "hide" the right hand column but the map is not expanding to take over the newly emptied area. Haven't given up just wanted to update progress.

If there are any JavaScript/CSS gurus out there that want to take a shot your more than welcome. Only stipulation is the dump1090 map itself cannot be modified only dump1090.php. I honestly do not wish to maintain a customized dump1090-mutability fork.

**Comment by radiostationx** [comment]
I found a useful enhancement which may be of interest.
To retain UTC clock on left and change right hand Last Update clock to  your Local Time.
This involves modification of script.js file in mutability.
Details and "how to" are at the foot of page link below

[http://forum.planefinder.net/threads/raspberry-pi-b-plus-and-model2-installation-instructions-for-raspbian-dump1090-data-feeder.241/](url)

**Comment by jprochazka** [comment]
> This involves modification of script.js file in mutability.

This is where I run into problems. As stated before in forum posts and here I do not wish to maintain a dump1090-mutability fork containing such changes. I am however starting to lean towards making my own dump1090 and dump978 map using the JSON data supplied by both dump1090 and dump978. However this is just a thought which might be revisited once I am happy with how the portal displays historical flight data.

**Comment by jprochazka** [comment]
This has be addressed in the new portal being worked on now. I am going to close this issue due to the fact that In the near future the portal will reside in it's own repository. The new protal is a total rewrite and totally different creature making most all portal issues posted here invalid.
