### ISSUE TITLE
Raspberry Pi 1 and 3 not recognized.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#118]
I thought I had the RPi 1 fixed but have had a report it is not. Also the RPi 3 is running newer instructions so is more than likely not being detected properly either when installing the Planfinder and Flightradar24 clients. At this time I do not own either a RPi 1 or 3 so if anyone can get me the results for the following command on either or both devices I would appreciate it.

    uname -m

I have conflicting reports on the RPi 1:

    armv6l (with the letter L at the end)
    armv61 (with the numeral 1 at the end)

Need to confirm which is correct.

**Comment by jthawkes** [comment]
RPI1
Linux tardis3 4.1.17+ #843 Mon Feb 15 23:17:46 GMT 2016 armv6l GNU/Linux

RPI3
Linux tardis2 4.1.19-v7+ #853 SMP Wed Mar 9 18:09:16 GMT 2016 armv7l GNU/Linux

**Comment by jprochazka** [comment]
Thanks @jthawkes.
So l not 1 that should work as the scripting sits now then...
The RPi3 must be running the same instructions as the RPi2 then so no change should be needed there.

Going to leave the code as it is then for now and see about ordering a RPi1B and/or RPi1B+ to test things out before closing the issue. Unless in the mean time I get confirmation things are in fact working or not.

**Comment by jthawkes** [comment]
The RPI3 is 64bit capable, however, they have not released a 64bit OS for it yet.

FYI, my RPI3 runs about 1/2 the CPU% of my RPI2. 9-10% versus 20-22% just running Dump978/1090/piaware.

**Comment by jprochazka** [comment]
I found an RPi B I can use for testing which should be delivered shortly.

**Comment by expatc** [comment]
I have a Raspberry Pi 1 Model B (512MB). `uname -m` returns `armv6l`.
```
Installing the Plane Finder ADS-B Client package...

/home/pi/adsb-receiver/bash/feeders/planefinder.sh: line 97: lsb_release: command not found
dpkg: error processing archive /home/pi/adsb-receiver/build/pfclient_3.3.222_i386.deb (--install):
 package architecture (i386) does not match system (armhf)
Errors were encountered while processing:
 /home/pi/adsb-receiver/build/pfclient_3.3.222_i386.deb
\033[31m
#########################################
# INSTALLATION HALTED!                  #
# UNABLE TO INSTALL A REQUIRED PACKAGE. #
#########################################

The pfclient package did not install properly!

This script has exited due to the error encountered.
Please read over the above output in order to determine what went wrong.

Killed
```
```
Installing the Flightradar24 feeder client package...

/home/pi/adsb-receiver/bash/feeders/flightradar24.sh: line 130: lsb_release: command not found
dpkg: error processing archive /home/pi/adsb-receiver/build/fr24feed_1.0.18-5_i386.deb (--install):
 package architecture (i386) does not match system (armhf)
Errors were encountered while processing:
 /home/pi/adsb-receiver/build/fr24feed_1.0.18-5_i386.deb
\033[31m
#########################################
# INSTALLATION HALTED!                  #
# UNABLE TO INSTALL A REQUIRED PACKAGE. #
#########################################

The fr24feed package did not install properly!

This script has exited due to the error encountered.
Please read over the above output in order to determine what went wrong.

Killed
```

**Comment by radiostationx** [comment]
expatc , looks line you downloaded linux package fr24feed instead if pi version of feeder
I think ditto with planefinder.

**Comment by jprochazka** [comment]
I just got an RPiB in the mail this weekend. I should have it tested and any needed fixes committed tonight. The issue has to do with the RPiB not being detected properly when setting up either the Planefinder or Flightradar24 client resulting in the script trying to install the wrong package.

The RPi3 might have the same issue when installing the Planefinder or Flightradar24 client. I am hoping to have a RPi3 in my possession here shortly to do testing.

As stated earlier I am sure it have to do with the output of the command "uname -m" the problem is I am getting conflicting reports on what the output of this command is for these devices. Once I am able to see the output myself I can get a proper fix in place.

**Comment by jprochazka** [comment]
I tested the installation process on an RPiB today. Everything went smooth with no errors. Commit d6927cde055e7abead0676dd7831d29c96050723 added support for both devices. These files were fixed after the last release so you will need to update your scripts using the instructions found in the README.md file.

A new release and image containing these fixes and additional features will be available shortly.

**Comment by jprochazka** [comment]
I am reopening this issue due to the fact the RPi3 is using a Cortex A-53 which is built on the ARMv8-A architecture. I am honestly not sure this issue will not show it's head on an RPi3. Until I get reliable confirmation things work, or better yet as with the RPiB get one in hand to test, I will leave this open.

**Comment by jthawkes** [comment]
I agree. The image is not reporting correctly at the moment. It could also change when they finally release a 64 bit OS.

**Comment by jprochazka** [comment]
I have heard no reports of issues pertaining to the Raspberry Pi 3 so I am closing this issue.
