### ISSUE TITLE
Add checks for packages fakeroot and virtualenv

### ISSUE THREAD

**Issue by UlrichZeller** [jprochazka/adsb-receiver#120]
On armbian systems the needed packages fakeroot and virtualenv are not installed by default.
Please include a check and installation if necessary.
Tested with armbian on Orange Pi PC and Banana Pi Pro. Excellent work.

**Comment by jprochazka** [comment]
You don't happen to remember which items needed these two packages do you?

**Comment by UlrichZeller** [comment]
I selected all possibilities so I can not say, if the later parts needed the packages too.
fakeroot was needed by dump-mutability.
virtualenv was needed by piaware.

**Comment by jprochazka** [comment]
Checks for these packages added in commit 1f53ad2a94db470c93bac01dfd28a0ecbb65e5ce.

fakeroot added as a prerequisite for dump-mutability.
virtualenv added as a prerequisite for dump-mutability.

If anyone finds these packages are needed for any other software let me know.
