### ISSUE TITLE
Issue with Planefinder Client display in portal

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#122]
Possible security issue when planefinder checkbox is selected in admin area of portal.
The PF client displays correctly but if a station owner makes his/her station available on www , an anonymous viewer can see sensitive details such as PF station log and view PF settings page.
This could cause the station owner some problems if the viewer obtained the stations PF sharecode.

**Comment by jprochazka** [comment]
I know this isn't the proper way to think when it comes to security but honestly someone getting a hold of your sharecode is about as likely as someone getting your FlightAware password which would be just as dangerous.

There is not much more I can do as far as security goes when it pertains to the Planefinder ADS-B Client beyond allow users to enable or disable the link. With or without the link the Planefinder client web site is still addressable. It is a part of the Planefinder ADS-B Client and is installed no matter what if the pfclient package is installed. Basically this is just security through obscurity and I know this is not a great way to practice security by no means either.

The best way to protect this if you are concerned about the public seeing this would be to firewall the port so it is not available to the public.

    ... snip ...
    iptables -A INPUT -p tcp --destination-port 30053 -j DROP
    ... snip ...

Of course there would generally be more rules needed for iptables but this should give you an idea on the direction you could take to hide the pages from the public.You could also change the iptables rule around a bit to allow only certain IP addresses access to it. 

What I can do is make a write up on firewalling a receiver using iptables in the wiki.

**Comment by jprochazka** [comment]
Privacy isssues such as this should be taken up with the developer responsible for the code in question.
