### ISSUE TITLE
Add function to blog of web portal.

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#123]
Is there a way to add the ability to copy text from a word/wordpad etc document and paste to the
blog text editor window please ?

On updating portal to latest version using ./install.sh, all previous station blogs are deleted.
It would be useful to have the blog of your choice held as a word processing document for easy transfer via paste after upgrading the station web portal to the latest version.

**Comment by jprochazka** [comment]
I use TinyMCE for the blog post contents and if I am not mistaken there is Word converter already in place. Not sure but I think it is just a matter of adding an additional tool bar button. I will look into adding the option if in fact it is available. 

I have been focusing on upgradability in the next release. That being said you will have to suffer through the "reset" just one more time. Until then backup the file /var/www/html/blogPosts.xml and restore it afterwards. This is actually already an open issue located at  https://github.com/jprochazka/adsb-receiver/issues/98

**Comment by jprochazka** [comment]
I use TinyMCE for the blog post contents and if I am not mistaken there is Word converter already in place. Not sure but I think it is just a matter of adding an additional tool bar button. I will look into adding the option if in fact it is available. 

I have been focusing on upgradability in the next release. That being said you will have to suffer through the "reset" just one more time. Until then backup the file /var/www/html/blogPosts.xml and restore it afterwards. This is actually already an open issue located at  https://github.com/jprochazka/adsb-receiver/issues/98

**Comment by jprochazka** [comment]
I use TinyMCE for the blog post contents and if I am not mistaken there is Word converter already in place. Not sure but I think it is just a matter of adding an additional tool bar button. I will look into adding the option if in fact it is available. 

I have been focusing on upgradability in the next release. That being said you will have to suffer through the "reset" just one more time. Until then backup the file /var/www/html/blogPosts.xml and restore it afterwards. This is actually already an open issue located at  https://github.com/jprochazka/adsb-receiver/issues/98

**Comment by radiostationx** [comment]
Hi jrochazka,
Looked in the suggested location to find file to backup but I cannot locate blogposts.xml

![blog php](https://cloud.githubusercontent.com/assets/17929166/13908285/7eb0ca38-eef7-11e5-95d0-3542069f64dd.png)
