### ISSUE TITLE
Smaller scale for bandwidth system charts

### ISSUE THREAD

**Issue by expatc** [jprochazka/adsb-receiver#124]
On the system information page, the bandwidth system charts are displayed in MB/s. As a result, they both display 0 MB/s due to the rounding of the system's significantly smaller scale bandwidth usage. A smaller scale would produce a better way of monitoring the performance at a quick glance. I only have my receiver's statistics to go by, but I imagine a scale in kB/sec with 100% equal to 100kB/sec would provide a better indicator of current usage. Even if the 100% = 100kB/sec change wasn't implemented for the dial, simply having the digits read in kB/sec instead of MB/sec would be beneficial.

**Comment by radiostationx** [comment]
expatc. I think that changes to the guages are on the to do list for a later release with other small items on the web portal but I think jprochazka is attending to some other work first.
He has done a great job so far putting all this together and the image runs largely trouble free.

**Comment by jprochazka** [comment]
The system information page was not "complete" when released but it worked so instead of removing them from the current release I included what was done so far in the last release.

**Comment by jprochazka** [comment]
Added option to display either Mbps or Kbps.
Commit 535049433a5753b68f5f5908aa8360ed11d904d2.
