### ISSUE TITLE
HTTPS issue

### ISSUE THREAD

**Issue by ytwytw** [jprochazka/adsb-receiver#126]
I'm setting up https only with reverse proxy (nginx) and I find out there are several http hard link causing issues (will not display since its http link)

Would be nice to fix this

Thanks

**Comment by jprochazka** [comment]
Will do.

**Comment by ytwytw** [comment]
Hi @jprochazka 

My SD Card just died

I gonna re-install and check again over the weekend and will report here 

Thanks,

**Comment by ytwytw** [comment]
Mixed Content: 
The page at 'https://xxx.xxx.xxx/dump1090.php' was loaded over HTTPS, but requested an insecure image 'http://maps.google.com/mapfiles/kml/pal4/icon57.png'. This content should also be served over HTTPS.

here is one

**Comment by jprochazka** [comment]
This issues was an issue with dump1090-mutability and was fixed a couple weeks ago.
https://github.com/mutability/dump1090/commit/e509e76294786387b01e39c09ccd216fb109c01d

I would suggest making the changes outlined in that commit or updating dump1090-mutability which should resolve your issue..

**Comment by ytwytw** [comment]
@jprochazka This resolved my issue

It's all good now :+1: 

Thanks,
