### ISSUE TITLE
Wireless

### ISSUE THREAD

**Issue by rlane3907** [jprochazka/adsb-receiver#127]
Joe, I just following your instructions for the ADSB-Receiver installation on my new Pi3.  That was the easiest install I ever did  with no problems.  My Pi is sending data to FlightAware just fine.  My question is how to set up wireless.    The setup WiFi for PiAware didn't work at all.    Thanks.  Rich

**Comment by jprochazka** [comment]
I take it you are using the image which uses Raspbian Jessie Lite which contains no GUI. If this is the case you can set it up "manually" using wpa supplicant which is not a hard task to do.

Make sure wpa_supplicant is installed.

    sudo apt-get update
    sudo apt-get install wpasupplicant

Open the file /etc/wpa_supplicant/wpa_supplicant.conf so you can edit it.

    sudo nano /etc/wpa_supplicant/wpa_supplicant.conf

Unless you have a custom setup as far as your WiFI access point is concerned the contents of this file should generally look like this. Simply replace YOUR_SSID and YOUR_PASSWORD with the appropriate information pertaining to your access point.

    ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
    update_config=1

    network={
            ssid="YOUR_SSID"
            psk="YOUR_PASSWORD"
            proto=WPA
            key_mgmt=WPA-PSK
            pairwise=TKIP
            auth_alg=OPEN
    }

Then open the file /etc/network/interfaces.

    sudo nano /etc/network/interfaces

Add the following if a wlan0 section does not exist.

    allow-hotplug wlan0
    iface wlan0 inet manual
        wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

Finally run the following command to bring the interface up.

    sudo ifup wlan0


If you are using Raspbian Jessie and not the Lite version and can use the command startx it may be easier to install and run the wpagui package.

    sudo apt-get install wpagui

Then run it. It is self expanitory how it works.

    sudo wpa_gui

**Comment by rlane3907** [comment]
Joe,

Thanks for the excellent instructions.  I was able to follow the steps and
everything worked perfectly!  I really like the web page, especially the
concentric range rings and the additional data.  It's a big improvement
over the original.  I appreciate your help and time.  And quick response!

V/R,

Rich

**Comment by jprochazka** [comment]
Added setup instructions to the wiki.
https://github.com/jprochazka/adsb-receiver/wiki/Setting-Up-a-WiFi-Connection

**Comment by Romeo-Golf** [comment]
Joe,

Sorry for dragging up a closed thread but with the increased prevalence of Raspberry Pi 3 with wifi included I was wondering if you see any issue with me adding a quick dialog to ask the user if they would like to setup wifi, and if so confirm the SSID/PSK etc values with some whiptail dialogs etc?

I suppose these values could also be configure/saved in the config file to assist with unattended installation.. ie user downloaded the latest image to the SD card, mounts, copies over the config, unmounts and swaps the SD card into the Pi for deployment out of reach of wired ethernet and/or a screen.... but will save such grand ideas for later ;)
 
Thanks.
