### ISSUE TITLE
Change location information

### ISSUE THREAD

**Issue by makeitwrite** [jprochazka/adsb-receiver#130]
Installed this successfully on a Rasberry Pi 3 for flightaware, but in the initial process may have fat fingered or otherwise input wrong physical location coordinate information as the live dump map from the device has me off about a mile from my true location. I've changed it on the flightaware site in my profile, but would like to be able to correct on the device. re-install does not take me to the set of options for flightaware nor can I understand how to uninstall to allow a re-install. This might be a handy option for people who move. 
Thanks, Bob

**Comment by jprochazka** [comment]
The latitude and longitude can be set in the file /etc/default/dump1090-mutability. More than likely the reason it did not center properly after reinstall was due to a cookie so clear your browser cookies to test it.

**Comment by jthawkes** [comment]
The config file is
/etc/default/dump1090-mutability 



Jon

**Comment by makeitwrite** [comment]
Thank you - Changed coordinates in file and restarted - all good and apologize for the newbe question. Next on to a better antenna -
Bob

**Comment by jprochazka** [comment]
Not a problem.
