### ISSUE TITLE
Performance Graphs - Total Bandwidth

### ISSUE THREAD

**Issue by kyleinprogress** [jprochazka/adsb-receiver#132]
My apologies for creating an "issue" here. I tried registering on the forums, but never got an email message after registering.

How difficult would it be to add a graph that shows total bandwidth, not just Tx/Rx? I installed VNSTAT on the pi so I can check there, but it'd be nice to see a graph that just shows total bandwidth (split between Tx/Rx would be an added bonus) for the pi.

**Comment by jprochazka** [comment]
First off as of last night emails from the web site are no longer being sent from the web server hosting the site. I switched to a third party email service. Thinking that emails sent from the server which is hosted by Amazon AWS are being tagged as spam...

Secondly there is no reason to apologize requests like this are welcome here.

Anyways back to your feature request.

I am not sure I follow what you are asking for. Is this something you would like to see added to the system information page or the performance graphs. There is a performance graph named "Bandwidth Usage" which I think displays the information you are requesting. Incoming and outgoing traffic split, incoming going up and outgoing going down and max, average, and current speeds displayed as text at the bottom.

![system-localhost-wlan0_bandwidth-24h](https://cloud.githubusercontent.com/assets/2583357/14212879/faae243c-f802-11e5-855a-fed049661089.png)

If this is not what you are looking for could you give us a better idea or an example of how you would like this data displayed and we will be more than happy to try and accommodate the request.

**Comment by kyleinprogress** [comment]
After thinking this through a little more, I'm not sure it would be possible to show a total bandwidth using the time-series graphs. Here is what I see when I log onto the raspberry pi and view VNSTATS. I'm looking mainly at the first three columns to figure out what the totals were.

![screen shot 2016-04-01 at 11 47 48 am](https://cloud.githubusercontent.com/assets/4053652/14213820/9dc5181e-f7ff-11e5-8d4f-78998d540002.png)


Basically, I'm just looking for a graph/metric that shows total bandwidth used by the pi over time. Since more and more ISPs are enforcing limits, might be worth keeping an eye on. Based on my [current location](http://flightaware.com/adsb/stats/user/kwarner04#stats-19849), you can see I'm not contributing a ton of data to flightaware. I'm also don't have a lot of people looking at my stats, so almost all of the bandwidth is sending and receiving data from flightaware/flightradar/etc.

**Comment by jprochazka** [comment]
I get what your saying. You need historical data you can view over a specific range of time such as daily, weekly, and monthly. I am trying to wrap the 2.0.0 release up right now but I will look into adding this in the next release after v2.0.0.

**Comment by jprochazka** [comment]
The portal is getting a total rewrite and in the near future the portal will be stored in it's own repository so there is no need to track future enhancments here. However, it is on my yet to be published portal TODO list.
