### ISSUE TITLE
Configure piaware after adsb-receiver install

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#135]
Hi,
Configured piaware today and all seems okay but I wanted to reconfigure piaware again so i followed the guide from flightaware and inserted

``sudo piaware-config -user mystatsionname -password``

I inserted the password when prompted but then i pressed enter the system returned to the command prompt. i could make no further progress re-configuring my settings.

Please can something be inserted into wiki on how to re-configure feeder programs if a user should need to change settings.

**Comment by jprochazka** [comment]
That command should work to reset the user and password. You can check to see if the new user and password were set by running the following command.

    sudo piaware-config -show

PiAware is PiAware it is not modified in any form. It would take quite some time and be redundant to document every third party application. However I will add documentation pointing to third party documentation once I start cleaning up and catching up on what is available as soon as the v2.0.0 release is completed.

**Comment by radiostationx** [comment]
Issue closed.
