### ISSUE TITLE
Cannot login to web page pictures included 

### ISSUE THREAD

**Issue by Ferkulj** [jprochazka/adsb-receiver#137]
http://imgur.com/a/AW5DD

**Comment by ledfinger** [comment]
I see the same issue and also any other PHP pages eg. http://127.0.0.1/blog.php come up as blank

**Comment by chacy169** [comment]
I got the same issue after I reinstall it

**Comment by radiostationx** [comment]
Hi ,
Did you open browser and insert

[IP_ADDRESS_OF_YOUR_DEVICE]/admin/install.php

This should cure your problem.

**Comment by Ferkulj** [comment]
radiostationx, thanks for the answer i got it figured out but now my dump1090 is not running.

**Comment by jprochazka** [comment]
Were you able to get dump1090 working?

**Comment by chacy169** [comment]
After I reinstall the system.  It works good now.

Sent from my iPhone

On 12 Apr 2016, at 19:51, Joe Prochazka <notifications@github.com<mailto:notifications@github.com>> wrote:


Were you able to get dump1090 working?

-
