### ISSUE TITLE
AJAX call failed (error: Not Found). Maybe dump1090 is no longer running?

### ISSUE THREAD

**Issue by chacy169** [jprochazka/adsb-receiver#138]
After I reboot my raspberry Pi, When I open the web portal, and click the dump1090 live map, it shows me this message. 
At the beginning, I though maybe something wrong with system, then I reboot it again, same issue again. Then I though the dump1090 service not running, then I restart the service, but the system gives me no such services message. 

Anyone know how to solve this issue?

Thanks in advance.

**Comment by jprochazka** [comment]
Are you using dump1090-mutability or a modified version which has been floating around lately? 
I have seen two reports of issues running the modified version.

**Comment by chacy169** [comment]
Hi Joe
I just run the clone your adsb receiver from GitHub and install it.  Now it become worse, when I put my raspberry Pi on web browser it shows me nothing. I format the sd card reinstall the system and clone the adsb receiver from GitHub, still got nothing shows on web, but when I type 192.168.1.55/admin it shows me login web, but when I click login, the web cannot show me anything.

Best wishes
Cheng



Sent from my iPad

On 8 Apr 2016, at 03:58, Joe Prochazka <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you using dump1090-mutability or a modified version which has been floating around lately?
I have seen two reports of issues running the modified version.

-

**Comment by Ferkulj** [comment]
Yeah getting the same error, not picking any traffic up.

**Comment by chacy169** [comment]
Hi Joe

I just solve the issue, after I install the system and clone the adsb receiver, I cannot open the  radiostationx just said the new adsb receiver needs to install manually, Can you please write this on your web https://github.com/jprochazka/adsb-receiver#manual-installations

> 

Hi ,
There is a new web based installer after installing the script.
Open browser address bar and insert

[IP_ADDRESS_OF_YOUR_DEVICE]/admin/install.php

This should cure your problem.

> 

And after I reinstall the system, the dump1090 can running properly. But I don't know what cause this issue.

Ty

**Comment by jprochazka** [comment]
Will do.
Actually I will be removing the web based install steps shortly.

**Comment by CaySG550** [comment]
[IP_ADDRESS_OF_YOUR_DEVICE]/admin/install.php does not work. 404 error.
Please explain in detail how to "reinstall the system" and how to proceed.
Thank you
S
