### ISSUE TITLE
Error after install dump978 opinion by using script

### ISSUE THREAD

**Issue by ytwytw** [jprochazka/adsb-receiver#139]
I got a new SD card and load latest version of raspbian lite

then run the install.sh script with clean configuration

After choosing ADS-B Receiver (i pick 1 for 1090, 0 for 978)

then I got the following error every 5s on terminal output 

Found 2 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001
  1:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
usb_claim_interface error -6
Failed to open rtlsdr device #0.

any ideas?

Thanks

**Comment by radiostationx** [comment]
I think you would require 2 instances of dump1090 to decode messages from 2 frequencies with 2 dongles.
By default d1090 uses device 0.
You should perhaps ask the author Joe or  d1090-mutability author "obj" for some help on this one.

**Comment by jprochazka** [comment]
Open /etc/default/dump1090-mutability and check that device is set to 1.
Open ~/adsb-receiver/build/dump978/dump978-maint.sh make sure the number after -d is set to 0.

Let me know what you come up with.

**Comment by ytwytw** [comment]
When I set 0 to 1090, 1 to 978, its fine

when i set 1 to 1090, 0 to 978, both file has been set to 0

**Comment by ytwytw** [comment]
I fixed myself by recompiling rtl sdr with kernel detached parameters 

Now works prefect

**Comment by ytwytw** [comment]
ok I found the issue 

#! /bin/sh

# Start without logging.
while true; do
    rtl_sdr -d 1 -f 978000000 -s 2083334 -g 48 - | /home/pi/adsb-receiver/build/dump978/dump978 | /home/pi/adsb-receiver/build/dump978/uat2json /var/www/html/dump978/data | /home/pi/adsb-receiver/build/dump978/uat2esnt | /bin/nc -q1 127.0.0.1 30001 &
    sleep 15
done


the rtl_sdr command does not get killed after 15s of run

then its recursive calling rtl_sdr for the same usb devices 

obviously, its in use, cannot claim the same usb devices

thats why i got the usb errors

please fix

@jprochazka

**Comment by jprochazka** [comment]
The startup script will be run as a service shortly.
