### ISSUE TITLE
unable to change custom admin settings in web portal v2.0

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#141]
In web portal settings [ip-of-device]/admin I can change items to display under the heading navigation , untick boxes save settings and logout. This works as expected but if i try to change measurements or system options, the selections do not save.
If I try to log in as admin again to try and change measurements or system display options the changes I made to navigation previously go back to default (all options ticked).
I could not display

measurements: kbps

**Comment by vincemarsters** [comment]
I get similar with the Flightradar24 code as well as the measurements to kbps - this just gets wiped out

**Comment by jprochazka** [comment]
Fixed in commit 09dfdec50c3928a6363c1b90c9ed33dff5cce5a8.
To fix your existing setups add the following lines to the file /var/www/html/data/settings.xml JUST ABOVE the line </settings>.

        <setting>
            <name>measurementBandwidth</name>
            <value>kbps</value>
        </setting>

**Comment by mgunther68** [comment]
I cannot change any Navigation Links. Any deselection does not take when hitting 'Save Settings' button: all links are still selected when coming back to the page.

**Comment by jprochazka** [comment]
Are you getting the green alert at the top when saving the settings? Also what data storage option are you using XML?

**Comment by mgunther68** [comment]
Yes I'm getting green confirmation at the top. And I'm using XML (i.e. no advanced portal setup).

**Comment by jprochazka** [comment]
Navigation settings are fixed.
6a9056df722281ed871121c1019051165de3ff80
