### ISSUE TITLE
How to change port in portail 80 -> 8080 ?

### ISSUE THREAD

**Issue by disquette38** [jprochazka/adsb-receiver#143]
Hello 

How to change the port in portail to 8080, and change the last update with my local time ???
Thank

**Comment by jprochazka** [comment]
To change the port Lighttpd to listens on opening the file /etc/lighttpd/lighttpd.conf and changing the server.port setting the port you want.

Plot times are based on the time the server is set to. I will be changing this so all times are saved as UTC and converted to a time zone of choice in the portal. Until then set the proper time zone on your device using the following command.

    sudo dpkg-reconfigure tzdata
