### ISSUE TITLE
Flights tab visibility

### ISSUE THREAD

**Issue by paranoidjack** [jprochazka/adsb-receiver#144]
The Flights tab is only visible when the Blog is enabled.

Orange PI PC / Armbian | Apr 6, 2016 revision - adsb-receiver using MySQL

**Comment by jprochazka** [comment]
Fixed in commit eff75b058121b7363e6ac948101cecefb4bd8f6c.

**Comment by radiostationx** [comment]
Flights tab still visible when lite version is installed.
No option in portal to remove flight search box.
