### ISSUE TITLE
Use bash to setup the portal.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#147]
Use bash to setup the portal and remove the PHP installer from the portal files.

**Comment by jprochazka** [comment]
This change will be put off indefinitely.
I am not sure if this will clash with future plans.

**Comment by Romeo-Golf** [comment]
Does this have any relevance to https://github.com/jprochazka/adsb-receiver/issues/251 ?

**Comment by jprochazka** [comment]
It might and then again it might not.
It depends on if/when I get around to this issue...

I have a feeling that #251 will be completed and closed before this one.

**Comment by jprochazka** [comment]
The portal is getting a total rewrite and in the near future the portal will be stored in it's own repository so there is no need to track future enhancments here.
