### ISSUE TITLE
Add the ability to specify Lat and Lon for dump978.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#148]
Add the ability to specify the latitude and longitude of the dump978 receiver much like you can for dump1090.

**Comment by Romeo-Golf** [comment]
latitude and longitude you say?...  #258  :+1:

**Comment by jprochazka** [comment]
Adding latitude and longitude when setting up dump978 is now optional.
_The only place the latitude and longitude is used is in the map configuration._
commit f872eaf65f56266b232532a5a6c9fe3e73d4092d
