### ISSUE TITLE
System Information Bandwidth Guages

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#150]
Hi Joe,
Scale is fixed now in kbps but bandwidth guages stuck at zero,collectd performance graph is logging bandwidth correctly. New Install from scratch with latest updates 13/4/16.
Update ; Guages seem to work fine in kbps when eth0 is activiated and is the chosen interface to monitor but do not work when wlan0 is active and chosen.

**Comment by jprochazka** [comment]
I made a change to the file ~/adsb-reciver/build/portal/html/api/system.php which should resolve this issue. To fix your installation without having to go through the installation process again replace the contents of /var/www/html/api/system.php with the contents of the modified file found at https://raw.githubusercontent.com/jprochazka/adsb-receiver/master/build/portal/html/api/system.php.
