### ISSUE TITLE
Add ability to show metric measurements in dump1090.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#151]
Ask the user if they wish to use metric or imperial measurements when setting up dump1090-mutability. If this can be made possible securely add the ability to the administration panel as well.

**Comment by Romeo-Golf** [comment]
metric good....  although I seem to recall one of the feeders requires the user to input the receiver elevation in some strange unit which I cant quite recall... was it hands, or perhaps feet? ;)

**Comment by jprochazka** [comment]
Changes to dump1090's configuration should have no effect on any other altitude setting.

**Comment by jprochazka** [comment]
Added to dump1090-mutability setup script in commit 3801d8b379ec1373c554420d5d4ad2d2905875c6.
