### ISSUE TITLE
Add posibility to configure upintheair plot in the admin / settings

### ISSUE THREAD

**Issue by hasselk** [jprochazka/adsb-receiver#157]
It would be nice if one could enable/disable the plot.
even better would it be, if one could change parameters like stroke/fill colour opacity stoke thickness.

if one could add multiple plots(different hights, or reciever plot), that would be absolutely great.

**Comment by jprochazka** [comment]
Will see what I can do.

**Comment by jprochazka** [comment]
This has been added to my next gen portal TODO list. I am going to close this issue due to the fact that In the near future the portal will reside in it's own repository. The new portal is a total rewrite and totally different creature making most all portal issues posted here invalid.
