### ISSUE TITLE
Handle jobs raspi-config normally handles.

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#160]
Is it possible to expand file system ,add country, timezone and wifi country within ./install.sh script without visiting raspi-config.

Current default is USA,New York.

No big issue but having these options contained in the script would make things slick.
Perhaps a solution would be to include a brief automated diversion to sudo raspi-config during install.
Thanks.

**Comment by jprochazka** [comment]
With the upcoming v2.0.2 release I am going to try a new resize script which should automatically handle the resizing of the image to fill the drive when first booted up.

https://github.com/Drewsif/PiShrink

It is a neat little trick that backs up the existing /etc/rc.local within the image and replaces it with one that executes raspi-config --expand-rootfs after booting up then when finished restores the original rc.local and reboots the system.

This should get rid of one of the steps for now.

**Comment by jprochazka** [comment]
This will be a tentative addition to v3.0.0 but I will look into adding the ability to change locales and time zones from within the install script.

**Comment by jprochazka** [comment]
I am going to pass on this.
It seems to me it would be like reinventing the wheel.
