### ISSUE TITLE
Error about missing mysql module

### ISSUE THREAD

**Issue by stevepmitchell** [jprochazka/adsb-receiver#161]
Just updated to the newest available client on two systems.  After choosing to use the advanced mode, and setting up SQLite in the UI, I am continually getting a python error at the command line:

ImportError: No module named MySQLdb
Traceback (most recent call last):
  File "/home/pi/adsb-feeder/build/portal/logging/flights.py", line 45, in <module>

Looks like even though I'm not using MySQL that module is being called.  After installing the module (my distribution it is through apt "apt-get install python-mysqldb") I am getting SQL errors for what looks like MySQL commands, even though I do have it setup for SQLite:

Traceback (most recent call last):
  File "/home/pi/adsb-feeder/build/portal/logging/flights.py", line 77, in <module>
    cursor.execute("SELECT COUNT(*) FROM adsb_aircraft WHERE icao = %s", aircraft["hex"])
sqlite3.OperationalError: near "%": syntax error

**Comment by stevepmitchell** [comment]
It also does not appear that any data is being written to any database, even SQLite as I cannot search or find any flight history on either system.

**Comment by jprochazka** [comment]
Posted a fix.
Please replace flights.py with the current version found at https://github.com/jprochazka/adsb-receiver/blob/master/build/portal/logging/flights.py or apply the patch found [here](https://www.adsbreceiver.net/2016/04/17/patch-v2-0-0-2016-4-17-1-available/).

**Comment by stevepmitchell** [comment]
Thanks.  Downloaded and patched my two systems, but the SQLite database still seems to be 0 size, and I can't search or find any flights.

**Comment by jprochazka** [comment]
Will test SQLite logging and apply any needed fixes before the v2.0.1 release.

**Comment by jprochazka** [comment]
The Python SQLite library needed the query parameters written different. SQLite specific queries have been rewritten and tested.

Another issue was found pertaining to SQLite which was fixed for the installer. Make sure all SQLite tables start with adsb_ and that /var/www/html/classes/settings.class.php has "adsb_" set for the db_prefix value.
