### ISSUE TITLE
Squawk codes not entered into database correctly

### ISSUE THREAD

**Issue by nzradar** [jprochazka/adsb-receiver#169]
When searching a flights record in adsb_positions table there incorrect squawk entries for many flights.  An aircraft squawking 5074 on a particular sector has an additional squawk entry of 5070 as seen below:

553 | 2016-04-25 09:28:21 |   14383 |   5070
553 | 2016-04-25 09:28:40 |   14538 |   5074
553 | 2016-04-25 09:29:00 |   14700 |   5074
553 | 2016-04-25 09:29:19 |   14859 |   5074
553 | 2016-04-25 09:29:39 |   15012 |   5074
553 | 2016-04-25 09:29:59 |   15177 |   5070
553 | 2016-04-25 09:30:21 |   15372 |   5070
553 | 2016-04-25 09:30:40 |   15527 |   5074
553 | 2016-04-25 09:31:00 |   15683 |   5074

This happens on many flights.

**Comment by jprochazka** [comment]
More than likely the message was garbled slightly when received and decoded by dump1090. I see this from time to time when viewing the dump1090 map. An aircraft may appear to be squawking something like 7500 or 7700 even though there is no actual hijacking or emergency taking place. I would recommend when viewing this data go with the squawk that seems to dominate the data as the actual one.
