### ISSUE TITLE
Update to v2.0.1 issue

### ISSUE THREAD

**Issue by chacy169** [jprochazka/adsb-receiver#183]
Hello guys,
After I Update use 
cd ~/adsb-receiver
git fetch --all
git reset --hard origin/master
./install.sh

When I open the portal, it always jump to http://192.168.1.55/install/upgrade.php no matter what I do.

How to solve this problem?

Thanks in advance.

**Comment by jprochazka** [comment]
Honestly I am not sure why this is happening and I am working on getting some sort of fix together...

This is something I have noticed here and there but has happened more so while testing all the different installation scenarios for this release. Lighttpd or PHP-CGI seems to intermittently not handle post data properly.

If you run into a problem during the PHP installation portion where you are forwarded to the page /install/upgrade.php after submitting the form found at /install/ delete the file /var/www/html/classes/settings.class.php and visit the /install/ URL once more.

Related to this issue:
https://github.com/jprochazka/adsb-receiver/issues/175

**Comment by chacy169** [comment]
Hi Jprochazka,

It works to me again. Because I reboot my rpi, then I click the dump1090, which shows me dump1090 not running, so I reinstall the system again, but it still not working, so I update, then it shows error as above, my hardware is rpi3 and system is noobs 1.9.0. Hope this can help you find issue

Warm regards,
