### ISSUE TITLE
Unable to Use Remote Database

### ISSUE THREAD

**Issue by nzradar** [jprochazka/adsb-receiver#184]
With release 2.0.1 fresh install I want to use Advanced features and store my data on a remote server.  The remote server is a managed web host and a root password is not allowed.  All database admin is done using the assigned user or users created by the assigned user.  I have a number of databases running on the remote server and have had the adsb-receiver running as such since inception.  However, during the install I cannot 'skip' the root password question yet the script isn't actually going to create the database or tables, is that right?  The database and tables I wish to use are already created so I expected to be asked for a username and password and database for the connection string.

**Comment by jprochazka** [comment]
Added the ability to specify a non root user to create the database and user using the bash script in commit 1e909927d98951a2da0f1ad0403b00c9f49d8de0.
