### ISSUE TITLE
no save buttons in portal v2.0.2

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#193]
Hi Joe,
Upgraded system to new v2.0.2 with lite options.
Had problems initially with saving settings when running ip_of_device/install   
Deleted file /var/www/html/classes/settings.class.php and ran 
ip_of_device/install    one more time
no save buttons to save user settings in web portal so for example I cannot save wlan0 for monitoring, keeps reverting back to default eth0.

**Comment by jprochazka** [comment]
Fixed in commit d86c7e1028943698882d42bd5e61531136e8d35b.
You grabbed this version a little bit early doing final testing now on a new image.
