### ISSUE TITLE
Add SQLite database path to settings.class.php.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#196]
Currently the path to the SQLite database is hardcoded into common.class.php. The path to the databse file should be stored in the file settings.class.php and the path to the file taken from there by common.class.php.

**Comment by caiusseverus** [comment]
It would be very useful if the sqlite database location was customisable on installation. This would make it easier to add an external hard drive for advanced installations rather than having to completely reinstall or to set up links to move it there.

**Comment by jprochazka** [comment]
Will be adding this in v2.1.0.

**Comment by jprochazka** [comment]
Adding to v3.0.0 which will contain an overhauled installation process.

**Comment by jprochazka** [comment]
Completed in commit d075e6088b995d86dd9f80273fdbbbcacbe79db4.
