### ISSUE TITLE
When bind to all interfaces is used IPV6 doesn't work.

### ISSUE THREAD

**Issue by jthawkes** [jprochazka/adsb-receiver#199]
When bind to all interfaces is used IPV6 doesn't work.
Consider changing it from 
NET_BIND_ADDRESS="0.0.0.0"
to 
#NET_BIND_ADDRESS="0.0.0.0"

**May 13 03:15:17 tardis2 piaware[749]: mlat-client(859): Beast-format results connection with ::1:30104: [Errno 111] Connection refused**
May 13 03:15:54 tardis2 piaware[749]: mlat-client(859): Beast-format results connection with 127.0.0.1:30104: connection established
May 13 06:46:31 tardis2 piaware[749]: mlat-client(859): Beast-format results connection with 127.0.0.1:30104: connection lost
May 13 06:47:31 tardis2 piaware[749]: mlat-client(859): Beast-format results connection with 127.0.0.1:30104: connection established
May 13 09:19:28 tardis2 piaware[535]: Starting multilateration client: /usr/lib/piaware/helpers/fa-mlat-client --input-connect localhost:30005 --input-type dump1090 --results beast,connect,localhost:30104 --results beast,listen,30105 --results ext_basestation,listen,30106 --udp-transport 70.42.6.198:7418:1982839014
May 13 09:19:29 tardis2 piaware[535]: mlat-client(586): Beast-format results connection with ::1:30104: [Errno 111] Connection refused
May 13 09:19:59 tardis2 piaware[535]: mlat-client(586): Beast-format results connection with 127.0.0.1:30104: connection established
May 13 09:30:47 tardis2 piaware[535]: mlat-client(586): Beast-format results connection with 127.0.0.1:30104: connection lost
Change script to comment out bind section
it now binds to IPV6
May 13 09:30:57 tardis2 piaware[1811]: Starting multilateration client: /usr/lib/piaware/helpers/fa-mlat-client --input-connect localhost:30005 --input-type dump1090 --results beast,connect,localhost:30104 --results beast,listen,30105 --results ext_basestation,listen,30106 --udp-transport 70.42.6.198:7440:3602295029
**May 13 09:30:58 tardis2 piaware[1811]: mlat-client(1861): Beast-format results connection with ::1:30104: connection established**

**Comment by jprochazka** [comment]
Instead of setting the configuration variable NET_BIND_ADDRESS to 0.0.0.0 the script now comments out this variable in order to bind all interfaces.

Commit 376ab244f8c2f3127f0484d7046d006a7a640f93.
