### ISSUE TITLE
Unable to login after update to v2.0.3

### ISSUE THREAD

**Issue by JaapOnline** [jprochazka/adsb-receiver#206]
After the ADS-B Receiver Portal Update to v2.0.3, I'm not able to login to the "ADS-B Administration" anymore with the credentials I supplied earlier. How to get acces again ??

**Comment by kochiy** [comment]
How about that key??

Default Login: admin
Default Password: adsbreceiver

https://github.com/jprochazka/adsb-receiver/wiki/Configuring-the-Portal

**Comment by JaapOnline** [comment]
problem is solved, thanks for the reply !
