### ISSUE TITLE
exact location incorrect on Live Dump1090 map

### ISSUE THREAD

**Issue by Cornmeister** [jprochazka/adsb-receiver#213]
not sure if its a adsb-receiver issue, or a dump1090-mutability issue,

looks like the receiver location on the live map is not ok.
I've tried the approximate and exact option,

both settings write 'approx' data to the receiver.json:

pi@raspberrypi:/run/dump1090-mutability $ more receiver.json
{ "version" : "v1.15~dev", "refresh" : 1000, "history" : 8, "lat" : 52.000000, "lon" : 4.000000 }

instead of "lat" : 52.058885, "lon" : 4.341138

**Comment by jprochazka** [comment]
Check the file in particular the LAT and LON variables and make sure they match the proper coordinates. If they do I wouldn't worry too much about it.

Looking at the output of my receiver.json it is cut short showing LAT at 41.39 and lon at -82.08. I am guessing the actual LAT and LON are masked so as not to make available the exact location of your receiver to the public which might be what you are seeing.

This being said I think your dump1090 setup is more than likely fine. If when checking the file /etc/default/dump1090-mutability you notice the LAT and LON are in fact set wrong reopen this ticket and let me know and I will look into it.

**Comment by gonzalu** [comment]
[https://github.com/mutability/dump1090/issues/105]
