### ISSUE TITLE
No an issue but a question: How I can combine 978 and 1090 traffic in one ?

### ISSUE THREAD

**Issue by kalustian** [jprochazka/adsb-receiver#217]
Hi,

I know there is a separate data extract for dump978 and 1090...using either dump1090/data/aircraft.json or dump978/data/aircraft.json.

My question is: how  can I have both data traffic in the same json? or how can I send the 978 traffic over the dump1090/data/aircraft.json so all 978 and 1090 traffic can be seen in just one http link ??

Thanks,

**Comment by kalustian** [comment]
never mind...I think a got my answer,,,

**Comment by jprochazka** [comment]
dump978 data is fed to dump1090 so dump1090's aircraft.json already contains aircraft from both.

**Comment by kalustian** [comment]
thanks...
