### ISSUE TITLE
Positions not being recorded in MySQL database after fresh v2.2.0 install

### ISSUE THREAD

**Issue by jdwall** [jprochazka/adsb-receiver#218]
Hey Joe,

Thanks for all your work on this project. I am encountering an issue with a fresh `v2.2.0` install. Although `adsb_aircraft` and `adsb_flights` are _sometimes_ populated, `adsb_positions` is never. 

`adsb_aircraft` has 59 records
`adsb_flights` have 18 records
`adsb_positions` have 0 records

All of that being said, I _typically_ can see 40 airborne aircraft with positions at a time, so for whatever reason it sometimes is working on updating `adsb_aircraft` and `adsb_flights` but never `adsb_positions`. 

To my understanding, the script that handles pushing the data to MySQL is `flights.py`. [Here](http://pastebin.com/93UEKbkF
) is my `flights.py` located at `/home/pi/adsb-receiver/build/portal/logging`. Here is also a snapshot in time of the [output](http://pastebin.com/T1dRNH6R) of `http://IP/dump1090/data/aircraft.json` if that is of any help. 

==== How I installed adsb-receiver ====

I installed it via the `v2.2.0` release image, and then:

```
cd ~/adsb-receiver
git fetch --all
git reset --hard origin/master
./install.sh
```

Selected advanced settings → logged in the admin interface and again selected advanced settings and to use remote MySQL. I am sure the answer is right in front of me, but I am struggling to figure this out still. Thank you for the help! 

I also want to point out that autoincrement is really high for `adsb_aircraft` and `adsb_flights`, was that intentional?

```
CREATE TABLE `adsb_aircraft` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `icao` varchar(24) NOT NULL,
  `firstSeen` datetime NOT NULL,
  `lastSeen` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=30114 DEFAULT CHARSET=utf8;
```

```
CREATE TABLE `adsb_flights` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `aircraft` int(11) NOT NULL,
  `flight` varchar(100) NOT NULL,
  `firstSeen` datetime NOT NULL,
  `lastSeen` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11026 DEFAULT CHARSET=utf8;
```

**Comment by webdoodle** [comment]
I'm having a similar problem.  I was setting up MySQL so that I could access it remotely, and then the tables disappeared.  I used the about create script to recreate the aircraft and flights tables, but what else am I missing?  Can you provide create table scripts for all tables?

**Comment by jprochazka** [comment]
**@jdwall**

I just took a look at my development machine and can see this indeed appears to be an issue.

There is a newer version of the file flights.py which @adamkaplan created a merge request for. After I get that merged I will take a look again at it. The development of the advanced portion of the portal was put on hold until I got caught up with non portal issues which had piled up in my recent absence. I should be back at it after the next release.

As far as auto increment goes mine are incrementing by 1.
Is this different for you?

**@webdoodle** 

Here is the SQL to create the database.
_(This is minus the FAA database table which will not be used and be removed in a future release.)_

```
CREATE TABLE '.$dbPrefix.'administrators (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(75) NOT NULL,
  login VARCHAR(25) NOT NULL,
  password VARCHAR(255) NOT NULL);
```
```
CREATE TABLE '.$dbPrefix.'aircraft (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  icao VARCHAR(24) NOT NULL,
  firstSeen datetime NOT NULL,
  lastSeen datetime NOT NULL);
```
```
CREATE TABLE '.$dbPrefix.'blogPosts (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  date datetime NOT NULL,
  author VARCHAR(100) NOT NULL,
  contents VARCHAR(20000) NOT NULL);
```
```
CREATE TABLE '.$dbPrefix.'flightNotifications (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  flight VARCHAR(10) NOT NULL);
```
```
CREATE TABLE '.$dbPrefix.'flights(
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  aircraft INT(11) NOT NULL,
  flight VARCHAR(100) NOT NULL,
  firstSeen datetime NOT NULL,
  lastSeen datetime NOT NULL);
```
```
CREATE TABLE '.$dbPrefix.'positions (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  flight BIGINT NOT NULL,
  aircraft BIGINT NOT NULL,
  time datetime NOT NULL,
  message INT NOT NULL,
  squawk INT(4) NULL,
  latitude DOUBLE NOT NULL,
  longitude DOUBLE NOT NULL,
  track INT(11) NOT NULL,
  altitude INT(5) NOT NULL,
  verticleRate INT(4) NOT NULL,
  speed INT(4) NULL);
```
```
CREATE TABLE '.$dbPrefix.'settings (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  value VARCHAR(100) NOT NULL);
```

**Comment by webdoodle** [comment]
Thank you!  I ended up wiping the box and starting from scratch, as I'm pretty sure I somehow either missed a step or got them out of order.   It seems to be working great.  Thank you so much for your help!

**Comment by jprochazka** [comment]
OK...
I did some digging into my test advanced portal and found some things missing. Fixes along with the new flights.py submitted by @adamkaplan have been added to the 2.2.1 branch which should be released this weekend or at the latest early next week.

7fa44bd33107cc4a97f4437433e950936cd88c85

First off check the file /etc/rc.local and make sure that the following lines exist.
_(Make sure you change the path so it is correct!)_

```
/home/pi/Projects/adsb-receiver/build/portal/logging/flights-maint.sh &
/home/pi/Projects/adsb-receiver/build/portal/logging/maintenance-maint.sh &
```

Next just to be safe make sure the following files exist and point to the right places.

/home/pi/Projects/adsb-receiver/build/portal/logging/flights-maint.sh

```
#!/bin/sh
while true
  do
    sleep 30
        /usr/bin/python /home/pi/Projects/adsb-receiver/build/portal/logging/flights.py
  done
```

/home/pi/Projects/adsb-receiver/build/portal/logging/maintenance-maint.sh

```
#!/bin/sh
while true
  do
    sleep 30
        /usr/bin/python /home/pi/Projects/adsb-receiver/build/portal/logging/maintenance.py
  done
EOF
```

/home/pi/Projects/adsb-receiver/build/portal/logging/config.json
_(Make sure to check the database name and credentials.)_

{
    "database":{"type":"mysql",
                "host":"localhost",
                "user":"DBUSER",
                "passwd":"DBPASSWD",
                "db":"DBNAME"}
}

**Comment by jdwall** [comment]
I pulled `2.2.1` and reinstalled from there. `auto_increment` is correct, once installed, as one. However, once installed, auto_increment continues to go up. 

FYI with `2.2.1` it does not populate `config.json`. Just putting that on your radar, you may know but not sure if it's worth submiting an issue. 

If I manually run `flights-maint.sh` I receive the following output:

```
pi@raspberrypi:~/adsb-receiver/build/portal/logging $ ./flights-maint.sh
Traceback (most recent call last):
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 201, in <module>
    processor.processAircraftList(data["aircraft"])
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 104, in processAircraftList
    self.processAircraft(aircraft)
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 131, in processAircraft
    self.processFlight(aircraft_id, aircraft)
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 155, in processFlight
    self.processPositions(flight_id, aircraft)
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 169, in processPositions
    self.cursor.execute(self.STMTS['insert_position_sqwk'], params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1364, "Field 'aircraft' doesn't have a default value")
Traceback (most recent call last):
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 201, in <module>
    processor.processAircraftList(data["aircraft"])
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 104, in processAircraftList
    self.processAircraft(aircraft)
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 131, in processAircraft
    self.processFlight(aircraft_id, aircraft)
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 155, in processFlight
    self.processPositions(flight_id, aircraft)
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 169, in processPositions
    self.cursor.execute(self.STMTS['insert_position_sqwk'], params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1364, "Field 'aircraft' doesn't have a default value")
Traceback (most recent call last):
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 201, in <module>
    processor.processAircraftList(data["aircraft"])
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 104, in processAircraftList
    self.processAircraft(aircraft)
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 131, in processAircraft
    self.processFlight(aircraft_id, aircraft)
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 155, in processFlight
    self.processPositions(flight_id, aircraft)
  File "/home/pi/adsb-receiver/build/portal/logging/flights.py", line 169, in processPositions
    self.cursor.execute(self.STMTS['insert_position_sqwk'], params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1364, "Field 'aircraft' doesn't have a default value")
```

If I run `maintenance-maint.sh` there is a mistake with the path referenced:

```
pi@raspberrypi:~/adsb-receiver/build/portal/logging $ ./maintenance-maint.sh
/usr/bin/python: can't open file '/home/pi/adsb-receiver/build/portal/portal/logging/maintenance.py': [Errno 2] No such file or directory
```

After fixing the extra `/portal/portal/` reference I re-ran `maintenance-maint.sh` and received the following output:

```
pi@raspberrypi:~/adsb-receiver/build/portal/logging $ ./maintenance-maint.sh
  File "/home/pi/adsb-receiver/build/portal/logging/maintenance.py", line 153
    cursor.execute("DELETE FROM adsb_positions WHERE time < ?", params)
    ^
IndentationError: unexpected indent
  File "/home/pi/adsb-receiver/build/portal/logging/maintenance.py", line 153
    cursor.execute("DELETE FROM adsb_positions WHERE time < ?", params)
    ^
IndentationError: unexpected indent
  File "/home/pi/adsb-receiver/build/portal/logging/maintenance.py", line 153
    cursor.execute("DELETE FROM adsb_positions WHERE time < ?", params)
    ^
IndentationError: unexpected indent
```

I fixed the extra indentation and then re-reran `maintenance.py`. After that, I am getting

```
Traceback (most recent call last):
  File "/home/pi/adsb-receiver/build/portal/logging/maintenance.py", line 35, in <module>
    while true:
NameError: name 'true' is not defined
Traceback (most recent call last):
  File "/home/pi/adsb-receiver/build/portal/logging/maintenance.py", line 35, in <module>
    while true:
NameError: name 'true' is not defined
```

I commented out `while true:` and... then I got frustrated I couldn't make it work because I don't know python lol.

**Comment by jdwall** [comment]
Okay, so, now even with all those changes I was able to get the script to import data into the database. However, I had to change around how `adsb_positions` was structured. Now, I have no `aircraft` as they are all `NULL` but I can easily cross-reference and build a `VIEW` that works around that. :-)

```
CREATE TABLE `adsb_positions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `flight` bigint(20) NOT NULL,
  `aircraft` bigint(20) DEFAULT NULL,
  `time` datetime NOT NULL,
  `message` int(11) NOT NULL,
  `squawk` int(4) DEFAULT NULL,
  `latitude` double NOT NULL,
  `longitude` double NOT NULL,
  `track` int(11) NOT NULL,
  `altitude` int(5) NOT NULL,
  `verticleRate` int(4) NOT NULL,
  `speed` int(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8;
```

**Comment by jprochazka** [comment]
**config.json**

I have been debugging the 2.2.1 branch. It was more than likely in a very "rough" state when you pulled it. There have been changes since your last pull I am sure being that is what I am working on right now. :)

**NULL aircraft column**

Looking into the NULL aircraft field. More than likely this is not being populated by the flights.py @adamkaplan submitted due to the fact the aircraft column was added in a branch that was merged after he had completed the work on this file and submitted it.

Thanks for hanging in there and reporting the issues! It looks like it is starting to get back to where it was before my extended leave and the merge made after returning and forgetting where I left off...

**Comment by jprochazka** [comment]
A modified flights.py which should resolve the aircraft ID not being added with other position data has been committed to the 2.2.1 branch. This should resolve the NULL aircraft column data issue.

https://raw.githubusercontent.com/jprochazka/adsb-receiver/2.2.1/build/portal/logging/flights.py

Commit 48c9e07ae366ef714319b5b6eaaa368b2ceded6c
