### ISSUE TITLE
Whiptail checkbox writing results to file.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#22]
Need to figure out how to output the whiptail checkbox results to a variable that can be used to loop through instead of whiptail writing the results to a file in install.sh. For the time being the file generated by whiptail is being manually deleted by the script when exiting the script.

**Comment by jprochazka** [comment]
This is a minor non issue which does not need addressed.

**Comment by gimli2** [comment]
Try to redirect otputs:
sel=$(whiptail --checklist "Please pick one" 10 60 5 one one off two two on  3>&1 1>&2 2>&3);

(http://stackoverflow.com/questions/1970180/whiptail-how-to-redirect-output-to-environment-variable)
