### ISSUE TITLE
Feature request: Add support for, and make use of, GPS receivers

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#223]
(feature request)

Some users may have a GPS receiver attached to their ADSB tracking Pi, typically via serial port, so in addition to providing assistance with the tools and config needed for this to work it would be great if the resulting location information can be used ;)

I notice that piaware detects and connects to gpsd (if running) but in order to take full advantage of this capability I would suggest considering:

1) Making an option in the install script to attempt to configure GPSD, if so then packages such as gpsd gpsd-clients python-gps pps-tools, and perhaps even ntp... as per the following guide aimed at using the Pi as an NTP server there are some other steps such as updating the /boot/config.txt that may also benefit from being done here:

http://www.satsignal.eu/ntp/Raspberry-Pi-quickstart.html

2) Attempt to start gpsd and if it aquires a location then prompt the user to use this, or a manual correction, at any subsequent steps in the installation which currently prompt the user to enter LAT/LON/ELEVATION

3) display the output of cgps on the 'system information' tab of the web interface

4) graphs the various information provided by gpsd on the 'performance graphs' tab of the web interface, ideally one each for the LAT/LON/ELEVATION with the value, reported error rate and trending if possible to make it easy to spot if these values are drifting...  the time offset may also be useful...

5)  if we wanted to make the most out of a a GPS receiver attached to a Pi then setting up NTP to use this, and a PPS signal wired from the GPS to a GPIO pin, would be awesome.. but given the number of different approached taken by the various guides this is probably at least as much work as making use of the positioning information :)

**Comment by Romeo-Golf** [comment]
While it may be some time before we have a Raspberry Pi with built in GPS receiver, I would hope im not the only user who has added one of these to their Pi for other purposes...

I think that ensuring NTP is running is particularly important since MLAT depends on accurate time signals so I will split that out into a separate feature request; however in the mean time I am interested to know if anyone else would find it beneficial to have the option to configure GPSd and use the hopefully accurate position of the receiver for any/all elements of the adsb-reciever distribution?

**Comment by jprochazka** [comment]
There are not enough devices and not enough demand to justify adding a feature such as this at this time.
