### ISSUE TITLE
log to remote *SQL server

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#225]
(feature request)

While i suspect it could be setup manually following an advanced install, it would be nice if the install script provided the option to configure logging to a remote *SQL (or perhaps just mysql) server and provide a link to download the template for the database that would be expected on the remote server.

Hopefully this would allow users to combine the benefits of logging data for later analysis, and potentially features such as overlaying historical signals onto the map to show 'coverage', while retaining the low cost and east of deployment of a Pi booting from an SD card ;)

**Comment by jdwall** [comment]
Are you referencing something along the lines of remote-syslog? Papertrail has a project here on GitHub https://github.com/papertrail/remote_syslog2/

For context, here is their remote logging setup for centralized logs. http://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-text-log-files-in-unix/#remote_syslog

**Comment by jprochazka** [comment]
This is a feature available when selecting to install the advanced portal features if you are referring to retaining aircraft, flights, and position data. Currently remote logging to remote MySQL servers is supported but once PostgreSQL support is added that will be an available option as well.

If it is a different type of logging other than aircraft, flights, and positions you are looking for let me know.
