### ISSUE TITLE
How to get weather report ( TAF..METAR ..Winds..etc ) via web/json ?

### ISSUE THREAD

**Issue by kalustian** [jprochazka/adsb-receiver#227]
Hi,

I could be able to install and get successfully trafiic for 1090 and 978 via data/aircraft.json. I was wondering if there is a way to get wether information as well.

Thanks

**Comment by jthawkes** [comment]
The later versions of Dump1090-mut contain US NEXRAD weather. I have been running them for about 1 month. It just gives the weather radar view. No other details as far as I can see.

https://github.com/cyoung/stratux has their version of dump978 that should be able to provide these details. It would be interested to see what can be done with their version.

**Comment by kalustian** [comment]
They have it available via websocket...but i was wondering if there is a way via json.

**Comment by jprochazka** [comment]
I take it your looking for METARS/AIRMET/SIGMET data to be displayed on the dump1090-mutability web page. The information is available via [NOAA](http://www.aviationweather.gov/dataserver) and is available in XML format.

However...

Making changes to the dump1090-mutability map, which is part of a separate project, is beyond the scope of this project. My plate is full at this time and focusing my free time on this project has become my first priority. There are plans to create maps to display dump1090 and dump978 maps specifically built for this project in the hopefully near future but right now my goal is to get the flight logging and aircraft information features done first.

I will leave this issue open as a reminder once I am to that point as well as a place for others to offer suggestions and ideas on where and how to get this information if gathering the mentioned data from NOAA is not the answer people are looking for.

**Comment by kalustian** [comment]
I was just curious is that was something already available or can be done easily - no problem at all - like this project - Thanks-
