### ISSUE TITLE
Add CPU temperature gauge.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#229]
Add a real time CPU temperature gauge to the system information page. 

Reading /sys/class/thermal/thermal_zone0/temp will not work in all cases as suggested.
Maybe install the lm-sensors package?

**Comment by jdwall** [comment]
Could you use `/opt/vc/bin/vcgencmd measure_temp`? 

```
pi@raspberrypi:~ $ /opt/vc/bin/vcgencmd measure_temp |grep -o '[0-9;.]*'
54.8
pi@raspberrypi:~ $
```

**Comment by jdwall** [comment]
What was your issue you encountered in using `/sys/class/thermal/thermal_zone0/temp`? I was able to get it to work fine. I'll open a PR with the gauge added. Give me a few minutes to finish up.

**Comment by jprochazka** [comment]
That is not a proper path on all distro. (File does not exist on Debian for example) The lm-sensor package seems to be the go to way. But I will take a look at your earlier suggestion once I have the v2.3.0 image which just needs shrunk, archived, and uploaded.

**Comment by jdwall** [comment]
I opened PR #231. I tried to use the `lm-sensor` package, and it will not work for Raspberry Pi's AFAIK. However, that isn't to say that one can't go back to the `install.sh` script and based on the operating system, install `lm-sensor` and make the necessary changes to `system.php` to make the appropriate modifications to the file based on the operating system. Thoughts?

```
root@raspberrypi:/# sudo sensors-detect
# sensors-detect revision 6209 (2014-01-14 22:51:58 +0100)

This program will help you determine which kernel modules you need
to load to use lm_sensors most effectively. It is generally safe
and recommended to accept the default answers to all questions,
unless you know what you're doing.

Some south bridges, CPUs or memory controllers contain embedded sensors.
Do you want to scan for them? This is totally safe. (YES/no): YES
modprobe: FATAL: Module cpuid not found.
Failed to load module cpuid.
Silicon Integrated Systems SIS5595...                       No
VIA VT82C686 Integrated Sensors...                          No
VIA VT8231 Integrated Sensors...                            No
AMD K8 thermal sensors...                                   No
AMD Family 10h thermal sensors...                           No
AMD Family 11h thermal sensors...                           No
AMD Family 12h and 14h thermal sensors...                   No
AMD Family 15h thermal sensors...                           No
AMD Family 15h power sensors...                             No
AMD Family 16h power sensors...                             No
Intel digital thermal sensor...                             No
Intel AMB FB-DIMM thermal sensor...                         No
VIA C7 thermal sensor...                                    No
VIA Nano thermal sensor...                                  No

Lastly, we can probe the I2C/SMBus adapters for connected hardware
monitoring devices. This is the most risky part, and while it works
reasonably well on most systems, it has been reported to cause trouble
on some systems.
Do you want to probe the I2C/SMBus adapters now? (YES/no): YES
Sorry, no supported PCI bus adapters found.

Sorry, no sensors were detected.
Either your system has no sensors, or they are not supported, or
they are connected to an I2C or SMBus adapter that is not
supported. If you find out what chips are on your board, check
http://www.lm-sensors.org/wiki/Devices for driver status.
root@raspberrypi:/#
```

**Comment by jprochazka** [comment]
RPi Support added with Pull Request https://github.com/jprochazka/adsb-receiver/pull/231.
Please note this is Raspberry Pi specific at this time and will not work on Debian or Ubuntu at this time. By the time v2.4.0 is ready support for PC distributions will be added.

**Comment by jprochazka** [comment]
As for the "sensors" post.

I added lm-sensor, well actually it was already installed by Linux Mint, Running the command "sensors" returned the following.

```
joe@mint ~/Projects/adsb-receiver $ sensors
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +33.0°C  (high = +76.0°C, crit = +100.0°C)
Core 1:       +28.0°C  (high = +76.0°C, crit = +100.0°C)
```

Went ahead and installed lm-sensor on my RPi receiver and as you reported no information was to be had. Pretty sad Raspbian is not keeping up on this package. It offers a lot of important information which would be nice to pass along...

Anyways I have been working in virtual machines mostly. Installing Linux mint on a physical machine the file /sys/class/thermal/thermal_zone0/temp appears to exist. This covers Linux Mint/Ubuntu but could have sworn I was unable to find said file on Debian...
