### ISSUE TITLE
Send a tweet when a flight seen.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#236]
Add the ability to send a tweet to twitter whenever a flight in the flight notification list has been seen.

**Comment by jprochazka** [comment]
Issue #238 is related to this issue.

**Comment by jprochazka** [comment]
Current Status and TODO list:
All changes are currently contained in the 2.4.0 branch.
_(Italicized text denotes items currently being worked on.)_

-[ ] _Add XML support._
-[ ] Add MySQL support.
-[ ] Add SQLite support.
-[ ] _Send tweet to Twitter when a flight is seen._
-[ ] _Send an email to the administrators when a flight is seen._
-[ ] Create an editable email template.
-[ ] Create an editable tweet template.

**Comment by jprochazka** [comment]
The Twitter additions I was working will be replaced with @kevinabrandon's project named [AboveTustin](https://github.com/kevinabrandon/AboveTustin) as long as things go well testing and creating the installation script for this project.

This feature in it's current form will be removed from the v2.5.0 release.

**Comment by jprochazka** [comment]
A test version containing an option to install AboveTustin will be made available in the upcoming v2.5.2 release which will feature this option. As long as the test release(s) go well look for an AboveTustin option to be made generally available in v2.6.0.

**Comment by jprochazka** [comment]
Got AboveTustin up and running in a test environment connected to my ADS-B receiver.
https://twitter.com/adsb_receiver

Everything's looking good will need to run through the installation scripts and add a way to choose extras.

**Comment by kevinabrandon** [comment]
@jprochazka how long does it take to tweet?  I think my setup takes about 5 to 10 seconds?

**Comment by jprochazka** [comment]
That's about right then. Honestly it is not a huge concern to me. It's been running fine since I switched over to my RPi. On my Debian box it was fairly instant but that box has a lot more juice to it.

**Comment by jprochazka** [comment]
Script completed and will be available in the new extras options to be made available in v2.6.0.
