### ISSUE TITLE
Add the ability to set a notification distance.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#237]
Instead of notifying whenever a receiver spots an aircraft add an option to set specify a maximum range an aircraft has to enter before notifying the user via the flight notification system.

Adding a minimum altitude option would be useful as well.

**Comment by Romeo-Golf** [comment]
While I haven't used the notification feature, I see that it lets you provide a list of aircraft of interest and have the system notify you... in which case being able to specify the maximum distance from site would be useful but perhaps for altitude we could have the option for maximum and/or minimum  values?

I would also be interested in notifications for any flight which fly over or near to the receiver location, or perhaps even some other user configured set of co-ordinates, would this be possible with the same sort of notification functionality?

In fact why stop there, it would be awesome if this could develop into a framework which allowed flexible alerting with filters based on any/all of the received data... allowing multiple notifications such as:

type = landplane AND range < 10000m AND altitude > 5000m
type = helicopter AND range < 1000m AND altitude < 500m

Or would that be better in a separate feature request for consideration in a future release?

**Comment by Romeo-Golf** [comment]
Any thoughts? :)

**Comment by jprochazka** [comment]
This has been added to my next gen portal TODO list. I am going to close this issue due to the fact that In the near future the portal will reside in it's own repository. The new protal is a total rewrite and totally different creature making most all portal issues posted here invalid.
