### ISSUE TITLE
Add whiptail for adding Bing and/or Mapzen API Keys

### ISSUE THREAD

**Issue by jdwall** [jprochazka/adsb-receiver#239]
Since `dump1090-mutability` moved away from Google Maps API to Open Street Map, I think it would be nice to have an option for users to add Bing and/or Mapzen API keys during the installation script. I've got a branch that I'm working on adding that functionality to. Will open a PR once done.

**Comment by jprochazka** [comment]
I am going to add this to the v2.4.0 milestone. More than likely this will be added to the portal administration page so it can be changed on the fly without the need to run the scripts again to add a key.

Related Issue: https://github.com/jprochazka/adsb-receiver/issues/207

**Comment by jdwall** [comment]
Much smarter. Want me to take that off your plate?

**Comment by jprochazka** [comment]
Up to you.
If you want it take it.

**Comment by jdwall** [comment]
Ill take it off your plate. :)

**Comment by jprochazka** [comment]
Added the ability to specify these keys using the bash scripts.
commit 5b3543a938e0346401313756833f861d31a3ad5c
commit 4c6ed7909339e8f046e1f436a9eaea766f131403
