### ISSUE TITLE
Ask for longitude and latitude when upgrading dump1090.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#240]
When upgrading or reinstalling dump1090-mutability the user should be presented with a dialog containing the currently set longitude and latitude so they can change these settings if needed.

**Comment by jprochazka** [comment]
Fixed in commit 029bd02ea00d84ff1a29f76912dd746bf990bcdc.

**Comment by Romeo-Golf** [comment]
could this value be stored somewhere that it can easily be used by other elements of the project such as when registering the receiver with some of the third party data sources?

If so would it also make sense to as the user for the elevation of their antenna, if know, or potentially look this up based on the LAT/LON?

**Comment by jprochazka** [comment]
The issue got buried once closed and I just now ran across this request. If you could open up another issue pertaining to this request I will look into adding this feature in the future. Anyways I am guessing you want this information available say on the system information page?
