### ISSUE TITLE
Suggestion: User configurable links in menu

### ISSUE THREAD

**Issue by Calimerorulez** [jprochazka/adsb-receiver#246]
Thanks for the great work on this project!

I have a suggestion: it would be nice to have user configurable links in the menu. I'm running Virtual Radar among other programs on the same computer as ADS-B receiver, and it would be nice to display a link to it in the top menu.

**Comment by jprochazka** [comment]
The theme needs some work come the next release. The work mainly involves the top navigation which I am thinking needs to utilize some sort of fly out navigation. Currently with all links on one line it is pushing the search filed on advanced installs down another line covering a portion of the maps. Let me see what I can do for you when I start work on the themes. It should be a fairly easy addition.

**Comment by jprochazka** [comment]
Added support for custom links in commit 24493a82653766af47099d846146407e5dab425f.
