### ISSUE TITLE
Feature request: Option to install NTPd and configure to use a local ntp server pool

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#249]
While I believe that NTP is installed by default on Rasperbian Jessie, this may not be the case on all Debian based distro's, and even then it may be configured to use a default global pool of NTP servers such as pool.ntp.org which could be less reliable than using NTP servers located in geographical proximity to the receiver.

Given that accurate time stamps are critical for MLAT, yet the Raspberry Pi lacks a battery backed RTC to retain its system time over a reboot, it would seem particularly useful for the adsb-receiver install script to either install ntp by default, or provide the option to do so if its not presently installed.

I am not sure if the system location is set at some point, or could be inferred from another source such as GPSd or even the, but it would be great if the default NTP server pool configured could be replaced with one which is likely to be closer to the receiver such as the country specific pools provided by ntp.org

Following the reconfiguration and restarting of ntpd the system should soon have a reasonably accurate time so it would make sense to ensure that this step is performed prior to the reporting of any data and ideally as early into the setup process as possible.

Finally to allow the users to confirm that NTP has synced with at least one NTP server it may be useful to display the output of 'ntpq -pn' on the admin section of the web interface:

```
/home/pi/adsb-receiver# ntpq -pn
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
+87.81.181.2     138.96.64.10     2 u  117 1024  377   18.498    9.071   6.687
+5.152.207.79    143.210.16.201   3 u 1035 1024  375   16.337    7.262   5.148
*178.79.160.57   131.188.3.221    2 u   83 1024  377   27.699    0.037   5.135

```

**Comment by Romeo-Golf** [comment]
Before I do anything towards adding GPS timing to NTP I just wanted to check your thoughts on:

Testing for, and if not present install, the stock NTP package?

Give the user the option either select their country manually, or derive this from the LAT/LON, to then configure NTP to use the per-country pools from ntp.org?

Where and how you think it best to display some sort of NTP status and synchronization information in the portal?

**Comment by jprochazka** [comment]
Use the CheckPackage function in bash/functions.sh. This will check if a package is installed and if not attempt to install it. If for some reason the function fails to install the specified package after 5 tries it will halt setup entirely.

```
# Source the file functions.sh
source bash/functions.sh

# Run the CheckPackage function (CheckPacakge <package name>)
CheckPackage ntp
```

**Comment by target-drone** [comment]
Would you consider using chrony?  RHEL 7 made the switch, and in quick testing here, they are pretty similar, but chrony seems to converge way faster, which is handy after a non-rtc device like a pi restarts, and produces a more stable clock, also handy on a pi where the relatively high cpu usage running dump1090 and the adsb portal scripts introduces jitter.  It doesn't do ntp broadcasts though, if anyone uses that.

**Comment by jprochazka** [comment]
I think this is getting a bit beyond the scope of things and does not add much value. Time would be better spent on more value add features.
