### ISSUE TITLE
Error installing Planefinder/FR24 client on Ubuntu ARM64

### ISSUE THREAD

**Issue by Calimerorulez** [jprochazka/adsb-receiver#252]
Hi,

I'm getting the following error when trying to install the Planefinder client on a Pine64, with Ubuntu ARM64:

dpkg: error processing archive pfclient_3.4.61_i386.deb (--install):
 package architecture (i386) does not match system (arm64)

Flightradar's feeder give the same error.

Some kind of work around seems to:

sudo dpkg --add-architecture armhf

and manually download the Planefinder armhf and installing it. For Flightradar I manually ran the install as described here:
http://forum.flightradar24.com/threads/8908-New-Flightradar24-feeding-software-for-Raspberry-Pie?p=66479#post66479

**Comment by jprochazka** [comment]
Just like with x86_64 systems I will need to add ARM64 detection so that the armhf architecture is added when needed. Thanks for pointing this out when looking into it I also noticed another issue which may effect Ubuntu users pertaining to adding the i386 architecture as well.

**Comment by jprochazka** [comment]
Could I pester you for the output of the following command on your PINE64 device so I get it right?
    uname -m

**Comment by jprochazka** [comment]
I went ahead and committed the changes if anyone still runs into this issue on PINE64 devices I will need an answer to the above question. The changes were part of commit 11b6770cf279b9e62fde7ce0115f77c8d33cec63.

**Comment by Calimerorulez** [comment]
Sorry for my late answer, I was on a holiday... It is indeed 'aarch64'.
