### ISSUE TITLE
Clean install gives error "Can't exec pyversions" on installing mlat-client

### ISSUE THREAD

**Issue by Calimerorulez** [jprochazka/adsb-receiver#253]
Having installed the package python-dev is required to run 'pyversions' :-)

**Comment by jprochazka** [comment]
The python3-dev package should have been installed which should have taken care of this requirement. It is at line 99 of adsbexchange.sh. What distribution are you running?

**Comment by Calimerorulez** [comment]
You are right, I meant python3-dev. I installed on Debian Jessie on a RPi, and on Ubuntu on my Pine64, and both distributions gave me that error about pyversions...

**Comment by jprochazka** [comment]
Will look into it.

**Comment by jprochazka** [comment]
Must be a package naming difrence between distributions.
The python-dev package is now required with commit 1e8ce8d5c71e3dd3a176fc33a4c85d55a28318bc.
This addition will be available in the soon to be released v2.5.0.
