### ISSUE TITLE
Small bugs :-)

### ISSUE THREAD

**Issue by Calimerorulez** [jprochazka/adsb-receiver#254]
In build/portal/logging/flights.py, on row 196, there is a hardcoded IP-address which gives me an error in /var/log/syslog. I changed it to 'localhost' and now it works fine.

In /home/pi/adsb-receiver/build/portal/logging/maintenance-maint.sh the executed statement/directory has two times 'portal' in it. Gives an error in /var/log/syslog too.

**Comment by jprochazka** [comment]
Forgot to change that back after testing...
The path in the logging setup script has been fixed as well.
