### ISSUE TITLE
upgrade 2.0.2 to 2.4 failed

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#257]
No "save settings" button in address/admin/install.php
Did not get option for lite install on set up of portal.
reset head back to 2.0.2 (1e311572f52f31bf9a8fe288dbaa1c3dcc2a8e57) and ran 
./install.sh again.
Went to set up portal page, save button was there and all went ok but now portal unreachable, map does not work, station still sending data to flightaware though.

I have had this problem before
https://github.com/jprochazka/adsb-receiver/issues/174#issuecomment-215992038

can reach
 localhost/install/.
and save settings button is there but when i try to change timezone (europe) and save the settings, it reverts back to africa.
Portal pages, map, performance etc do not function

Think I have found the answer as i had an existing image which i was trying to upgrade.
https://github.com/jprochazka/adsb-receiver/blob/master/README.md

Until I get time to do a fresh install, any ideas of a fix/rollback on my existing 2.0.2 please ?

**Comment by jprochazka** [comment]
Actually check the log file /var/log/lighttpd/error.log and post any messages you have there which occur when you try and visit the portal.

**Comment by radiostationx** [comment]
2016-10-11 13:39:52: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknow$
2016-10-11 13:39:52: (mod_fastcgi.c.2702) FastCGI-stderr: Stack trace:
2016-10-11 13:39:52: (mod_fastcgi.c.2702) FastCGI-stderr: #0 /var/www/html/blog.php(60): DateTimeZone->__construct('')
2016-10-11 13:39:52: (mod_fastcgi.c.2702) FastCGI-stderr: #1 {main}
2016-10-11 13:39:52: (mod_fastcgi.c.2702) FastCGI-stderr:   thrown in /var/www/html/blog.php on line 60

**Comment by jprochazka** [comment]
Can you get me the full line starting with:

> 2016-10-11 13:39:52: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknow$

There is more information I need after the **$**.
Thinking you might just be missing a setting is all.

**Comment by radiostationx** [comment]
2016-10-11 13:39:52: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknow$$Unknown or ba$Unknown or bad timezone ()' in /var/www/html/blog.php:60

**Comment by jprochazka** [comment]
Take it you are running the lite version of the portal. If so add the following to /var/www/html/settings.xml.

```
<?xml version="1.0" encoding="utf-8"?>
<settings>
...
    <setting>
        <name>timeZone</name>
        <value>America/New_York</value>
    </setting>
...
</settings>
```

Make sure to set the proper time zone afterwards in the admin area.
Let me know if you encounter any other issues.

**Comment by radiostationx** [comment]
Completed the change to  /var/www/html/settings.xml
enter admin area, timezone selections are there in list, save button is there, but any change will not save.
Reverts back to 1st item on list Africa.

Tried localhost/admin/install.php

The data directory is writable.
The settings.class.php file is writable.

No Save button or next button at foot of page.

**Comment by jprochazka** [comment]
> Completed the change to /var/www/html/settings.xml using nano (no file existed btw)

If this has the advanced portal features enabled, which I am guessing is the case if the .xml files are not present in the folder /var/www/html/data/, use the MySQL queries added to the post above.
If you are using SQLite the same queries should work.

```
sqlite /var/www/html/data/portal.sqlite
DELETE FROM adsb_settings WHERE name = 'timeZone';
INSERT INTO adsb_settings (name, value) VALUES ('timeZone', 'America/New_York');
```

**Comment by radiostationx** [comment]
Hi Joe, I had lite install and upgraded using the readme.
when i used install.sh, I did not get option for lite/data junkie
Now i have a receiver feeding to fr24,fa etc but portal will not work.
I wanted lite as before.
Do I make the change to /var/www/html/data/ as above ?

**Comment by radiostationx** [comment]
Hi Joe, files are in /var/www/html/data/
administrators.xml
blogposts.xml
flightnotifications.xml
placeholder.txt
settings.xml

**Comment by jprochazka** [comment]
Take a look at the error log once more lets see if we fix one issue and ran into another.

`cat /var/log/lighttpd/error.log`

**Comment by radiostationx** [comment]
Hi Joe,
Here we go.

2016-10-12 17:24:24: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Unca                                                                             ught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or                                                                              bad timezone ()' in /var/www/html/blog.php:60
2016-10-12 17:24:24: (mod_fastcgi.c.2702) FastCGI-stderr: Stack trace:
2016-10-12 17:24:24: (mod_fastcgi.c.2702) FastCGI-stderr: #0 /var/www/html/blog.                                                                             php(60): DateTimeZone->__construct('')
2016-10-12 17:24:24: (mod_fastcgi.c.2702) FastCGI-stderr: #1 {main}
2016-10-12 17:24:24: (mod_fastcgi.c.2702) FastCGI-stderr:   thrown in /var/www/h                                                                             tml/blog.php on line 60

**Comment by jprochazka** [comment]
That is still the same one...
OK so I got this right all the above XML files you listed exist.

> Completed the change to /var/www/html/settings.xml using nano (no file existed btw)

This file was empty?
If so lets do this...

Backup all .xml files located in the directory /var/www/html/data **EXCEPT** settings.xml and administrators.xml.

    mkdir ~/backups/
    sudo cp /var/www/html/data/*.xml ~/backups/
    sudo rm -f ~/backups/settings.xml
    sudo rm -f ~/backups/administrators.xml

Delete all .xml files in the directory /var/www/html/data/.

    sudo rm -f /var/www/html/data/*.xml

Delete settings.class.php.

    sudo rm -f /var/www/html/classes/settings.class.php

If you downloaded the latest master branch containing v2.4.0...

    cd ~/adsb-receiver
    ./install.sh

Skip installing install/reinstall everything if you wish EXCEPT the portal. Be sure to Install the portal when asked to. and follow all the instructions including going to the web based installer when told to.

Restore you old XML files.
(only necessary to restore any blog posts or the flight notification list.)

    sudo cp ~/backups/*.xml /var/www/html/data/

**Comment by radiostationx** [comment]
Hi Joe that worked and I now have portal but d1090 map view does not work.I just get spinning java wheel.
ctrl,shift j result is "Uncaught ReferenceError: google is not defined"
Nearly there !

**Comment by jprochazka** [comment]
That error is due to a missing Google Maps API key.
You may want to go ahead and update/rebuild dump1090-mutability using install.sh.

dump1090-mutability did not use a key for the Google Maps API service in the past which was fine up until recently when they changed their policy and began requiring it. They switched it to use Open Street Maps by default to get around this problem. Rebuilding and reinstalling dump1090-mutability should fix your issue.

**Comment by radiostationx** [comment]
Hi Joe,
No luck with re install of mutability from ./install.sh, maps do not show work.

Perhaps d1090 mutability has changed recently as I note that it no longer supports internal  web server.

[http://discussions.flightaware.com/ads-b-flight-tracking-f21/dump1090-mutability-not-showing-map-t38041.html]

I also noted the change in directory / location for gmap.html
in build/dump1090/public_html/
But the gmap.html file looks very different to previous ones I have seen, In particular line 9 where the API key insertion location is .

Is there any way to cure the map issue with google maps or how to use other map suppliers ?

Help anyone ?
Thanks

**Comment by jprochazka** [comment]
Forget about Google Maps for now it is no longer supported in the dump1090-mutability code. Yes there are many changes in the newer version of dump1090-mutability as they migrated away from Google Maps to OpenStreetMaps.

1.  After you upgraded make sure your browser cache is cleared out.
2.  Go directly to the dump1090-mutability map to see if it works. _(http://YOUR_DEVICE_IP_ADDRESS/dump1090/gmap.html)_
3. If that works try to visit the portal map. _(http://YOUR_DEVICE_IP{_ADDRESS/dump1090.php)_
