### ISSUE TITLE
Feature request: Option to set the date in 24 hour format in the admin settings

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#259]
It would be nice if there was an pre-populated option for 24 hour time in the general tab of the admin settings, 'Y-m-d H:i' seems to correspond to the MySQL DATETIME format and is what I have used the manual over-ride to set on my systems :)

**Comment by Romeo-Golf** [comment]
Although minor, does this seem reasonable given that 24 hour time is predominantly used in aviation? :)

**Comment by jdwall** [comment]
I opened PR #263 for you. Here is what it looks like.

![Img](http://i.imgur.com/4glHY3K.png)

**Comment by Romeo-Golf** [comment]
Jacob,

That looks great thanks, could it be worth adding a heading above the customer time format box to advise what its there for and perhaps a radio box to indicate when that value is used instead of the predefined options?

**Comment by jprochazka** [comment]
Thanks for the contribution @jdwall. The changes will be contained in the upcoming v2.5.0 release. I also added the suggestions made by @Romeo-Golf as well in commits 5170d4f7f48cc17cdb2b0a65ecdc5a5dc65d93ed and 3083d88e2aaaddf10a5314af560112d2a1f539a6.

![date-format-reformat](https://cloud.githubusercontent.com/assets/2583357/19819772/3689a410-9d24-11e6-9427-af757e6c2f02.png)
