### ISSUE TITLE
Add the ability to share data with FlightRadar24.com. 

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#26]
Add the ability to share data with FA24 if it fact the new client does play nice with dump1090-mutability.

**Comment by jprochazka** [comment]
Until Flightradar24 decides to develop their software to "play nice" with other feeding software this will not be addressed.

I refuse to support the installation of older versions of software in order to feed data to a site which now wishes to take sole possession of your feeder's data. This being said I will not work towards making it easier for anyone to feed such a company their data nor will I trouble shoot any issues which arise from running their software in addition to the software installed by these scripts. This may change in the future if Flightradar24 decides to change their stance when it comes to needing to control all data as if it was their own to do with only as they see fit.

**Comment by jprochazka** [comment]
I have tested out the FR24 software on my test device and apparently the latest FR24 software will work with dump1090-mutability. Look for support to be added soon.

**Comment by geofffox** [comment]
Hi Joe -

First thanks for doing all this as/with FOSS.

I have never been involved with a github project before.  I used your
script over a fresh Raspbian install.  Does this mean as this project
continues my Pi will automatically be sync'ed and brought up to date?

Thanks,
Geoff

On Thu, Feb 18, 2016 at 6:17 PM, Joe Prochazka <notifications@github.com>
wrote:

> I have tested out the FR24 software on my test device and apparently the
> latest FR24 software will work with dump1090-mutability. Look for support
> to be added soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jprochazka/adsb-receiver/issues/26#issuecomment-186016063>
> .
>



-- 


My blog:  My Permanent Record <http://www.geofffox.com>

**Comment by jprochazka** [comment]
There are no "automatic" updates. However by updating and executing the scripts you will be informed if updates are available. With a couple exceptions...

It is hard to tell when an older version of dump1090-mutability or dump978 is installed. The versions installed by the scripts are more or less from the development branch. These are updated constantly with no change to the version number.

Updating is something I will be looking into in the future. How automated it will become will be addressed at that time.

**Comment by jprochazka** [comment]
Option to install the client added in the branch named upgrade.
