### ISSUE TITLE
Feature Request, historical data handling

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#260]
Is it possible to add enhancement to simplify the export of collectd graph data from older installs to new fresh install of adsb-receiver portal.
If not, could some instructions be provided in the wiki on how to backup/export/import historical collectd graph data.

**Comment by Romeo-Golf** [comment]
yeah backup/restore functionality would be useful, both for graph data and settings.. 

perhaps the latter could be related to master config file referenced in issue #251 ?

**Comment by jdwall** [comment]
@jprochazka made a Wiki page a while back that explains where the information is stored https://github.com/jprochazka/adsb-receiver/wiki/Backup-and-Restore

**Comment by Romeo-Golf** [comment]
Jacob,

Thanks for that, I guess when using the advanced features like SQL backend it wold typically require this manual procedure..

But would the portal at least have the permissions to be able to zip up all the data from a basic install and allow the user to download for backup purposes, and ideally also upload to allow the data to be restored back onto fresh install?

**Comment by jprochazka** [comment]
Backup script added for the v2.5.0 release.

Set the correct permissions on the backup script if needed.
`chmod +x ~/adsb-receiver/bash/tools/portal_backup.sh`

Execute the backup script.
`cd ~/adsb-receiver/ && ./bash/tools/portal_backup.sh`

Added in commit 2d130cab6a0653d617d81edfebfe840b91cdbe06.
