### ISSUE TITLE
Feature Request, feeder services uninstall

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#261]
Is it possible to automate uninstall options to a similar format as installing them. 
For example, individual feeder services, perhaps this could be done via a new command ./uninstall.sh

Installing the script goes fine,and it is a great way to set up a station quickly but uninstalling anything leaves new Linux users a little uncertain. Presumably to retain functionality of the portal some of the files and directories for feeder programme etc are in different locations than is the norm.

**Comment by Romeo-Golf** [comment]
Cant comment on the ease but seems like it would be useful, perhaps the dialog which allow you to select additional feeders could take the de-selection of a particular feeder as instructions to de-install... maybe after confirming that is really what the user wants to do and if they want the data/logs associated with that feeder to also be removed?

**Comment by radiostationx** [comment]
Yeah, The script is very user friendly during the install process but not so much in the uninstall.
Experimenting Using sudo rm-f , purge commands and suchlike is bound to go wrong for most users.

**Comment by Romeo-Golf** [comment]
This has come up a few times so I will try to do some work on this on my 2.7.0 branch...

**Comment by radiostationx** [comment]
Issue with adsb exchange removal, adsb ex causing issue with 360radar.
How can I remove adsb exchange ?
Thanks

**Comment by radiostationx** [comment]
Hi Joe, any advance on how to remove adsb exchange service please ?

**Comment by jocamero** [comment]
I’m also looking for some help on how to uninstall the web portal since it interferes with PiHole.  I’d really appreciate it if someone could help. Thanks in advance!

**Comment by jprochazka** [comment]
Please refer to issue #498.
