### ISSUE TITLE
mlat-client errors to console

### ISSUE THREAD

**Issue by jcloudm** [jprochazka/adsb-receiver#264]
I just did a completely fresh install of jessie and a fresh clone of this project. I just happened to have a monitor hooked up to my raspberry pi. After a final reboot, I am getting an mlat-client error spit out to the console roughly once every 30 seconds. Here is the output:

mlat-client: error: argument --user: expected one argument

It then prints the entire mlat-client usage. It doesn't appear to be getting caught in other logs. Grepping through the clone, I think the only place mlat-client is called with --user is in adsbexchange.sh and adsbexchange-mlat_maint.sh. I think the problem is that during adsbexchange setup, I didn't set a receiver name because it said (NOT REQUIRED). It appears that one needs to be set in order to avoid this error, so if a user doesn't enter a receiver name I would argue that adsbexchange-mlat_maint.sh should not pass the user argument to mlat-client in adsbexchange-mlat_maint.sh, or should pass a default value.

**Comment by jcloudm** [comment]
Update: it appears user is required so the install script needs to assign a default value to avoid this error.

**Comment by jprochazka** [comment]
Will fix this to require that bit of data.
It was my understanding this was not a requirement but apparently it is.

**Comment by jprochazka** [comment]
Receiver name is now required.
commit 74b77e78555ad15a9dc9bda0829f15cbcaf2e3e3
