### ISSUE TITLE
Error adding a blog post.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#265]
Reported in the official forums:
https://www.adsbreceiver.net/forums/topic/blog-not-running/#post-659

> Hello friends:
> i am using xml under raspbian
> using last update version when i try to post in the blog i get:
> 2016-11-04 12:53:14: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning: Invalid argument supplied for foreach() in /var/www/html/classes/blog.class.php on line 41
> 2016-11-04 12:53:21: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice: Undefined variable: blogPosts in /var/www/html/classes/blog.class.php on line 106
> 2016-11-04 12:53:21: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning: Invalid argument supplied for foreach() in /var/www/html/classes/blog.class.php on line 106
> 2016-11-04 12:53:21: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning: simplexml_load_file(): /var/www/html/data/blogPosts.xml:9: parser error : Entity ‘ntilde’ not defined in /var/www/html/classes/blog.class.php on line 192
> 2016-11-04 12:53:21: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning: simplexml_load_file(): ahue</author><contents>&lt;p&gt;A las 13:00 del 4 de Noviembre de 2016 a&ntilde; in /var/www/html/classes/blog.class.php on line 192
> 2016-11-04 12:53:21: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning: simplexml_load_file(): ^ in /var/www/html/classes/blog.class.php on line 192
> 2016-11-04 12:53:21: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning: simplexml_load_file(): /var/www/html/data/blogPosts.xml:10: parser error : Entity ‘eacute’ not defined in /var/www/html/classes/blog.class.php on line 192
> 2016-11-04 12:53:21: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning: simplexml_load_file(): &lt;p&gt;En breve lo subir&eacute; al lado de la antena.&lt;/p&gt; in /var/www/html/classes/blog.class.php on line 192
> 2016-11-04 12:53:21: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning: simplexml_load_file(): ^ in /var/www/html/classes/blog.class.php on line 192
> 2016-11-04 12:53:21: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error: Call to a member function addChild() on boolean in /var/www/html/classes/blog.class.php on line 193

**Comment by surviving** [comment]
Getting the same error issue here....

**Comment by jprochazka** [comment]
Committed a possible fix for this issue into the 2.4.1 branch.
Commit 838d9b357ac25a1699b2d4bd8abc2da1eeeed35a

If someone having this issue would like to test this let me know how it goes.
Replace /var/www/html/classes/blog.class.php with the new one linked below.
https://raw.githubusercontent.com/jprochazka/adsb-receiver/2.4.1/build/portal/html/classes/blog.class.php
 
Guessing the issue has to do with encoding.

**Comment by jprochazka** [comment]
I have tested the changes using the special characters I figured were causing the error such as "é" and "ñ" and it would appear the error is resolved. I have merged the changes into the master branch and can be applied to your installation by running install.sh and choosing to reinstall/upgrade the portal.

Pull Request #269
