### ISSUE TITLE
Consider using etcher.io to simplify image burning instructions

### ISSUE THREAD

**Issue by karrots** [jprochazka/adsb-receiver#266]
[Etcher.io](http://etcher.io) works with zip/gz/uncompressed images and is cross platform.

**Comment by jprochazka** [comment]
Thanks for the software recommendation. Will check it out and adjust the wiki accordingly if things go well on my end.

**Comment by jprochazka** [comment]
I gave this a shot when setting up an environment to compile PhantomJS and honestly I ran into issues using it trying to overwrite an SD card which had a image of Raspbian already burnt to it. Etcher.io reported that the SD card did not have enough space available while Win32DiskImager did what it always does writes the image to the selected SD card without a complaint.

I like the fact it is cross platform and would have simplified the wiki instructions but...

However thanks for the software recommendation I will keep an eye on the project and if they fix this issue will be more than happy to revisit this option.

**Comment by karrots** [comment]
Looks like your hitting this issue.

https://github.com/resin-io/etcher/issues/685

**Comment by jprochazka** [comment]
Actually I cannot even get that far. At the select drive option the drive is marked as too small for image and will not let me select the drive.
![etch-error](https://cloud.githubusercontent.com/assets/2583357/20782182/60917a74-b757-11e6-85e2-3dcfcda61016.png)

**Comment by karrots** [comment]
huh odd it looks as though the SD card isn't inserted into the reader.
Submit a issue with them see if they can work it out.

**Comment by Psysquirrel** [comment]
I've just come across the same problem. I can move files to the drive in Windows Explorer but Etcher sees it as having no space.

Did anyone find a solution to this problem?
