### ISSUE TITLE
dump1090-mutability fails to startup fully

### ISSUE THREAD

**Issue by Caboosey** [jprochazka/adsb-receiver#268]
I did several fresh installs using the v2.4.0 dump1090-mutability image on Raspberry Pi 3. dump1090-mutability would run, but fail to load the config file and thus never listen on any port or any IP. 

My Setup:
Device/system: Raspberry Pi 3
Wait for Network to boot: Enabled
Image/Distro: adsbreceiver image v2.4.0 dump1090-mutability
Static IP: Configured and enabled.
Packages installed: dump1090-mutability, dump978, ADS-B Portal, Flightradar24
Number of Dongles: 2
dump1090 device assignment: 0
dump978 device assignment: 1
dump1090 Listen on any IP: Enabled

RTL Test Output:
```
Found 2 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000004
  1:  Realtek, RTL2838UHIDIR, SN: 00000005
```

I had to constantly restart the dump1090-mutability service after every reboot to make it work.

I discovered an issue at: /etc/init.d/dump1090-mutability

**Steps to fix:**
1. Issue following command:
`sudo nano /etc/init.d/dump1090-mutability`
2. Change lines from:
```
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
```
Change lines to:
```
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
```
3. Save and Exit.
4. Reboot:
`sudo reboot`
5. Verify dump1090-mutability is listening on network:
`sudo netstat --program --protocol=inet --tcp --wide --all`

**Comment by jprochazka** [comment]
I personally have not ran into this issue on my receiver which is running all available installation options at this time along with two dongles assigned the same as you posted. The scripts supplied by this project do not deal with the dump1090-mutability init script except when adding the --measure-noise argument.

Being that the dump1090-mutability setup script is not intended to modify things other than arguments and settings I feel this is better addressed by the maintainer of dump1090. I leave fixes specifically pertaining to each application up to the maintainers of said application. For me to begin modifying things may end up causing even more troubles down the road.

However you may wish to post this on @mutability's dump-1090 repository issue tracker maybe?
