### ISSUE TITLE
Option to build and install beast-splitter.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#277]
Add an option to "Extras" offering users the ability to builds and install beast-splitter for use by those running Mode-S Beast receivers.

**Comment by Romeo-Golf** [comment]
Interesting peice of kit, though not cheap!

http://www.modesbeast.com/scope.html

https://shop.jetvision.de/epages/64807909.sf/de_DE/?ObjectPath=/Shops/64807909/Products/41000

**Comment by jprochazka** [comment]
> Interesting peice of kit, though not cheap!

That's for sure...
Anyways added as an "extra" and should be available in v2.6.0.

commit 14328bf98b054241b3106be1123242c7c7c7180e
