### ISSUE TITLE
Links missing in dump1090.php to graphs.php on upgrade and new install of 2.5.0 

### ISSUE THREAD

**Issue by stevenflang** [jprochazka/adsb-receiver#278]
When upgrading from 2.4 using install script or installing new 2.5 image links to graph are missing from dump1090.php. blog link works though ! system / maps and / links -- link do not work,

**Comment by stevenflang** [comment]
Adding additional info -
Looks like the pull down menu is not working but behavior is different for Chrome browser vs Firefox.

**Comment by Romeo-Golf** [comment]
works for me on both chrome and firefox...

**Comment by stevenflang** [comment]
Thank you for the sanity check !

I am unable to explain what happened to the upgraded pi but when I booted it back up it's working now. 
I may have carried over the problem from the upgraded 2.5 to the new 2.5 image by copying /var/www/html/data directory over to the new image but I also included settings.xml which I read should not be copied. I should have read the directions for copying this initially !

Thank you and closing issue ..

**Comment by jprochazka** [comment]
There was a couple reports on this on the forum as well. If anyone else encounters this issue please clear your browsers cache. The Twitter Bootstrap library used by the default template was updated in v2.5.0. Not sure if that is what is causing the issue or something else that has been cached is doing so.
