### ISSUE TITLE
Feature request: add UKHAB lora-gateway support as an Extra

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#279]
Having obtained a GPS hat which also has a LoRa decoder Im planning to see if I can add support for installation the lora-gateway as an extra feature...

Thankfully they are also on github so should be able to benefit from any tidyup work such as installing wiringpi via a package rather than building from source, although the nurses based UI may also present some challenges...

https://github.com/PiInTheSky/lora-gateway

http://www.daveakerman.com/?p=1719

https://www.rs-online.com/designspark/building-a-raspberry-pi-powered-lorawan-gateway

**Comment by Romeo-Golf** [comment]
So having done some more reading its worth clarfiying a few things:

This particular 'lora-gateway' is provided by the High Altitude Ballooning community who have started using the LoRa PHY to replace various means of transmitting data back to the ground, including telemetry and images :)

From what I can tell this does not use the LoRaWan protocols on top of the LoRa PHY, but it appears to be based on APRS so may well have a lot in common with the RTLSDR-OGN code from the Open Glider Network folks..

Additionally since at present this requires a dedicated LoRa radio such as the one linked below, this probably belongs in the Extras category... but there are some other projects working on decoding the LoRa that may allow reception of this data using a standard USB SDR at some point :)

http://wiki.dragino.com/index.php?title=Lora/GPS_HAT

**Comment by Romeo-Golf** [comment]
FYI the install for this on my 2.7.0 branch is now 'working' at least as far as i can get without a correctly wired LoRa module, which I hope to resolve with the HAT Hack3r board :)

In the mean time I just wanted to confirm that as a combined decoder and feeder, which at present requires a dedicated LoRa radio, this would belong in extras?

**Comment by jprochazka** [comment]
Just not enough demand. Once demand is great enough I might be interested in adding GPS support.
