### ISSUE TITLE
Add support for Orange Pi devices.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#28]
It was brought to my attention that there appears to be issues with the scripts when running them on an Orange Pi device running Debian Jessie using the kernel created by @loboris. Once I am able to obtain an Orange Pi I will look into possibly supporting the device depending on how far down the rabbit hole it takes me.

https://github.com/loboris/OrangePI-Kernel

**Comment by dschaper** [comment]
I'll give this a run on an OPi2, running minimal Ubuntu Wily. It's a fresh install with @loboris kernel and the thermal fix.

**Comment by dschaper** [comment]
There are some bizarre USB issues going on, but they don't seem to be related to the script. The only issue I've found so far is the lack of python 2 or 3 with the default install. I'll try walking the script manually and see where the USB issues come in...

**Comment by dschaper** [comment]
Installing the rtl-sdr package seems to resolve the USB issues.

**Comment by jprochazka** [comment]
Added the package rtl-sdr as a required package when installing dump1090-mutability in commit 19ddc937bb6803256bd47ce6307e3fa445489dd7. I am still about 2 weeks out from receiving an Orange Pi for testing. Going to leave this issue open until then unless I here reports that this change to the dump1090-mutability.sh file fixed anything.

**Comment by dschaper** [comment]
Looks like there is no cron support in the default images, solved with an install of systemd-cron.

**Comment by jprochazka** [comment]
Added cron as a required package as well.

**Comment by dschaper** [comment]
Okay, had SDCard throw a shoe on me, so I'm starting from scratch. Here's a walkthrough. OPi2 with a 4GB SDCard. 

1. Download and install (via Rufus) Ubuntu_vivid_mini_img.xz from Google Drive.
2. Download and copy over contents of scriptbin_kernel_tar.gz to the boot partition.
3. Copy the correct script.bin and uImage for my OPi2.
4. Attach USB TTL Serial cable for setup.
5. Log in to OrangePi, expand filesystem and reboot.
6. Add orangepi to /etc/hosts (Annoyance Fix)

* Run nmcli to bring up wireless networking (OPi2 has built in wifi)

7. Install and run update_kernel.sh to grab latest kernel (Linux OrangePI 3.4.39-01-lobo #1 SMP PREEMPT Sun Oct 25 14:46:41 CET 2015 armv7l armv7l armv7l GNU/Linux)
8. Install and run thermal fix from http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=785
9. Install OPi Monitor (RPiMonitor Mod) from http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=811&extra=page%3D1
10. Install via apt-get fake-hwclock, since the OPi doesn't set the proper time/date until late in the boot process, often services are started with the default 1-1-1970 system date and that can cause issues. 

* Install adsb-feeder:

1. Follow instructions on the homepage For New Installations:
Error: /var/lib/dpkg/info/dump1090-mutability.postinst: line 115: /etc/cron.d/dump1090-mutability: No such file or directory
2. run 'sudo mkdir /etc/cron.d/` in second terminal window while script is running. (Install byobu for tmux support)
3. Reboot

No Dump1090 graphs, and a 404 Error when trying to access the dump1090-map. Also getting the invalid certificate error in /tmp/piaware.out.

**Comment by dschaper** [comment]
Looks like the lack of /etc/cron.d/ throws off the installation of dump1090-mutability, I wasn't even given the option to enter my HeyWhatsThat information.

**Comment by dschaper** [comment]
12/30/2015 07:21:18 ****************************************************
12/30/2015 07:21:18 piaware version 2.1-5 is running, process ID 568
12/30/2015 07:21:18 your system info is: Linux OrangePI 3.4.39-01-lobo #1 SMP PREEMPT Sun Oct 25 14:46:41 CET 2015 armv7l armv7l armv7l GNU/Linux
12/30/2015 07:21:18 Connecting to FlightAware adept server at piaware.flightaware.com/1200
12/30/2015 07:21:18 ADS-B data program 'dump1090-mutabi' is listening on port 30005, so far so good
12/30/2015 07:21:18 Starting faup1090: /usr/lib/piaware/helpers/faup1090 --net-bo-ipaddr localhost --net-bo-port 30005 --stdout
12/30/2015 07:21:18 Started faup1090 (pid 592) to connect to dump1090-mutabi
12/30/2015 07:21:18 Connection with adept server at piaware.flightaware.com/1200 established
12/30/2015 07:21:18 TLS verify failed: self signed certificate in certificate chain
12/30/2015 07:21:18 Failing certificate:
12/30/2015 07:21:18   sha1_hash: B69ABB0BF41433F4E27434BF6628CE1EA1CAA704
12/30/2015 07:21:18   subject: CN=FlightAware Root,OU=Operations,O=FlightAware LLC,L=Houston,ST=TX,C=US
12/30/2015 07:21:18   issuer: CN=FlightAware Root,OU=Operations,O=FlightAware LLC,L=Houston,ST=TX,C=US
12/30/2015 07:21:18   notBefore: Dec  9 16:50:04 2015 GMT
12/30/2015 07:21:18   notAfter: Dec  4 16:50:04 2035 GMT
12/30/2015 07:21:18   serial: A9FE756D9E6B94B4
12/30/2015 07:21:18 TLS alert: unknown CA
12/30/2015 07:21:18 TLS error: certificate verify failed
12/30/2015 07:21:18 TLS handshake with adept server at piaware.flightaware.com/1200 failed: handshake failed: certificate verify failed
12/30/2015 07:21:18 reconnecting in 113 seconds...
12/30/2015 07:21:19 piaware received a message from dump1090-mutabi!
12/30/2015 07:21:48 24 msgs recv'd from dump1090-mutabi; 0 msgs sent to FlightAware

**Comment by jprochazka** [comment]
Wonder if copying the FlightAware cert to /etc/ssl/certs/ will fix the certificate error...

    sudo cp /usr/lib/fa_adept_packages/ca/flightaware-combined.cert.pem /etc/ssl/certs/
    sudo update-ca-certificates 

I added the cron package as a requirement to install dump1090-mutability.

Once these items are hashed out I can add the additional software you mentioned that is needed for an Orange Pi to run properly. At that time I am going to have to figure out a way to detect an Orange Pi over say a Raspberry Pi so that extra software is not installed on RPi devices.

**Comment by dschaper** [comment]
This thing is an SDCard monster... Trying again with the "install_to_usb" script... Will update as I find things...

**Comment by dschaper** [comment]
Installing cron package when systemd-cron is already installed causes core dump:

Checking if the package cron is installed... [NOT INSTALLED]
Installing the package cron...

Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  logrotate checksecurity exim4 postfix mail-transport-agent
The following packages will be REMOVED:
  systemd-cron
The following NEW packages will be installed:
  cron
0 upgraded, 1 newly installed, 1 to remove and 0 not upgraded.
Need to get 65.6 kB of archives.
After this operation, 165 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports/ vivid/main cron armhf 3.0pl1-127ubuntu1 [65.6 kB]
Fetched 65.6 kB in 0s (69.9 kB/s)
(Reading database ... 26925 files and directories currently installed.)
Removing systemd-cron (1.3.1+ds1-2) ...

Broadcast message from systemd-journald@OrangePI (Wed 2015-12-30 19:58:04 PST):.60 4x1.0GHz 1003M9% 2015-12-30 19:58:04

systemd[1]: Caught <ABRT>, dumped core as pid 16625.


Broadcast message from systemd-journald@OrangePI (Wed 2015-12-30 19:58:04 PST):

systemd[1]: Freezing execution.

Failed to execute operation: Connection reset by peer
Failed to execute operation: Connection timed out
Processing triggers for man-db (2.7.0.2-5) ...
Selecting previously unselected package cron.
(Reading database ... 26899 files and directories currently installed.)
Preparing to unpack .../cron_3.0pl1-127ubuntu1_armhf.deb ...
Unpacking cron (3.0pl1-127ubuntu1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (219-7ubuntu6) ...
Failed to execute operation: Activation of org.freedesktop.systemd1 timed out
dpkg: error processing package systemd (--unpack):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)

Checking if the package cron is installed... [NOT INSTALLED]
Installing the package cron...

Reading package lists... Done
Building dependency tree
Reading state information... Done
cron is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up systemd (219-7ubuntu6) ...
/var/lib/dpkg/info/systemd.postinst: 133: /var/lib/dpkg/info/systemd.postinst: cannot open /run/systemd/was-enabled: No such file

Failed to try-restart systemd-logind.service: Activation of org.freedesktop.systemd1 timed out
Failed to try-restart systemd-networkd.service: Activation of org.freedesktop.systemd1 timed out
Failed to try-restart systemd-resolved.service: Connection timed out

**Comment by dschaper** [comment]
sudo cp /usr/lib/fa_adept_packages/ca/flightaware-combined.cert.pem /etc/ssl/certs/
    sudo update-ca-certificates

Doesn't seem to help with the certificate issue.

**Comment by dschaper** [comment]
Okay, solved the CA issue, it's noted in the commit https://github.com/flightaware/piaware/commit/6a883f428912357c252654cb811499e58db87d3a

   sudo rm -r /usr/lib/fa_adept_packages/ca

Copy the two certificate files from the commit

    sudo c_rehash /usr/lib/fa_adept_packages/ca

**Comment by jprochazka** [comment]
Will look into making a temporary workaround until @mutability tags the fix in a new release outside the master branch. Had issues in the past with PiAwares master branch not being "stable".

**Comment by mutability** [comment]
You can just point at that hash if you want, a tag is just a nice name for a particular point in the history anyway.

**Comment by mutability** [comment]
Here's a tag to make it simpler: https://github.com/flightaware/piaware_builder/releases/tag/v2.1-5-jessie

(but you can just use the hash in the future if you need to pin things to a specific commit. just check that sensible-build contains commit hashes or tags rather than e.g. "origin/master")

**Comment by dschaper** [comment]
Fixed in #47

**Comment by jprochazka** [comment]
Thanks for the info @mutability and @dschaper thanks for the pul request, https://github.com/jprochazka/adsb-feeder/pull/47, addressing this.

**Comment by dschaper** [comment]
Do you know when you're getting your Orange? The dump978 testing was all done on an OPi.

**Comment by jprochazka** [comment]
Been about a month now since ordering it so hoping any day now. If it was like the last amp I bought from China may still be a couple weeks out... Shipping times from China seems to be hit or miss for me.

**Comment by dschaper** [comment]
I've been really lucky with shipments coming in. Two weeks tops so far. Hopefully we have most of the issues ironed out by the time you get yours. Which model did you end up getting?

**Comment by jprochazka** [comment]
One of the Orange Pi PC's didn't get the Plus yet going to see how the cheaper one works out first.

**Comment by jprochazka** [comment]
My OPi is finally in country. This weekend I don't see myself being able to mess with it all that much but the weekend after I will try to dedicate a chunk of time to this.

**Comment by jprochazka** [comment]
Installation on Orange Pi devices using Ubuntu Vivid Mate appear to work out of the box.
http://discussions.flightaware.com/post188330.html#p188330

**Comment by jprochazka** [comment]
Hardware too obscure and after personal experience support and a solid operating system does not exist. Time trying to support this hardware can be better spent adding features.

**Comment by dschaper** [comment]
I concur!
