### ISSUE TITLE
Updated Plane Finder client 3.5.461

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#281]
Latest Plane Finder ADS-B feed client version is 3.5.461

https://planefinder.net/sharing/client_changelog

- Brand new map view including aircraft labels, photographs and additional metadata lookup
- Added colour-coded flightpaths to represent altitude
- Added the ability to mouse over flightpaths to view their speed and altitude at that any given point in time
- Improved Data View layout. Added the option to filter by additional fields
- Added the ability to set a Google Maps API key for users wishing to share their client webpages publicly (this is optional and not necessary when accessing the client locally)
- Rewritten HTTP parser to handle browser communication more reliably
- Various other bug fixes and improvements

I have updated the version in bash/variables.sh on my 2.6.0 branch so can confirm that the new client not only installs as expected, but looks nicer than the previous version :)

**Comment by jprochazka** [comment]
THanks. I updated the Planefinder ADS-B Client version for ARM in the master branch as well. The i386 package is still at the older version at this time.

Changes have been submitted to the master branch so those running 2.5.0 will have the option to upgrade their client by running install.sh and choosing to do so.
