### ISSUE TITLE
Add support for more than 4 USB RTLSDR tuners

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#284]
> The issue is that the Kernel limits the maximum size of all buffers that libusb can allocate to 16MB by default. In order to disable the limit, you have to run the following command as root:

echo 0 > /sys/module/usbcore/parameters/usbfs_memory_mb

https://github.com/steve-m/librtlsdr/issues/34

**Comment by jprochazka** [comment]
Too little value add to be added to the project. I have yet to see anyone here who runs more than four tunes on their device.
