### ISSUE TITLE
Use Kalibrate to estimate RTLSDR dongle error rate

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#291]
As part of the RTLSDR-OGN (#129) and possible Acardeco (#288) support I have some simple code to install Kalibrate and use the GSM850/900 frequencies to calibrate the RTL-SDR devices...

Although running the scans takes about 8 minutes, installing from github and compiling is fairly quick so I was wondering if its worth including as part of the default install so this could be available to calibrate tuners used by other decoders?

FYI I have been using the steve-m fork which has the ARM fixes needed to run this on Raspberry Pi, but happy to consider one of the many other forks if there are features work having:  

https://github.com/steve-m/kalibrate-rtl/

**Comment by Romeo-Golf** [comment]
So having thought about this being useful to allow for calibration of a dongle once selected by a decoder, would it be worth considering this as either a 'precursor' or 'prerequisite' whereby the user is presented with the option to install ahead of selecting which decoders/feeders/extras they wish to install?

**Comment by jprochazka** [comment]
At this time this is outside the scope of the project. Anyone wishing to get this in depth into their setup I would think would be capable of running said software and adjusting things accordingly.
