### ISSUE TITLE
Only update from github if local branch is behind remote branch

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#292]
For some of the RTLSDR-OGN (#129), HAB LoRa-Gateway (#279) and Acarsdeco (#288) code which is hosted on github I have used the following to only pull and recompile if the local branch is behind the remote branch:

> ACTION=$(git remote update)
>  if [[ \`git status -uno | grep -c "is behind"\` -gt 0 ]] ; then
> \# Local branch is behind remote so update.
> ACTION=$(git pull)
> \# And remove previous binaries.
> ACTION=$(sudo make clean)
> DO_INSTALL_FROM_GIT="true"
> fi

Is this worth re-using elsewhere such as only recompiling dump1090-mutablity if there have been changes on github?

**Comment by jprochazka** [comment]
This would be an unnecessary step. 
If you pull from an already up to date repository it tells you you are up to date.
