### ISSUE TITLE
Forum user reported "constant error in syslog"

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#294]
From https://www.adsbreceiver.net/forums/topic/noticed-constant-error-in-syslog/ :

I was looking through my /var/log/syslog file and noticed a re-occuring error in /adsb-receiver/build/portal/maintenance.py…

Jan  7 15:14:25 pine64 rc.local[872]: File "/adsb-receiver/build/portal/python/maintenance.py", line 153
Jan  7 15:14:25 pine64 rc.local[872]: cursor.execute("DELETE FROM adsb_positions WHERE time < ?", params)
Jan  7 15:14:25 pine64 rc.local[872]: ^
Jan  7 15:14:25 pine64 rc.local[872]: IndentationError: unexpected indent
Jan  7 15:14:55 pine64 rc.local[872]: File "/adsb-receiver/build/portal/python/maintenance.py", line 153
Jan  7 15:14:55 pine64 rc.local[872]: cursor.execute("DELETE FROM adsb_positions WHERE time < ?", params)
Jan  7 15:14:55 pine64 rc.local[872]: ^
Jan  7 15:14:55 pine64 rc.local[872]: IndentationError: unexpected indent
Below is lines 145-155 of /adsb-receiver/build/portal/python/maintenance.py… is the fix just as simple as deleting the space in front of “cursor.execute”?

` if purge_positions == true:
# MySQL
if config[“database”][“type”] == “mysql”:
cursor.execute(“DELETE FROM adsb_positions WHERE time < %s”, purge_date)

#SQLite
if config[“database”][“type”] == “sqlite”:
params = (purge_date,)
cursor.execute(“DELETE FROM adsb_positions WHERE time < ?”, params)

## Close the database connection.`

**Comment by jprochazka** [comment]
Fix when code was brought over from Romeo-Golf's 2.6.0 branch.
