### ISSUE TITLE
Using PiDrive & Berryboot

### ISSUE THREAD

**Issue by agoldcheidt** [jprochazka/adsb-receiver#296]
I'm running this OS image under Berryboot and I receive this error: "is not a SD card" and does not boot. I'm also using the PiDrive.

**Comment by Romeo-Golf** [comment]
Hi,

I believe the Berryboot images were contributed by a user on the forums:

https://www.adsbreceiver.net/forums/topic/with-full-jessie-does-not-work/

Would you mind starting a new thread in the support forum here, if possible details what steps you have taken prior to experiencing the error:

https://www.adsbreceiver.net/forums/forum/support/

Thanks.

**Comment by jprochazka** [comment]
My PiDrive setups do not use BerryBoot. It may take a few more commands to setup the way I do but when your done the OS does not know the difference or need extra software to run. If you are not afraid of a few commands and got a few minutes to get things set up you might want to check out my guide on doing so.

https://www.swiftbyte.com/articles/raspberry-pi/running-raspbian-from-a-usb-hard-drive
