### ISSUE TITLE
Low priority: Graph of dump1090 gain

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#297]
Having recently been tweaking my gain values manually I figured it could be worth graphing this somehow...

Even if initially just the configured gain value, if set, to assist with keeping track of when this was manually changed.

But if the live value can be obtained from dump1090, especially with the default auto gain setting, that would be even better :)

**Comment by jprochazka** [comment]
In its current state dump1090-tools does not offer such information. To add support for this would be beyond the scope of this project at this time. If someone were to submit a pull request adding this functionality to the dump1090-tools project then adding this information to the graphs would be trivial.
