### ISSUE TITLE
No system CPU graph available

### ISSUE THREAD

**Issue by mgunther68** [jprochazka/adsb-receiver#30]
I do not get the system CPU graph on my Pi installation . It is probably an issue with the collectd tool. I do not have this directory:
/var/lib/collectd/rrd/localhost/aggregation-cpu-average/

Error seen during make-collectd-graphs.sh:
ERROR: opening '/var/lib/collectd/rrd/localhost/aggregation-cpu-average/cpu-idle.rrd': No such file or directory

Also:pi@raspberrypi ~/git/adsb-feeder $ sudo /etc/init.d/collectd restart
[....] Restarting statistics collection and monitoring daemon: collectdCould not find plugin aggregation.
Could not find plugin aggregation.
. ok

**Comment by mgunther68** [comment]
I think this is due to my collectd version: Version: 5.1.0-3
The aggregation plugin was introduced in version 5.2.

According to Debian packages information:
wheezy has: Package: collectd (5.1.0-3)
jessie has: Package: collectd (5.4.1-6)

Since I'm on wheezy, I guess that explains why I don't have the aggregation package and therefore no system CPU graph.

**Comment by jprochazka** [comment]
Graphs are something I am looking to modify here shortly. Seen some very nice looking graphs and would like to add a slight touch of color and maybe some gradients and defiantly rearrange the textual information presented at the bottom. When I do this I will look into making them more "legacy friendly". I have seen some nice CPU graphs not utilizing the aggregation plugin only the CPU plugin which is available for Wheezy.

**Comment by mgunther68** [comment]
Sounds good, thank you!

**Comment by jprochazka** [comment]
I no longer see the point in supporting Wheezy based releases due to the age.
