### ISSUE TITLE
2.7.0 (and beyond) - Tracking any/all feature requests

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#301]
I have created a 2.7.0 branch which I'm thus far using to work on the following new features:

- #288 Add ACARDS support
- #279 Add HAB LoRa Gateway using dedicate LoRa Radio
- #223 + #249 Add GPS with timing data fed to NTP
- #248 Generic Feeder for BEAST/MLAT data
- #291 Use Kalibrate to calibrate tuners

Please feel free to suggest additional features or functionality to be considered by Joe for inclusion in this release; however please ensure to raise a separate issue thread and link to it rather than making suggestions directly :)

**Comment by jprochazka** [comment]
Going to close this one out so your fork is not confused with this project being this one will be going in a totally different direction than it currently is with the upcoming v3.x release. Please feel free to keep your fork running! I love the fact someone has shown so much interest in the project.
