### ISSUE TITLE
PiAware client upgrade to version 3.5

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#305]
https://www.adsbreceiver.net/forums/topic/piaware-3-1/#post-984

It looks like existing installs should update next time apt-get upgrade is run; however I assume the version number needs to be increased in variables.sh so have raised this to give an issue number to commit against ;)

**Comment by Romeo-Golf** [comment]
PiAware now at [version 3.5](http://flightaware.com/adsb/piaware/files/packages/pool/piaware/p/piaware-support/piaware-repository_3.5.0_all.deb), changes seem to be fairly [minor](https://github.com/flightaware/piaware/commits/master) so I will update on my [2.6.0](https://github.com/Romeo-Golf/adsb-receiver/tree/2.6.0) branch and leave for a  couple of days before doing the same on my [2.5.1](https://github.com/Romeo-Golf/adsb-receiver/tree/2.5.1) branch.

**Comment by jprochazka** [comment]
Master branch is now updated to install the PiAware v3.5.1 tag.
commit b7366a8760f8784d17405e7811d02212e2985cc3
