### ISSUE TITLE
remove the piaware username/password prompt

### ISSUE THREAD

**Issue by mutability** [jprochazka/adsb-receiver#306]
We're slowly trying to get away from putting FA username/password on the piaware client side.
It's still there as a legacy thing but it is a bit of a security hole and we'd rather not have people configure it.

Can you remove the prompt for a FA username/password from the setup scripts?

**Comment by mutability** [comment]
(somewhat related, as of 3.3 you can get a URL from /run/piaware/status.json "site_url", which will point to the user's stats page, so you don't need to know the username ahead of time)

**Comment by Romeo-Golf** [comment]
Sure, I will try to take a look at this over the weekend and thank for highlighting the site_url value :)

**Comment by Romeo-Golf** [comment]
So I reviewed the install code and it's a fairly minimal change so I should be able to do it later this week, although it would be in my 2.6.0 branch which due to the volume of changes may not make it into Joe's release.

I agree that moving away from having credentials stored locally seems wise, but suspect there may still be some use cases such as being configured for deployment at remote location...

So I just wanted to check if you would see my issues with retaining the option to configure the username/password, but with the default option being to skip and the text updated to highlight that this is not recommended due to security considerations etc? :)

**Comment by mutability** [comment]
I'd like the default to not even mention it ideally.

You can still configure it if needed via piaware-config.

**Comment by Romeo-Golf** [comment]
Part of the ethos of this project is to assist users in configuring multiple feeders so would rather avoid having to suggest using other tools to be able to have a comparable install to what the scripts do today...

Does the 'Claim My Pi' function allow users to track down their receiver without say knowing the IP/MAC address, or is there any other means to identify it remotely if the user is not given the option to configure the user/pass during the initial setup?

**Comment by mutability** [comment]
The only case you ever need to set a username/password is an install where you cannot reach the FA website from the same IP address as the feeder. That case will, itself, go away in the future. It is not a common case.

If you put a prompt in for username/password (even if it's surrounded by warnings) in the default flow, users _will_ fill that in when it's not needed, which is a security problem that I really don't need.

If you are going to retain the ability to configure the username/password then please put it somewhere that is not in the default install flow.

**Comment by Romeo-Golf** [comment]
Thanks for the update and just to confirm that I understand correctly there is presently a requirement for the user to be able to access the FlightAware website from the same public IP as the receiver is sending its data in order for it to be available to be 'claimed' by the user, but this may be addressed in future?

**Comment by mutability** [comment]
The automated claim process requires that you visit the claim webpage from the same external IP as the Pi is connecting from. Once you've done that once and the receiver is claimed, there's no further requirement.

**Comment by Romeo-Golf** [comment]
Thanks for confirming and as it seems the 'claim my pi' functionality should work in most, but not all, use cases I have proposed the following wording in my changes against the 2.6.0 branch:

> whiptail --backtitle "${RECEIVER_PROJECT_TITLE}" --title "Claim Your PiAware Device" --yesno 
> 
> Although it is possible to configure your FlightAware credentials locally, these will be stored in plaintext which represents a security risk that should be avoided.
> 
> FlightAware recommends claiming your feeder online using the following page:
> 
> http://flightaware.com/adsb/piaware/claim
> 
> Will you be able to access the FlightAware website from the same public IP address as the feeder will be sending data from?

If the user answers Yes then the next dialog confirms they will need to claim their pi and repeats the address, whereas answering No leads to the existing username/password configuration dialog.

So although not what was requested, does this seem like a reasonable interim step to decrease the number of users who have credentials stored locally while retaining the ability to do so for the corner cases where the requirement to access the  webpage from the same public IP?

**Comment by mutability** [comment]
Sure, that is an improvement over the status quo.

**Comment by jprochazka** [comment]
Sorry for the delay getting on this request but I see no problem removing this step and displaying instructions on how to claim their receiver using the website. I have this as next on my "machine gun catch up list" and should have it merged into the master branch within the next day.

**Comment by jprochazka** [comment]
Actually an easy fix just moved the contents of an else statement outside the if. Users should now be instructed to visit https://flightaware.com/adsb/piaware/claim to claim their device.

Commit: ceed37718299bae4e126f2b8e0c8269887574672
