### ISSUE TITLE
Services Not Starting At Startup

### ISSUE THREAD

**Issue by ForestFeather** [jprochazka/adsb-receiver#307]
So run into an interesting issue on the CHIP - at restart neither the dump1090-mutability service will start, nor will the piaware service, and both require manually starting.  Here's what I've seen:

Running 'sudo service dump1090-mutability/piaware start' does the trick and they start up fine.

Logs show two problems:

In piaware.log we get "software failed to determine MAC address of the device.  cannot proceed without it."
In the dump1090-mutability log we get: 
```Found 1 device(s):
0: unable to read device details
usb_open error -3
Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules
Error opening the RTLSDR device: Permission denied```

I have confirmed that the rtl-sdr.rules is installed along with the 0666 permissions.  Hence my confusion.  Any thoughts on this?

**Comment by Romeo-Golf** [comment]
Looks like we still have some work to do before we could consider the C.H.I.P to be supported, but given that it has a similar CPU to the Pi but at a lower cost I do think its worth pursuing...

The MAC issue could be related to some posts I found about the MAC being generated randomly on startup, but just to check can you confirm if you are using the onboard wifi or a usb network adaptor?

I am also unsure why the usb tuner would not be accessible to dump1090 on startup, but would then work when restarted manually; however mention of the blacklist did make me think of the issue reported in #296 whereby the blacklist functionality did not work as expected outside of Raspbian or stock Debian installs..

Can you try rebooting and attempting to start dump1090 manually with the below command as soon after it boots back up as possible?

`/usr/bin/dump1090-mutability --measure-noise --net --ppm 0 --fix --max-range 300 --net-ri-port 30001 --net-ro-port 30002 --net-bi-port 30004,30104 --net-bo-port 30005 --net-sbs-port 30003 --net-heartbeat 60 --net-ro-size 500 --net-ro-interval 1 --net-buffer 2 --net-bind-address 127.0.0.1 --stats-every 3600 --write-json /run/dump1090-mutability --write-json-every 1 --json-location-accuracy 1`

Thanks

**Comment by ForestFeather** [comment]
I can confirm that it does use the wlan0 for piaware - and the MAC has been steady, though it would be as it's a dedicated chip.  I believe it's only the USB-eth0 that has the randomly generated MAC due to the nature of eth-over-USB.  So the MAC is steady, and if it weren't as I understand it I'd have flightaware's website gawking angrily at me every time I restarted, which it hasn't at this time.

I started that command as soon as possible (being aware I'm unable to network in until I'm on ssh) but it started up with that command no problem, and received stats.  I'm looking further into the logs to see if there's anything in them (dmesg, syslog, etc) about service failure, but if you've any other ideas or directions I'm all ears - and sadly googling for 'linux services fail at startup' returns a million and one 'here's how to set the default startup values for a script' rather than anything directly useful.

**Comment by ForestFeather** [comment]
Hmm.  It appears in the logs that it's attempting to start up the dump1090 and piaware services before A) dbus has been fully activated and B) NetworkManager has booted and enabled the network interface.  (Case in point my log was littered with attempts of ntpd trying to ping the ntp servers for time and failing for about 10 seconds before the network was spun up.)  It seems that we may need to delay them until after those services are completed.

**Comment by Romeo-Golf** [comment]
Hmm, looks like for whatever reason dump1090 is trying to start before the network is up.. which does seem similar to issue #268 ...

Can you try editing /etc/init.d/dump1090-mutability to add $network to the Required-Start: line, then try rebooting?

**Comment by Romeo-Golf** [comment]
https://wiki.debian.org/LSBInitScripts

> Is it possible to start a given init script as late as possible?
>
> yes, if you really want to do so, insserv recognises the $all virtual facility name such that the script will be executed at the end.

**Comment by ForestFeather** [comment]
Okay, so here's the update - I set '$network' in dump1090-mutability's init file.  That got him working, but still no dice for piaware.  It already had several services including network.  But I did switch it to have '$all' instead, and after four reboots it's started up every time.  Seems like that's the fix there.

**Comment by Romeo-Golf** [comment]
FYI the change to add $network to the dump1090 init script has now been merged as commit https://github.com/mutability/dump1090/commit/bffaa6dd3989f78e3ba4b032a68e497e3019d49d  

However this will result in users being prompted by dpkg to confirm the following change to the dump1090 init script:

```

  Entering the ADS-B Receiver Project build directory...
  Installing the dump1090-mutability package...

(Reading database ... 47538 files and directories currently installed.)
Preparing to unpack dump1090-mutability_1.15~dev_armhf.deb ...
Unpacking dump1090-mutability (1.15~dev) over (1.15~dev) ...
Setting up dump1090-mutability (1.15~dev) ...

Configuration file '/etc/init.d/dump1090-mutability'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** dump1090-mutability (Y/I/N/O/D/Z) [default=N] ? D

--- /etc/init.d/dump1090-mutability     2017-02-07 20:34:05.376348667 +0000
+++ /etc/init.d/dump1090-mutability.dpkg-new    2017-02-09 17:31:26.000000000 +0000
@@ -1,8 +1,8 @@
 #!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          dump1090-mutability
-# Required-Start:    $remote_fs
-# Required-Stop:     $remote_fs
+# Required-Start:    $remote_fs $network
+# Required-Stop:     $remote_fs $network
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: dump1090 daemon (mutability variant)

```

**Comment by jprochazka** [comment]
I have a chip on hand if you can fill me in on what OS and version you are running and now that I am back I will try it out and see if I run into any issues I can fix.

**Comment by jprochazka** [comment]
Due to the fact there are so many RPi like devices n the market it is nearly impossible to support each and every one. Please note that currently supported devices can be seen at https://www.adsbreceiver.net.

I ask that those needing support for unsupported deevices do so in the project forums located at https://adsb.discourse.group/. Others as well as myself will be more than happy to help you out there.
