### ISSUE TITLE
Beta testing...

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#308]
With a number of almost-working features stacking up in my 2.7.0 branch i was thinking about how best to make these available for users who are willing to help with testing these ahead of completion and full integration into the project.

So I envisaged having a bash/betas folder and similar structure to the feeders/extras whereby the user could be presented with a list of beta features which could be installed, ideally without any significant changes to the base system :)

This would seem particularly relevant to mostly 'stand alone' features such as an ACARS decoder where a basic scripted install may be useful to some users ahead of any future work to store and/or display this data in the portal...

And in this case it would seem possible to simply create the bash/betas folder and put suitably stand-alone features in there for interested users to install by running the script directly, once ready for release the install script could be moved to the relevant decoders/feeders/extras folder and integrated into the install script so that its available in the appropriate menu.

Sound reasonable?

**Comment by jprochazka** [comment]
Defiantly sounds reasonable. Don't take it personal that I am closing this issue it is only due to the fact it is not an issue and I am trying to clean up the tracker after returning from my absence.
