### ISSUE TITLE
Menu to select additional decoders

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#309]
When Dump978 was the only additional decoder option I can see how an additional menubox was the simplest solution to ask the user if they would like to install this; however with the addition of the RTL-SDR OGN decoder (#129) it highlights this will not scale well if additional decoders are added...

So if the definition of a decoder is anything which requires its own tuner then we will likely have the ACARS decoder (#288) at some point and, while the HAB LoRa Gateway (#279) could potentially be considered as either a decoder or an extra due to its requirement for a dedicated LoRa radio module, it seems likely there will be more in the future...

So I was wondering if it was worth making an additional menu in the installed for decoders, similar to the current feeders and extras menus, to allow the users to select any/all of the additional decoders and potentially be advised of how many tuners this selection would require before proceeding?

This would presumably follow the placement of the current Dump978 and RTL-SDR OGN install questions in being after the dump1090 installation options, which I recently changed from a --menu to --radiolist to make it more obvious that only a single dump1090 fork can be installed..

From there is should be possible to count the number of tuners required by the decoders selected, in addition to dump1090, and either warn or give the user the option to revise their decoder selection to match the available tuner count :)

**Comment by jprochazka** [comment]
The thought behind keeping things the way they are is to keep the options separate so multiple copies of what is generally the same decoder are not installed. Only one dump1090 instance should be installed at any given time just as only one dump978 instance should be installed at any given time as well. Separating dump1090 selections from dump978 selections and only allowing the user to select one saves users from accidentally installing multiple instances without having to write more complex business rules to catch said mistake.
