### ISSUE TITLE
Move the dump1090 --measure-noise flag to /etc/defaults/dump1090-mutability ?

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#313]
So I recently commended on the method which graphs.sh modifies the init script against the original commit (https://github.com/jprochazka/adsb-receiver/commit/1fdf95d548aeb49b4a711560d45f7559b6328968):

> Could this be achieved by adding the --measure-noise flag to the EXTRA_ARGS="" line of /etc/default/dump1090-mutability, thus avoiding making changes to /etc/init.d/dump1090-mutability ?

Now following some recent updates to dump1090-mutability I re-ran the main install script, picked up the update and when dpkg went to install the package it prompts with the following:

```
Setting up dump1090-mutability (1.15~dev) ...

Configuration file '/etc/init.d/dump1090-mutability'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** dump1090-mutability (Y/I/N/O/D/Z) [default=N] ?  D

--- /etc/init.d/dump1090-mutability     2017-02-07 20:34:05.376348667 +0000
+++ /etc/init.d/dump1090-mutability.dpkg-new    2017-02-09 17:31:26.000000000 +0000
@@ -1,8 +1,8 @@
 #!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          dump1090-mutability
-# Required-Start:    $remote_fs
-# Required-Stop:     $remote_fs
+# Required-Start:    $remote_fs $network
+# Required-Stop:     $remote_fs $network
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: dump1090 daemon (mutability variant)
@@ -18,7 +18,7 @@
 DESC="dump1090-mutability daemon"
 NAME=dump1090-mutability
 DAEMON=/usr/bin/$NAME
-ARGS="--measure-noise "
+ARGS=""
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME

```

The addition of $network as a requirement to start dump1090, which was an upstream fix to the issues reported in #307, the installation will revert the change to add the --measure-noise flag used to collect data for the graph... at least until the portal is re-installed and the change re-applied.

So I just wanted to check if there was any reason why the application of this flag couldn't or shouldn't be moved to /etc/defaults/dump1090-mutability ?

**Comment by jprochazka** [comment]
Sounded like a good idea so changed where this flag went in commit e35a3c5524194907a9937d1691ca4aa857278d38.
