### ISSUE TITLE
MLAT client will not install if the configured version does not match the latest version

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#316]
This issue was originally reported in the forum:

https://www.adsbreceiver.net/forums/topic/error-installing-adsb-exchange

After some digging it appears that the current code to download and install the mlat-client expects the resulting deb package to contain the configured version string which is configured as $MLATCLIENTVERSION, which is sourced from bash/variables.sh and currently set to "0.2.6" on the master branch:

```
master/adsb-receiver$ grep MLATCLIENTVERSION bash/variables.sh 
MLATCLIENTVERSION="0.2.6"
```

And from the failed install:

```
dpkg-deb: building package `mlat-client' in `../mlat-client_0.2.8_armhf.deb'.
 dpkg-genchanges -b >../mlat-client_0.2.8_armhf.changes
dpkg-genchanges: binary-only upload (no source code included)
 dpkg-source --after-build mlat-client
dpkg-buildpackage: binary-only upload (no source included)

  Installing the mlat-client package...

dpkg: error processing archive /home/pi/adsb-receiver/build/mlat-client_0.2.6*.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 /home/pi/adsb-receiver/build/mlat-client_0.2.6*.deb

  Checking that the mlat-client package was installed properly...

  INSTALLATION HALTED!
  UNABLE TO INSTALL A REQUIRED PACKAGE.
  SETUP HAS BEEN TERMINATED!

The package "mlat-client" could not be installed.

----------------------------------------------------------------------------------------------------
  ADS-B Exchange feed setup halted.

Press enter to continue...

```

**Comment by Romeo-Golf** [comment]
The summary is that neither the` $MLATCLIENTVERION` or `$MLATCLIENTTAG` variables actually control which version of the mlat-client code is downloaded....  which on the mlat-client master branch is presently version 0.2.8 so the deb package built from this code is named `mlat-client_0.2.8_armhf.deb` while the install script is expecting to find something matching `mlat-client_0.2.6*.deb`.

`  
`

At first glance the 'easy' fix would be to bump the versions configured in bash/variables.sh to match the latest release; however as per issue #310 _MLAT Client Version bump to 0.2.8_ this release has a bug which prevents it from being able to feed MLAT data to ADSB Exchange...

The good news is that there is a fix for this issue (https://github.com/mutability/mlat-client/commit/546e43396fa773a86506e3c3a0b59116d195d2a3), unfortuantely this is only present in the mlat-client dev branch as 0.2.9-dev with no committed timescales for release of a stable 0.2.9 release to the master branch: https://github.com/mutability/mlat-client/compare/dev

`   
`

As these issues are outside of out control I suspect the best course of action would be updating the code which installs the mlat-client so that it makes use of the git tags to check out a 'known good' version as defined by the values in `bash/variables.sh`, thus ensuring that the resulting deb package name matches the file name which the install script currently expects to find :)

**Comment by Romeo-Golf** [comment]
So onto fixing it...

I think the first time I would have reinstalled the mlat-client after the version in the uptream master branch stopped being 0.2.6 (in commit https://github.com/mutability/mlat-client/commit/b804cc364ee97c17bd2a215e8146ba89ebd28a46) would have been while working on the 2.6.0 branch which had its mlat client version bumped to 0.2.7 (in commit https://github.com/jprochazka/adsb-receiver/commit/afef37744f532c44b653f4e0f75ece87ad138674#diff-419a0919c02e336c702e74fdd730ee0b), hence had not noticed this while doing further work on the adsbexchange.sh script which installs the mlat client.

As this issue was also reported with the standalone adsb exchange feeder script I had a look at that code and saw that it attempts to use the `$MLATCLIENTTAG`, which having checked the history for the adsbexchange.sh script in here saw there has also previously been some code to checkout based on tag:

https://github.com/jprochazka/adsb-receiver/commit/30d0573cf658fbed5b82647182f474c4ad435696#diff-8cdcdb789cb0151a698a1c563aa20afcL86

So using those examples, combined with some reading up on the github syntax required to reliablly check out code based on tags, I have some code to commit to my 2.7.0 branch and start testing shortly...

Assuming that goes to plan I will itterate it down to 2.6.0 and then to 2.5.1 as the minimal set of changes required for fix this issue; however as it stands new installs are unable to compile a working mlat client so should hopefully be a catalyst to get 2.5.1 out as a bugfix release :)

**Comment by Romeo-Golf** [comment]
Changes seem to work as expected so have pushed them to my 2.6.0 branch, the below output confirms that the mlat-client version 0.2.7 is built and installed as per the values in variables.sh ;)
                                                                                                                                                
```
  Preparing the mlat-client Git repository...

  Entering the mlat-client git repository directory...
  Fetching changes from the remote mlat-client git repository...

From https://github.com/mutability/mlat-client
   89c18fe..40f1a8f  dev        -> origin/dev
  Updating the local mlat-client git repository...

HEAD is now at 89c18fe Prepare for 0.2.8 release.
  Checking out mlat-client version "v0.2.7"...

HEAD is now at 43c13f0... Preparing for 0.2.7 release.

  Building and installing the mlat-client package...

  Building the mlat-client package...

dpkg-buildpackage: source package mlat-client
dpkg-buildpackage: source version 0.2.7
dpkg-buildpackage: source distribution stable

```

```
dpkg-deb: building package `mlat-client' in `../mlat-client_0.2.7_armhf.deb'.
 dpkg-genchanges -b >../mlat-client_0.2.7_armhf.changes
dpkg-genchanges: binary-only upload (no source code included)
 dpkg-source --after-build mlat-client
dpkg-buildpackage: binary-only upload (no source included)

  Installing the mlat-client package...

(Reading database ... 46373 files and directories currently installed.)
Preparing to unpack .../mlat-client_0.2.7_armhf.deb ...
Unpacking mlat-client (0.2.7) over (0.2.6) ...
Setting up mlat-client (0.2.7) ...
Processing triggers for systemd (215-17+deb8u6) ...
```

**Comment by Romeo-Golf** [comment]
Of course if anyone is able to assist with testing then the following commands should install my 2.6.0 branch onto a clean debian/raspian install:
```
sudo apt-get update
sudo apt-get install git
git clone -b 2.6.0 https://github.com/romeo-golf/adsb-receiver.git
cd ~/adsb-receiver
chmod +x install.sh
./install.sh
```

**Comment by Romeo-Golf** [comment]
And now in my 2.5.1 branch, with a small change to allow PROJECTBRANCH to be specified from the CLI :)

```
export PROJECTBRANCH="2.5.1"
sudo apt-get update
sudo apt-get install git
git clone -b ${PROJECTBRANCH} https://github.com/romeo-golf/adsb-receiver.git
cd ~/adsb-receiver
chmod +x install.sh
./install.sh 
```

**Comment by Romeo-Golf** [comment]
Also pushed this change to my 2.5.1 branch so that #310 'Update MLAT Client to version 0.2.9' will be available :)

**Comment by jprochazka** [comment]
This was how things were initially intended to be. Early on ADS-B Exchange was running a release of mlat-server which was not compatible with the master branch at the time. In order to avoid issues which may arise from development code committed to the master branch it was decided to specify the release and update it to whatever release ADS-B Exchange was expecting users to run at any given time by supplying it in the variables.sh file as is done with all third party software.

Many of these changes have been removed to restore this functionality to its original form eliminating extra complexity for the end user in commit d04002979036c939e5637b4e077fef864a32d37a made to this project.
