### ISSUE TITLE
Avoid piping wget/curl directly into a root shell where possible

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#319]
Seems like this should be avoided if possible, particularly when piping to a sudo bash shell:

https://tserong.github.io/sudo-wget/
https://www.seancassidy.me/dont-pipe-to-your-shell.html
https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/

I dont know if there are any obvious answers for instances in the adsb-receiver code, but I look to at least replace any direct pipes from wget/curl to at least save the script in the build directory for inspection later.

**Comment by jprochazka** [comment]
I agree so if you find a better way I am open to suggestions. I honestly do not see one being the project is based on making the installation of third party software easier.
