### ISSUE TITLE
Use https where possible

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#320]
Obviously it would be nice to use https where possible and while a number of URL's provided by the upstream providers are not always https, it appears that the majority are hosted on one of the major CDNs...

Consequently these web servers listen on port 443 and support HTTPS connections, at least if the client is prepared to accept that there may not nessisarily have a certificate for the hostname in the clients request.

Therefor I thought i would raise this issue to track updating the code to use HTTPS wherever possible, and to highlight any components where it would be beneficial to ask the upstream to provide such a URL :)

**Comment by jprochazka** [comment]
Any linking in the portal portion of the master branch uses relative linking so https can easily be enabled with minor modifications to the web servers configuration file.

Being most people utilizing this project do not tie their device to a domain name they control or have it public facing forcing people to use SSL would the majority of time force users to jump through hoops such as browser warnings telling them not to visit their site or adding private certs to their browser.

If in there is a want or need to automate the switch to SSL it would be quite trivial to add support for say lets encrypt that is of course if said feature would be wanted. Until then I would rather focus on converting the whole setup process to a web based one after stabilizing what is currently available.
