### ISSUE TITLE
Portal displays only 25 Flights Seen

### ISSUE THREAD

**Issue by MCancellier** [jprochazka/adsb-receiver#322]
The portal Flights Seen page only displays the last 25 flights seen, and will not allow you to page to display more flights. Using MySQL database with advanced features turned on.

**Comment by Romeo-Golf** [comment]
Hi, thanks for reporting this and I will need to check the code to confirm the expected behaviour.. in the mean time would you mind sharing a screenshot?

**Comment by MCancellier** [comment]
I had to do two screenshots to get top and bottom of the list:
[Screen Shot 2017-02-27 at 27 Feb 17-0709 1.PDF](https://github.com/jprochazka/adsb-receiver/files/803863/Screen.Shot.2017-02-27.at.27.Feb.17-0709.1.PDF)
[Screen Shot 2017-02-27 at 27 Feb 17-0709.PDF](https://github.com/jprochazka/adsb-receiver/files/803864/Screen.Shot.2017-02-27.at.27.Feb.17-0709.PDF)

**Comment by Romeo-Golf** [comment]
Hi,

Looking at flights.php I can see the following in the code:

```
    // Items per page.
    $itemsPerPage = 25;
```

And then in the template there is code to add links to the additional pages, if required:

                <ul class="pagination">
                    {for pageNumber eq 1 to page:pageLinks}
                    <li><a href="flights.php?page={pageNumber}">{pageNumber}</a></li>
                    {/for}
                </ul>

Can you try scrolling down on the middle of the page to see if these links are at the bottom after the table of the last 25 flights?

If there is no sign of these links can you right click on the middle of the page, go to view source and share that?

**Comment by MCancellier** [comment]
The tabular section in the middle doesn't scroll independently from the rest of the page. No links at the bottom. Is there something in particular you want to see from View Source? In Safari that brings up the Web Inspector which has a ton of data. Anything in particular you want to see? It does show some errors, do you want to see those or the code itself?

**Comment by MCancellier** [comment]
Here are a bunch of screenshots. If you see anything interesting, let me know…
![screen shot 2017-02-27 at 27 feb 17-1615 1](https://cloud.githubusercontent.com/assets/25111464/23384415/1dddcc7c-fd08-11e6-85d5-612f578977ec.jpg)
![screen shot 2017-02-27 at 27 feb 17-1614 1](https://cloud.githubusercontent.com/assets/25111464/23384419/1dfaf66c-fd08-11e6-97f4-5f443881c65e.jpg)
![screen shot 2017-02-27 at 27 feb 17-1615 2](https://cloud.githubusercontent.com/assets/25111464/23384418/1df56e0e-fd08-11e6-93ff-2ae675dd2b97.jpg)
![screen shot 2017-02-27 at 27 feb 17-1614](https://cloud.githubusercontent.com/assets/25111464/23384416/1df53cd6-fd08-11e6-9da6-51348d9426cd.jpg)
![screen shot 2017-02-27 at 27 feb 17-1615 3](https://cloud.githubusercontent.com/assets/25111464/23384420/1e4605da-fd08-11e6-90b8-26f058c04d66.jpg)
![screen shot 2017-02-27 at 27 feb 17-1615](https://cloud.githubusercontent.com/assets/25111464/23384417/1df55fd6-fd08-11e6-8062-bc0502c67318.jpg)

**Comment by Romeo-Golf** [comment]
thanks again for the details and screenshots, it looks like the pagination script (http://botmonster.com/jquery-bootpag/) may not be installed... would you mind sharing the output of the following command:

`ls -l ~/adsb-receiver/build/portal/html/templates/default/assets/js/`

**Comment by MCancellier** [comment]
Looks like it isn’t. Is that a prerequisite that should install with the script or something that should be there in a standard Raspbian build?

total 156
-rw-r--r-- 1 pi pi 37045 Feb 24 12:16 bootstrap.min.js
-rw-r--r-- 1 pi pi  3884 Feb 24 12:16 date.format.js
-rw-r--r-- 1 pi pi  7983 Feb 24 12:16 graphs.js
-rw-r--r-- 1 pi pi 86709 Feb 24 12:16 jquery-3.1.1.min.js
-rw-r--r-- 1 pi pi  4330 Feb 24 12:16 jquery.sidebar.js
-rw-r--r-- 1 pi pi  1355 Feb 24 12:16 notifications.js
-rw-r--r-- 1 pi pi  3543 Feb 24 12:16 system.js

**Comment by Romeo-Golf** [comment]
To be honest ive only been helping out with the project for a few months and have yet to delve deeply into the portal code; I can see that the `jquery.bootpag.min.js` file is required by the advanced portal but doesnt appear to be installed by the install script :(

The following command will download the required file from github, please note this is a single line:

`wget -O ~/adsb-receiver/build/portal/html/templates/default/assets/js/jquery.bootpag.min.js https://raw.githubusercontent.com/botmonster/jquery-bootpag/master/lib/jquery.bootpag.min.js`

Would you mind testing this and confirming that it resolves the reported issue?.. if so I should be able to push the fix out to my 2.6.0 branch pretty quickly :)

**Comment by MCancellier** [comment]
Well, I tried that. No joy. Then I get another error:
![screen shot 2017-02-28 at 28 feb 17-1728](https://cloud.githubusercontent.com/assets/25111464/23440800/af425826-fddb-11e6-930a-f97d801932c0.jpg)

**Comment by MCancellier** [comment]
It is also throwing errors about the flight notification code. I think it must be unfinished. You can put an N-number in to the notification preference page, but it doesn't seem to go anywhere. Here is the reoccurring error that shows on the Flights Seen page:
![screen shot 2017-02-28 at 28 feb 17-1729](https://cloud.githubusercontent.com/assets/25111464/23440861/17129d62-fddc-11e6-8afc-976fb92a6e6a.jpg)

**Comment by MCancellier** [comment]
And note the CSS advisory in yellow:
![screen shot 2017-02-28 at 28 feb 17-1734](https://cloud.githubusercontent.com/assets/25111464/23440904/50e9efd6-fddc-11e6-900a-c69ed15bab9b.jpg)

**Comment by Romeo-Golf** [comment]
Thanks for the updates and unfortunately it may well be a case that the install time disclaimer that "the advanced portal features are still in development" means that there is still some outstanding work on these features...

Which hopefully @jprochazka will get a chance to finish off for the 2.6.0 release; however it may be worth trying my 2.5.1 release, which is a bugfix only release based on the current 'stable' version 2.5.0, and thus should result in an Advanced Portal install that at least does what it  supposed to :) 

Also FYI from what I can see it may be a jquery version issues that is preventing the pagination code from working, I will need to do some more digging but it does seem like what is described here:

https://geeksprogrammings.blogspot.com/2015/01/Uncaught-TypeError-undefined-is-not-a-function.html

**Comment by patmont** [comment]
If it's helpful for script diagnostics to mention: I have had had Flights pagination work successfully on 2 clean builds where I cloned from master. I also chose MySQL option on Rpi3 installed through the advanced features. 

![screenshot from 2017-02-28 21-58-46](https://cloud.githubusercontent.com/assets/24196951/23447643/22f260a2-fe01-11e6-8aa3-0a463850ba80.png)

**Comment by Romeo-Golf** [comment]
@patmont thanks for the info, it looks @jprochazka was trying to use the bootpag jQuery script to condense the screen real estate required to display links to many hundreds, or potentially thousands, of historical flights logged by an advanced portal install with this commit: 043349c916abe0736005e4c1583da78adcefaa80 

Unfortunately the bootpag script looks to have been written for jQuery version 1, while its version 3 that is used by the other portal functionality... hence the Uncaught Type Error 'undefined is not a function' reported when accessing the flights.php in the 2.6.0 branch.


As my contributions have mostly been around the decoder/feeder components I have only tried 2.6.0 on my Pi's but I will see if I can find some time to spin up another vm for a 2.6.0 branch install with the advanced portal installed so I can try to help out with issues such as this one :)

Its also worth highlighting that my experience with jQuery is minimal so if there is anyone who can provide any assistance with either getting the current bootpag script to work, or suggest a suitable replacement that plays nice with jQuery 3, that would be greatly appreciated...  

@jdwall how is your familiarity with jQuery?  ;)

**Comment by jprochazka** [comment]
The code making up the pagination on this page had been updated on my end at one point however I need to go through and find it again or rewrite it. It used totally different pagination code doing away with showing EVERY page available. I will be making this a priority and should find its way into the upcoming 2.6.0 release.
