### ISSUE TITLE
Portal Flights Seen plotting non-functional

### ISSUE THREAD

**Issue by MCancellier** [jprochazka/adsb-receiver#323]
When clicking through a flight link, the portal.php page displayed flashes flight info and then pulls a Google Maps page centered on Cleveland, OH. No tracks or flight info are displayed.

**Comment by Romeo-Golf** [comment]
Hi,

Can you confirm what platform your are running on and if you are using the dump1090-mutability or dump1090-fa fork?

Thanks.

**Comment by MCancellier** [comment]
I am on a Raspberry Pi 3, Raspbian Jessie latest with dump1090-mutability.
Viewing it on a MacBook Pro with either Safari or Firefox latest...

Mike Cancellier
Cancellier@gmail.com

**Comment by Romeo-Golf** [comment]
Thanks for the swift reply, would you mind sharing a screenshot and if possible SSH into the device to grab the output of 'sudo systemctl status dump1090-mutability' ?

**Comment by Datamix** [comment]
Have tried to navigate to your location? I think the region around Cleveland is the default location set by Joe.

**Comment by Romeo-Golf** [comment]
If the receiver Latitude and Longitude were provided when dump1090 was installed then these values should be used to centre the map, if not then I think as you say the default location may be Elyria, Ohio.

**Comment by MCancellier** [comment]
First the terminal dump:
● dump1090-mutability.service - LSB: dump1090 daemon (mutability variant)
   Loaded: loaded (/etc/init.d/dump1090-mutability)
   Active: active (running) since Sun 2017-02-26 09:47:24 MST; 21h ago
  Process: 12858 ExecStop=/etc/init.d/dump1090-mutability stop (code=exited, status=0/SUCCESS)
  Process: 12889 ExecStart=/etc/init.d/dump1090-mutability start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/dump1090-mutability.service
           └─12899 /usr/bin/dump1090-mutability --measure-noise --net --device-index 1 --ppm 0 --fix --lat 38.81279 --lon -104.8589049 --max-range 300 --net-ri-port 30001 --net-ro-port 30002 --net-bi-port 30004,30104 --net-bo-port 30005 --net-sbs-port 30003 --net-heartbeat 60 --net-ro-size 500 --net-ro-interval 1 --net-buffer 2 --stats-every 3600 --write-json /run/dump1090-mutability --write-json-every 1 --json-location-accuracy 1 --quiet

Feb 26 09:47:24 adsb-recevier systemd[1]: Started LSB: dump1090 daemon (mutability variant).

Now the screenshot:

[Screen Shot 2017-02-27 at 27 Feb 17-0710.PDF](https://github.com/jprochazka/adsb-receiver/files/803860/Screen.Shot.2017-02-27.at.27.Feb.17-0710.PDF)

**Comment by Romeo-Golf** [comment]
Hmm, so if dump1090 has been configured with LAT/LON then this should be displayed as a dot on the map.. have you tried scrolling the map to your location?

**Comment by MCancellier** [comment]
Yep. Nothing there. No dot, no track, nothing.

**Comment by Romeo-Golf** [comment]
Interesting, although the google maps part may be relevant as the current dump1090 install should use openstreetmaps.. can you try re-running the install script and saying yes when it asks if you would like to reinstall dump1090-mutability?

Thanks.

**Comment by MCancellier** [comment]
Doing that now. Just for reference, this was a clean install of your 2.6.0 branch...

**Comment by MCancellier** [comment]
No change after the reinstall. I noticed when perusing the portal scripts that Google Maps is explicitly called. I don't think that dump1090 is connected….

**Comment by Romeo-Golf** [comment]
Hi, there a few references to Google maps which pre-date their decision to require an API key, at which point the underlying dump1090 software switches to using OpenStreetMap's by default...

You can during the portal install specify a google maps API key, can you confirm if you have entered this?

**Comment by MCancellier** [comment]
Yes, I do have a Google Maps key entered.

**Comment by Romeo-Golf** [comment]
ah ok, thanks for confirming and at least that is one thing we can rule out :)

You mention in the original report that this occurs "When clicking through a flight link", can you advise if this link is from the 'flights seen' page?

**Comment by MCancellier** [comment]
Yep

**Comment by jprochazka** [comment]
Cannot recreate this issue using the projects master branch so I am closing this issue. If you experience this issue using this projects master branch in the future please feel free to reopen this issue or pen another. If you do so please supply information such as the type of database being used, browser name and version, etc..
