### ISSUE TITLE
Date formatting incorrect on Portal Admin Page

### ISSUE THREAD

**Issue by MCancellier** [jprochazka/adsb-receiver#324]
The date formats on the last two selections of the 24 hour format block are reversed.
![screen shot 2017-02-27 at 27 feb 17-1619 1](https://cloud.githubusercontent.com/assets/25111464/23384519/90b6d13a-fd08-11e6-8ba4-cbfd4cd4f48a.jpg)
![screen shot 2017-02-27 at 27 feb 17-1619](https://cloud.githubusercontent.com/assets/25111464/23384520/90d0f4ca-fd08-11e6-805f-bb6992ae2887.jpg)

**Comment by MCancellier** [comment]
Oh, I understand what they are for, but the format in the radio button section doesn’t match the coding at the bottom. They are reversed!

**Comment by Romeo-Golf** [comment]
ahh good spot, I have pushed a fix to my 2.6.0 branch to correct the date format examples to they match the values which are actually used ;)

**Comment by MCancellier** [comment]
Thanks!

**Comment by jprochazka** [comment]
Fixed in commit 569279229b32a3d429196d1be3c39fb0fc1d66fe.
