### ISSUE TITLE
Feature request: Automatically hide footer and nav bar on map view

### ISSUE THREAD

**Issue by Mictronics** [jprochazka/adsb-receiver#325]
A small JS hack allows to automatically hide the footer and navbar, providing maximum map view. Navbar is shown again when mouse enters the area.
In master.tpl change the last script tag to:
```
        <script type="text/javascript">
            $('#{template:pageId}').addClass("active");
			
			setTimeout(hideNavbar, 10000);
			setTimeout(hideFooter, 10000);
			function hideFooter(){
				if ( $("#iframe-wrapper").length ) {
					$('#iframe-wrapper').css('bottom', '0px');
				}
			};
			
			$('#navbar').mouseenter(function() {
				$('#navbar').fadeTo(600, 1.0, function(){
					$('#iframe-wrapper').css('top', '50px');
				});
			});
			
			$('#navbar').mouseleave(function() {
				setTimeout(hideNavbar, 3000);
			});

			function hideNavbar(){
				if ( $("#iframe-wrapper").length ) {
					$('#navbar').fadeTo(400, 0.05, function(){
						$('#iframe-wrapper').css('top', '0px');
					});
				}
			};
        </script>
```
Navbar and footer are always shown in any other portal view.

**Comment by Romeo-Golf** [comment]
Thanks for the suggestion and code contribution, I will see if i can get a chance to test this and if it works as expected will look to include in my 2.6.0 branch...

Out of interest have you tried viewing this on any mobile device browsers as this may be an area where the reclaimed screen area is most beneficial?

**Comment by Mictronics** [comment]
It works, tested on two Android 7". Another option is not to use bootstraps "navbar-fixed-top" but "navbar-static-top". At least then it scrolls away.
Getting the most out of the screen is by using jQuery-UI accordion for the side-bar. I have included that in my dump1090-fa fork. You may have a look at that as well.

**Comment by jprochazka** [comment]
This requests relates well with what I am currently working on a truly mobile friendly way to view real time data supplied by dump1090, dump978, etc.. A full screen feature will be added with the new map I am working on for v3.0.0 or possibly v2.7.0.

**Comment by jprochazka** [comment]
Added @Mictronics's JavaScript along with an option to toggle navigation and footed auto hiding to the administration area in commit ea73ade7cb561cefb72487a74dab53b67c853212.
