### ISSUE TITLE
Plane Finder ADS-B Client - Installation Halted

### ISSUE THREAD

**Issue by Varbaek** [jprochazka/adsb-receiver#328]
`  Installing packages needed to build and fulfill dependencies...

  Checking if the package libc6 is installed... [OK]
  Checking if the package wget is installed... [OK]

  Downloading the Plane Finder ADS-B Client package...

  Creating the Plane Finder ADS-B Client build directory...
  Downloading the Plane Finder ADS-B Client v3.5.461 for ARM devices...

--2017-03-14 17:52:21--  http://client.planefinder.net/pfclient_3.5.461_armhf.deb
Resolving client.planefinder.net (client.planefinder.net)... 104.86.110.107, 104.86.110.129, 2a02:26f0:10::5c7a:d451, ...
Connecting to client.planefinder.net (client.planefinder.net)|104.86.110.107|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-14 17:52:21 ERROR 404: Not Found.

  Installing the Plane Finder ADS-B Client package...

  Entering the Plane Finder ADS-B Client build directory...
  Installing the Plane Finder ADS-B Client v3.5.461 for ARM devices package...

dpkg-deb: error: `/root/adsb-receiver/build/planefinder/pfclient_3.5.461_armhf.deb' is not a debian format archive
dpkg: error processing archive /root/adsb-receiver/build/planefinder/pfclient_3.5.461_armhf.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /root/adsb-receiver/build/planefinder/pfclient_3.5.461_armhf.deb

  Checking that the pfclient package was installed properly...

  INSTALLATION HALTED!
  UNABLE TO INSTALL A REQUIRED PACKAGE.
  SETUP HAS BEEN TERMINATED!

The package "pfclient" could not be installed.

----------------------------------------------------------------------------------------------------
  Plane Finder ADS-B Client setup halted.

`

**Comment by Romeo-Golf** [comment]
Hi,

Thanks for the issue report, this has been fixed with change #317 which is targeted for the 2.5.1 branch but unfortunately there is no firm ETA for this to be released.

In the mean time this fix is present in the 2.5.1 branch of my fork which you can switch to this using the following commands:

```
export PROJECTBRANCH=2.5.1
cd ~/adsb-receiver
git remote rm origin
git remote add origin https://github.com/romeo-golf/adsb-receiver.git
git fetch
git checkout -b ${PROJECTBRANCH} origin/${PROJECTBRANCH}
./install.sh
```

Regards.

**Comment by Varbaek** [comment]
Thanks for the update

**Comment by KeelinJ** [comment]
@Romeo-Golf After I switch to your branch, running install.sh switches it back to master (and gives me the issue mentioned above). Any advice?

**Comment by Datamix** [comment]
If you want to install the 2.6.0 branch try:

./install.sh -b 2.6.0

**Comment by KeelinJ** [comment]
Thanks! Knew I was missing something

**Comment by Romeo-Golf** [comment]
> @Romeo-Golf After I switch to your branch, running install.sh switches it back to master (and gives me the issue mentioned above). Any advice?

@KeelinJ,

Unfortunately the ability to specify the install script to use a branch other than the master with the '-b' option was only introduced in the 2.6.0 release, so to use the 2.5.1 release you will need to set this as a variable prior to running install.sh using the following command

`export PROJECTBRANCH=2.5.1 && ./install.sh`

Regards.

**Comment by jprochazka** [comment]
Planefinder.net client version updated in master branch.
