### ISSUE TITLE
Flights Seen currently not working

### ISSUE THREAD

**Issue by Varbaek** [jprochazka/adsb-receiver#329]
`
root@flightradar:~# /usr/bin/python /root/adsb-receiver/build/portal/python/flights.py
Traceback (most recent call last):
  File "/root/adsb-receiver/build/portal/python/flights.py", line 199, in <module>
    processor.processAircraftList(data["aircraft"])
  File "/root/adsb-receiver/build/portal/python/flights.py", line 102, in processAircraftList
    self.processAircraft(aircraft)
  File "/root/adsb-receiver/build/portal/python/flights.py", line 111, in processAircraft
    self.cursor.execute(self.STMTS['select_aircraft_count'], (hexcode,))
sqlite3.OperationalError: no such table: adsb_aircraft
root@flightradar:~#
`

I've checked the "portal.sqlite" file in "/var/www/html/data/" and confirmed that it does contain this field.

**Comment by Varbaek** [comment]
Update: With MySQL it does work though. 

It seems that the generated file does not point correctly to the database maybe.

**Comment by jprochazka** [comment]
I will be testing v2.6.0 using SQLite shortly and will look into this issue at that time.

**Comment by jprochazka** [comment]
Fixed this issue as well as issues dealing with installation on Stretch based distros. The issue pertaining to you was due to a variable containing the path to the database being placed in a different place in config.json at some point. 

commit 5e0e6e0c1579de31926cc6798f058fec4fb3d92d
