### ISSUE TITLE
Unable to change "Up In Th Air" overlay

### ISSUE THREAD

**Issue by spaprzycki** [jprochazka/adsb-receiver#332]
Hello,

I have just started using your ADS-B Receiver software (I have been running bare Piaware & FR24 software up until now).

I have done initial install and pointed the install script at my panorama from HeyWhatsThat. All worked well, I got my theoretical range plotted.

I am now trying to use the receiver in different location, but cannot make the dump1090-mutability to change the plot to my new locations.

I have replaced "/usr/share/dump1090-mutability/html/upintheair.json" with file for my new location, but dump1090.php is still graphing the old plot.

Could you please let me know if it is cached somewhere and needs clearing or is above file not what's used for making the plot?

Btw. Awesome piece of software, so far loving it. The receiver stats is exactly what I needed. I will look into ways to contribute to your project! Thanks for all your work!

Thanks!
Regards,
Sergiusz

**Comment by spaprzycki** [comment]
self-service response :)

In /usr/share/dump1090-mutability/html/script.js:

lines 560 & 561, timeout & cache flag respectively.

Hopefully someone will find it useful in the future!

Regards,
Sergiusz

**Comment by Romeo-Golf** [comment]
Thanks for the report, I will try to factor in the option to update the upinetheair value at least during re-installation of dump1090-mutability...

**Comment by jprochazka** [comment]
You might want to point this out on the dump1090-mutability and/or dump1090-fa issue tracker. The JavaScript file you are referring to is maintained by them.
