### ISSUE TITLE
Dump1090 Compilation Issue

### ISSUE THREAD

**Issue by crablab** [jprochazka/adsb-receiver#335]
Whilst this isn't technically you're issue as I note that another repository is used, I don't know which one it is so I'm putting the bug report here! 

Whilst installing, the Dump1090 compilation fails due to a memory segmentation issue in the `binutils` package: 

> collect2: error: ld terminated with signal 11 [Segmentation fault]
> Makefile:54: recipe for target 'dump1090' failed
> make[2]: *** [dump1090] Error 1
> make[2]: Leaving directory '/home/pi/adsb-receiver/build/dump1090-mutability/dump1090'
> dh_auto_build: make -j1 EXTRACFLAGS=-DHTMLPATH=\"/usr/share/dump1090-mutability/html\" -DMODES_DUMP1090_VARIANT=\"dump1090-mutability\" returned exit code 2
> debian/rules:21: recipe for target 'override_dh_auto_build' failed
> make[1]: *** [override_dh_auto_build] Error 2
> make[1]: Leaving directory '/home/pi/adsb-receiver/build/dump1090-mutability/dump1090'
> debian/rules:30: recipe for target 'build' failed
> make: *** [build] Error 2
> dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by jprochazka** [comment]
Apparently this was an issue @mutability has addressed or was specific to your setup so marking this is invalid only due to the fact the issue no longer appears to exist and/or does not involve an issue with this project specifically.
