### ISSUE TITLE
Pi2 Flightaware Mlat client issue with v2.5.1

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#338]
Hi , Upgraded my v2.50 to 2.5.1 on raspberry pi 2 using guide kindly supplied by romeo-golf.
Everything installed okay including FA feeder 3.5 but I now have an issue with the fa mlat client which shows not synchronised. This could be related, seems to be recent pi upgrade firmware.
 http://discussions.flightaware.com/ads-b-flight-tracking-f21/mlat-anomalies-t38891-25.html

Using the script, is there a way to downgrade firmware only please ?

BTW I did make request for uninstall various feeder options in issue  #261 .

**Comment by radiostationx** [comment]
resolved  with the fa mlat client issue by downgrading pi kernel from 4.9 to 4.4.50 using the following

`sudo apt-get install rpi-update`

`sudo rpi-update 52241088c1da59a359110d39c1875cda56496764`

fa mlat client working fine, just that now i cannot  take system updates from this script which is the first process/selection following ./install.sh until firmware issue effecting pi2 is resolved.

**Comment by totalhavoc** [comment]
It looks like 4.9.29 fixes the issue 
sudo rpi-update aeb5f6166d3ef7298f6fee644ac8cebb7a8fa133

According to the notes on github it adds usb parity support

**Comment by phg2k** [comment]
@totalhavoc works fine on my 2 pis now! Thanks!

**Comment by totalhavoc** [comment]
Yeah, 4.9.29 was working for 4 hours when I posted. About 8 hours after that it stopped.. back to 4.4 for me too

**Comment by jprochazka** [comment]
Seems to be a Raspbian issue not related to this project so closing out this issue.
