### ISSUE TITLE
Blog Issue

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#340]
Create new blog.
Does not save /display correctly .

**Comment by jprochazka** [comment]
Is this an issue experienced with the fork or the code found here? I do not see any issue when creating a post in advanced features using MySQL. However I will test advanced features using SQLite and the lite version as I create said setups for testing.

Keep in mind information such as the installed portal feature, what you are saving data to such as MySQL, SQLite, or XML and the browser you are using helps tremendously when troubleshooting such an issue.

**Comment by jprochazka** [comment]
I have not been able to recreate this issue using either the MySQL, SQLite, or XML options using the code contained in the master branch.
