### ISSUE TITLE
Suggestion: Add new feeder option OpenSky Network

### ISSUE THREAD

**Issue by willfrd** [jprochazka/adsb-receiver#341]
Just wondering if it would be posible in a furutre version to add as one of the supported websites OpenSky.
Here are relevant links:
Main site: https://opensky-network.org/
Explorer: https://opensky-network.org/network/explorer
Contributing with Raspberry Pi: https://opensky-network.org/community/projects/30-dump1090-feeder
BTW, I don't know if its the moment or the place to ask, but is there any idea when the next version will be up?, I've seen the development has slowed down, I don't want to pressure or criticize anyone, the opposite I greatly appreciate all the effort put in this wonderful project, just asking :)

**Comment by Romeo-Golf** [comment]
@willfrd,

Thanks for the suggestion, although there is an open request to add OpenSky Network under issue #286 

With regards to release schedule there are a number of community submitted changes in my [2.5.1 branch](https://github.com/jprochazka/adsb-receiver/pull/295), hopefully @jprochazka will have a chance to review and accept these prior to embarking on any new development on the 3.0.0 branch..

In the mean time if you would like to help with 'beta testing' the code which is hoped to become the 2.5.1 release then the instructions on how to switch can be found here:

https://www.adsbreceiver.net/forums/topic/romeo-golf-fork-and-how-to-assist-with-testing/

Regards.

**Comment by willfrd** [comment]
Ok, thanks for the information, yeah, I'll give it a try when I have time :-)
