### ISSUE TITLE
[Question] Connecting to VRS

### ISSUE THREAD

**Issue by willfrd** [jprochazka/adsb-receiver#343]
I've managed to load in a domain the Virtual Radar Server (VRS), which has a url:port to fixed to recive data, the question is how do I configure the RPi to sent the data into the VRS? I've found a setting in  /etc/default/dump1090-mutability which says "NET_BIND_ADDRESS" and is fixed as default to "127.0.0.1", could it be I need to add another argument with the url:port of the VRS, and if so, how?, I've try to 'play' around with it but nothing has worked, any help is greatly appreaciated :D

**Comment by jprochazka** [comment]
Comment the line starting with NET_BIND_ADDRESS with a # and restart dump1090. You can then read data from dump1090 via VRS on any IP address assigned to the RPi.
