### ISSUE TITLE
Can't acces raw data from another computer

### ISSUE THREAD

**Issue by willfrd** [jprochazka/adsb-receiver#344]
Hey guys,
I know that the software by default outputs all the raw data that is being received in different ports with different formats within the localhost , e.g. SBS in port 30003. My issue is that when from another computer within the local network I type the ip:port of the RPi to see the data being received raw it answers with a 'connection rejected' message. Is there any way to make this work?
Thanks

**Comment by DL4OCH** [comment]
It really depends on the browser.
Chrome won't work, Firefox does.

**Comment by willfrd** [comment]
Thanks for the reply, true, I was using Chrome, but in Firefox it doesn't work either:
![](https://i.gyazo.com/c07965936f707bd43cdf43e8de0c3333.png)

:-(

**Comment by DL4OCH** [comment]
Please doublecheck if '--net' is in the options if it is dump1090-fa

or that NET_BIND_ADDRESS=127.0.0.1 is commented out with a # im dump1090-muta...

**Comment by willfrd** [comment]
Thanks again for your response, I checked the 'NET_BIND_ADDRESS' variable:
![](https://i.gyazo.com/5815dfe1850e08e8c30051cca58aad37.png)
And as you can see it doesn't have the # at the start of the line.
In regard with 'dump1090-fa' can you tell me what is the location of that file to open it?

**Comment by jprochazka** [comment]
You should be able to simply comment out the line...
`NET_BIND_ADDRESS="127.0.0.1`
After which dump1090 will broadcast the data on all IP addresses. In the future when running setup simply answer yes when the script asks if you would like to bind dump1090 to all IP addresses. This will do the same as commenting out the above line.
