### ISSUE TITLE
FlightRadar24 in Raspberry PI -> missing package "dirmngr"

### ISSUE THREAD

**Issue by Tab3r** [jprochazka/adsb-receiver#346]
Hi. First, thank you for this awesome script!

In my fresh install into my raspberry pi, I found this bug when fr24 feeder was installing:

> gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
> gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
> gpg: keyserver receive failed: No dirmngr

The solution was simple:
> apt-get install dirmngr

And it done!

**Comment by jprochazka** [comment]
Fixed in commit 569279229b32a3d429196d1be3c39fb0fc1d66fe.
