### ISSUE TITLE
Unable to locate package php-cgi

### ISSUE THREAD

**Issue by gleven** [jprochazka/adsb-receiver#353]
During update i get this message and the installation halts

**Comment by jprochazka** [comment]
I used different variable names for the PHP version when detecting the operating system and version. They all match now and should fix this issue.

commit 9ec3f8113244caf4e4de024f4fc52c85cb1bae27

**Comment by gleven** [comment]
Still doesn't work.
Even on a fresh install.

**Comment by jprochazka** [comment]
Forgot to set a default PHP version variable...
commit c5ccb8850dbcd4001bdcfab37bc347d56c74e521 should fix this.
