### ISSUE TITLE
Flights Seen page not indexing.

### ISSUE THREAD

**Issue by jrinky** [jprochazka/adsb-receiver#356]
I have 652 flights logged in MySQL but only the latest 25 flights visible on the "Flights" page. The indexing at the bottom of the page isn't being created. Can some suggest how to solve this or where to look? Thanks.

**Comment by jprochazka** [comment]
Looking into this now. Got to give me some time my test machine to gather some data. It only has a stock RTL-SDR antenna connected to it at the moment.

**Comment by jprochazka** [comment]
A JavaScript file needed to generate the pagination navigation was not committed to the repository. It has now been added in commit e8a0148a19f9910cb193f9cc5befd60a8cdb1cef.

You can download this file and place it into the directory `/var/www/html/templates/default/assets/js` directory from here: https://raw.github.com/botmonster/jquery-bootpag/master/lib/jquery.bootpag.min.js

**Comment by jrinky** [comment]
Thanks very much. :)
