### ISSUE TITLE
Bug: Web Portal Fails to install on Ubuntu 16.04 amd64/i386/armhf

### ISSUE THREAD

**Issue by abcd567a** [jprochazka/adsb-receiver#358]
Web Portal on Ubuntu Mate (Xenial) on RPi, failed due to DISTRO_PHP_VERSION is assuming the default value of 5 instead of 7.0, and as a result, instead of php7.0-cgi, attempted to install php5-cgi which is not available in Ubuntu repositories.

```
Checking if the package php5-cgi is installed... [NOT INSTALLED]
Installing the package php5-cgi...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package php5-cgi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source

E: Package 'php5-cgi' has no installation candidate

  Checking if the package php5-cgi is installed...  [INSTALLATION ATTEMPT FAILED]
```
.
### Bug is in  is in file _bash/portal/install.sh_
```
Error: line 249: [[: 16.04: syntax error: invalid arithmetic operator (error token is ".04")
```
.
I have finally found the reason: The comparison operator _-ge_ used in bash scripts works ok with integer comparison, and fails when used for comparison of a decimal number 16.04. I tried to replace -ge by >=, but it also failed. 

**First Method to Remove Bug:** 
Separately compared integer and decimal parts, and it worked ok.
Replace the original line 249 by modified line as shown below
```
#if [[ $DISTRO_RELEASE -ge "16.04" ]]; then DISTRO_PHP_VERSION="7.0"; fi
if [[ (${DISTRO_RELEASE%%.*} == "16" || ${DISTRO_RELEASE%%.*} > "16") && (${DISTRO_RELEASE##*.} == "04" || ${DISTRO_RELEASE##*.} > "04") ]]; then DISTRO_PHP_VERSION="7.0"; fi
```
.
.
**Second Method to Remove Bug:** 
Changed _-ge_ in line 249 by separate _==_  and _>_  statements. 
Seems == and > operand can compare _decimal/floating point numbers_, while _-ge_ and _>=_ cannot.
This is much easier solution than the first method above.
```
#if [[ $DISTRO_RELEASE -ge "16.04" ]]; then DISTRO_PHP_VERSION="7.0"; fi
if [[ $DISTRO_RELEASE == "16.04" || $DISTRO_RELEASE > "16.04" ]]; then DISTRO_PHP_VERSION="7.0"; fi
```
After above modification, script installed Web Portal

**Comment by jprochazka** [comment]
Thanks for pointing this oversight on my part out. You know how it goes when you get in a rush. Anyways I had to use a slightly different method to fix this.

`if [ `bc -l <<< "$DISTRO_RELEASE >= 16.04"` -eq 1 ]; then DISTRO_PHP_VERSION="7.0"; fi`

I used bc to compare the decimals being bash is not capable of comparing decimals. Your solution works in your case being your version, 16.04, matches `"16.04"` however being bash does not understand decimals this, `$DISTRO_RELEASE > "16.04"` basically does a string comparison and not a mathematical equation since bash does not know what to do with a number with a decimal in it.

Commit: 0ebc06ac5a9c5be52ee18deb3c028e760d8c9be4

**Comment by abcd567a** [comment]
Thanks Joe for removing the bug.

If I remember correctly, I have tried to use bc on the Pi2/Pi3 version of Ubuntu 16.04 Xenial, and got responce "command not found".

It is therefor advisable to add following line also:

CheckPackage bc

**Comment by abcd567a** [comment]
Tested on fresh install of Ubuntu 16.04 Xenial for **Pi2/Pi3**, worked like charm. Installed dump109p-mutability, all data feeders (piaware, planefinder, flightradar24, and adsbexchange), and Web Portal successfully.

Thanks Joe, Well done!!!
