### ISSUE TITLE
Login change in new 2.6

### ISSUE THREAD

**Issue by slookabill** [jprochazka/adsb-receiver#359]
Did the login username/password change in 2.6? I'm replacing my old SD card, and doesn't seem to login with a clean install and the password that's listed in the wiki.

**Comment by jprochazka** [comment]
The default password should still be adsbreceiver. Check if it is raspberry incase for some reason it did not change from the default Raspbian password when it was setup. The login should be pi. I will look into the matter first thing when I wake up in the morning.

**Comment by jprochazka** [comment]
You are right. The password "adsbreceiver" was not set on the images. Please use the default Raspbian image password "raspberry" for now. I will work on new images containing the proper password as documented which will also contain a couple bug fixes which don't effect the image release but may as well be added at that time.
