### ISSUE TITLE
Version 2.6 Mutab Image Issue

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#360]
v2.6 Mutability stretch lite image downloaded at 11:00hrs utc 26/10/2017
[https://github.com/jprochazka/adsb-receiver/releases/download/v2.6.0/adsb-receiver_2.6.0_dump1090-mutability_raspbian-stretch-lite.zip](url)
Image written to card, card inserted into Raspberry pi 2 .
System did not boot.
Downloaded and installed  v2.5 from image, no problems experienced.

Note : Welcome back Joe.

**Comment by jprochazka** [comment]
Did you try and rewrite the image in case something screwed up during the write?

**Comment by jprochazka** [comment]
Haven't heard back chalking it up to a bad write. Feel free to reopen this issue if the problem exists still.
