### ISSUE TITLE
ADSB Exchange bad MLAT-Client version

### ISSUE THREAD

**Issue by superg3** [jprochazka/adsb-receiver#361]
Hi,
We noticed in the installation script the MLAT-Client version installed is 0.2.9 and for some reason it does not sync/work with the MLAT server.
The mlat-client version that seems to be more stable is 0.2.6 .
Please, could you modify the installation script to install  0.2.6 version?
Thanks in advance.
Marcos L.

**Comment by jprochazka** [comment]
Sorry about that I have been away for a bit and it was my understanding via issues opened here that ADS-B Exchange was now using 0.2.9. I have reverted this change and once again by default 0.2.6 is installed. If for some reason you wish to use a different version you can set it in the vatiables.sh file.

commit e2ff3c9a7de913851b16c63234ad8878be5e45f4
