### ISSUE TITLE
Fresh install 2.6 image - dump1090 access denied

### ISSUE THREAD

**Issue by totalhavoc** [jprochazka/adsb-receiver#363]
I just installed 2.6.0 fresh and when Dump1090-Mutability starts I get the following errors in the log:

Mon Oct 30 13:33:53 2017 EDT  dump1090-mutability v1.15~dev starting up.
Using sample converter: UC8, integer/table path
Found 1 device(s):
0: unable to read device details
usb_open error -3
Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules
Error opening the RTLSDR device: Permission denied

**Comment by totalhavoc** [comment]
Solved it with the following:

sudo wget -O  /etc/udev/rules.d/rtl-sdr.rules "https://raw.githubusercontent.com/osmocom/rtl-sdr/master/rtl-sdr.rules"

sudo reboot

**Comment by jprochazka** [comment]
Added with commit e9dc4d63328e997c7bf9b9206cda3069645c83c9.
Thanks for the report and fix.

**Comment by totalhavoc** [comment]
SCX77 in the forums is the one that gets the fix credit
