### ISSUE TITLE
Unable to SSH to version 2.6.0

### ISSUE THREAD

**Issue by idobraca** [jprochazka/adsb-receiver#364]
For me on latest version 2.6.0 no accessible ports to SSH/telnet are opened.

**Comment by sipe** [comment]
Create empty file named ssh in boot partition.

https://www.raspberrypi.org/blog/a-security-update-for-raspbian-pixel/

**Comment by totalhavoc** [comment]
Or use "sudo raspi-config" and set ssh to enabled

**Comment by jprochazka** [comment]
Thanks for pointing this out I will be sure to add the file to the soon to be coming v2.6.1 release. This goes hand in hand with the default raspberry password change which I apparently, mistakenly, stripped out of the image build script...
