### ISSUE TITLE
EXT4-fs Error

### ISSUE THREAD

**Issue by estruble** [jprochazka/adsb-receiver#366]
Getting the same error on 2 different devices and on both dump1090-fa and dump1090-mutability:
[1396.334746] EXT4-fs error (device mmcblk0p2): ext4_journal_check_start:56 Detected aborted journal

Any suggestions?

**Comment by jprochazka** [comment]
Same SD card though I take it? The "device mmcblk0p2" is your SD card. Many times this message means your SD card has corrupt or bad sectors and may be about to die. You can try to run `fsck` which _might_ fix things in the mean time.

_Marked as invalid due to this being a hardware issue._

**Comment by estruble** [comment]
Thanks I’ll look into the SD card. I seam to be eating a few of them lately. 

Eric

Sent via T-Mobile iPhone
