### ISSUE TITLE
New install 2.6.0, ADS-B graphs not created 

### ISSUE THREAD

**Issue by radumalica** [jprochazka/adsb-receiver#367]
After installation, ADS-B graphs are not showing anything, because the scripts cannot import python module dump1090.py. I don't have the exact error now, but this is 100% it.

The rest of the graphs are working fine (cpu, memory, i/o etc)

**Comment by miloit** [comment]
Same here See issue#374

**Comment by jprochazka** [comment]
I cannot recreate the issue. However, there have been many bug fixes committed to the repository since this issue was opened. You may want to check that dump1090.py in fact exists within the directory ~/adsb-receiver/portal/graphs/.
