### ISSUE TITLE
2.6.0 image is just a plain raspbian, nothing preconfigured

### ISSUE THREAD

**Issue by radumalica** [jprochazka/adsb-receiver#368]
Just installed the 2.6.0 image, should be ready configured but the /root directory does not contain any adsb-receiver folder. You need to perform the quick install guide, get it from GIT, run install.sh and so on. Basically what you receive in 2.6.0 image is just raspbian jesssie and that's it.

**Comment by jprochazka** [comment]
check the pi users home directory not roots.
/home/pi/adsb-receiver
