### ISSUE TITLE
Error in syslog

### ISSUE THREAD

**Issue by Calimerorulez** [jprochazka/adsb-receiver#371]
Hi,

I encounter this error every 30 seconds in /var/log/syslog and on the console of my RPi 3:

```
Nov 27 10:40:53 raspberrypi rc.local[512]: Traceback (most recent call last):
Nov 27 10:40:53 raspberrypi rc.local[512]:   File "/home/pi/adsb-receiver/build/portal/python/maintenance.py", line 35, in <module>
Nov 27 10:40:53 raspberrypi rc.local[512]:     while true:
Nov 27 10:40:53 raspberrypi rc.local[512]: NameError: name 'true' is not defined
Nov 27 10:41:15 raspberrypi rc.local[512]: usage: mlat-client [-h]
Nov 27 10:41:15 raspberrypi rc.local[512]:                    [--input-type {auto,radarcape,beast,avrmlat,dump1090,sbs,radarcape_gps,radarcape_12mhz}]
Nov 27 10:41:15 raspberrypi rc.local[512]:                    --input-connect INPUT_CONNECT [--results RESULTS]
Nov 27 10:41:15 raspberrypi rc.local[512]:                    [--no-anon-results] [--no-modeac-results] --lat LAT --lon
Nov 27 10:41:15 raspberrypi rc.local[512]:                    LON --alt ALT [--privacy] --user USER [--server SERVER]
Nov 27 10:41:15 raspberrypi rc.local[512]:                    [--no-udp]
Nov 27 10:41:15 raspberrypi rc.local[512]: mlat-client: error: argument --lat: expected one argument
```

**Comment by Calimerorulez** [comment]
Found one solution for the mlat-client errors.

I added my latitude after --lat  and my longitude after --lon in /home/pi/adsb-receiver/build/adsbexchange/adsbexchange-mlat_maint.sh

Apparently, the lat/lon isn't inserted when the script is generated?

**Comment by jprochazka** [comment]
I merged a pull request addressing issues with the maintenance script tonight, You can either pull the changes using Git or overwrite the file /home/user/adsb-receiver/build/portal/python/maintenance.py with the contents of the file found in the master branch. If you are still encountering issues with maintenance let me know so I can address any further issues before a v2.6.1 release.

https://raw.githubusercontent.com/jprochazka/adsb-receiver/master/build/portal/python/maintenance.py

Thanks to @ttsak for the pull request addressing these issue.
Pull request #376 is where the changes were merged from and can be viewed.
