### ISSUE TITLE
New install problem - 2 issues 1) no ssh 2) no udev rules created

### ISSUE THREAD

**Issue by stevenflang** [jprochazka/adsb-receiver#373]
Fresh install today of both images available for pi 

1) ssh was not enabled by default 

2) image adsb-receiver_2.6.0_dump1090-mutability_raspbian-stretch-lite.img
Only one I tried .. did not create udev rules 

Noted the following in /var/log/dump1090-mutability.log

---------Cut---------------------
Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules
Error opening the RTLSDR device: Permission denied
Sat Dec  2 11:44:08 2017 EST  dump1090-mutability v1.15~dev starting up.
Using sample converter: UC8, integer/table path
Found 1 device(s):
0: unable to read device details
usb_open error -3
Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules
Error opening the RTLSDR device: Permission denied
---------Cut---------------------

Bus 001 Device 005: ID 0bda: Realtek Semiconductor Corp. RTL2838 DVB-T
Bus 001 Device 004: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Manually Added :  /etc/udev/rules.d/rtl-sdr.rules

With the following below: 

-------
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2838", MODE:="0666"
------

rebooted ..

Working .

**Comment by anarchydude** [comment]
Check out this post by legendary user abcd567:

https://discussions.flightaware.com/t/when-is-stretch-coming-to-piaware-sd-card-image-version/25990/9

Similar issues with the USB dongle not connecting. Seems like Stretch is giving all feeder software a big PITA. SSH is not enabled by default anymore, but I did notice the stock image with the adsb-receiver project also did not have this enabled by default as well. Hope this helps!

**Comment by jprochazka** [comment]
Script now downloads the file rtl-sdr.rules from the rtl-sdr repository if it does not exist locally.
Fix thanks to abcd567's post which @anarchydude linked.
