### ISSUE TITLE
maintenance.py repeating errors

### ISSUE THREAD

**Issue by beeyev** [jprochazka/adsb-receiver#375]
![errors](http://armarium.org/u/2017/12/08/0a1c3696912237984a94a4d39b903a83.png)

**Comment by aldennisa15** [comment]
see https://github.com/jprochazka/adsb-receiver/issues/372

**Comment by ttsak** [comment]
To be fair the pull request that you refer to is from @mkrzysztofowicz !
My pull request was a minor edit on the documentation :)

**Comment by jprochazka** [comment]
Thanks to @mkrzysztofowicz then as well!

**Comment by jprochazka** [comment]
Appears to be working. There was also another issue I had to fix issues pertaining to the settings queries. At the same time I consolidated these queries and removed unnecessary database engine checks for them.

commit 677655ea1aab6fbc8b80fb4ff3fe75d668385288
