### ISSUE TITLE
dump1090 charts do not work, but I do not know how to troubleshoot.

### ISSUE THREAD

**Issue by liwanglin12** [jprochazka/adsb-receiver#377]
The problem seems to be on dump1090.py, but I did not find the call to this file. Can you give me some help?

**Comment by liwanglin12** [comment]
![dump1090-localhost-local_trailing_rate-1h](https://user-images.githubusercontent.com/10279535/34918432-5ff0be4e-f98d-11e7-9476-d68f4a0c85a2.png)

Now it's working, but Min / Max data is not normally ...

**Comment by willfrd** [comment]
I'm having the same problrm since a random time (7 AM) today with the dump1090, the system graphs are working ok, any fixes for this? thanks
![image](https://user-images.githubusercontent.com/20045335/35184431-a3cea37e-fded-11e7-9e48-dc1c8df40310.png)

**Comment by liwanglin12** [comment]
@willfrd I checked the source code to find Min / Max data seems to need at least 86400 seconds (one day) of data to be generated. So, in fact, my problem has been solved.

Your chart situation seems more like the collected failed to fetch dump1090 data, try to check the /run/dump1090-mutability folder json file generation?

**Comment by willfrd** [comment]
So I should delete the files in /run/dump1090-mutability @liwanglin12 ? (I'm sorry I'm a bit noob with this)

**Comment by liwanglin12** [comment]
@willfrd nope. My point is to see if dump1090 is still there to write the json format log file, if not, that's probably the reason.

**Comment by willfrd** [comment]
Ok, so in my stats.json, inside /run/dump1090-mutability I have this atm:
```
{
"latest":{"start":1516460003.0,"end":1516460003.0,"local":{"samples_processed":0,"samples_dropped":0,"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0],"strong_signals":0},"remote":{"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0]},"cpr":{"surface":0,"airborne":0,"global_ok":0,"global_bad":0,"global_range":0,"global_speed":0,"global_skipped":0,"local_ok":0,"local_aircraft_relative":0,"local_receiver_relative":0,"local_skipped":0,"local_range":0,"local_speed":0,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":0,"reader":0,"background":0},"tracks":{"all":0,"single_message":0},"messages":0},
"last1min":{"start":1516460003.0,"end":1516460003.0,"local":{"samples_processed":0,"samples_dropped":0,"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0],"strong_signals":0},"remote":{"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0]},"cpr":{"surface":0,"airborne":0,"global_ok":0,"global_bad":0,"global_range":0,"global_speed":0,"global_skipped":0,"local_ok":0,"local_aircraft_relative":0,"local_receiver_relative":0,"local_skipped":0,"local_range":0,"local_speed":0,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":0,"reader":0,"background":0},"tracks":{"all":0,"single_message":0},"messages":0},
"last5min":{"start":1516460003.0,"end":1516460003.0,"local":{"samples_processed":0,"samples_dropped":0,"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0],"strong_signals":0},"remote":{"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0]},"cpr":{"surface":0,"airborne":0,"global_ok":0,"global_bad":0,"global_range":0,"global_speed":0,"global_skipped":0,"local_ok":0,"local_aircraft_relative":0,"local_receiver_relative":0,"local_skipped":0,"local_range":0,"local_speed":0,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":0,"reader":0,"background":0},"tracks":{"all":0,"single_message":0},"messages":0},
"last15min":{"start":1516460003.0,"end":1516460003.0,"local":{"samples_processed":0,"samples_dropped":0,"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0],"strong_signals":0},"remote":{"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0]},"cpr":{"surface":0,"airborne":0,"global_ok":0,"global_bad":0,"global_range":0,"global_speed":0,"global_skipped":0,"local_ok":0,"local_aircraft_relative":0,"local_receiver_relative":0,"local_skipped":0,"local_range":0,"local_speed":0,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":0,"reader":0,"background":0},"tracks":{"all":0,"single_message":0},"messages":0},
"total":{"start":1516460003.0,"end":1516460003.0,"local":{"samples_processed":0,"samples_dropped":0,"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0],"strong_signals":0},"remote":{"modeac":0,"modes":0,"bad":0,"unknown_icao":0,"accepted":[0,0]},"cpr":{"surface":0,"airborne":0,"global_ok":0,"global_bad":0,"global_range":0,"global_speed":0,"global_skipped":0,"local_ok":0,"local_aircraft_relative":0,"local_receiver_relative":0,"local_skipped":0,"local_range":0,"local_speed":0,"filtered":0},"altitude_suppressed":0,"cpu":{"demod":0,"reader":0,"background":0},"tracks":{"all":0,"single_message":0},"messages":0}
}
```
Which indicates thath there is no data been recorded at this time right?

**Comment by liwanglin12** [comment]
@willfrd I checked the start and end timestamps and they showed that your dump1090 data update time was a few minutes ago and did not look like have problem. I'm sorry I'm afraid I can not help you anymore.

**Comment by willfrd** [comment]
Yeah, I think its a problem of the mutability because the portal is not working either, I'll have a look by myself, thanks for trying anyways :-)

**Comment by liwanglin12** [comment]
If the portal does not work, check that YOUR_FEEDER_IP / dump1090 / data / stats.json is accessible because the chart data is from this url.

**Comment by willfrd** [comment]
Yeah, that works:
![](https://i.gyazo.com/cbe489b52ba0a7945a04ba63e2845733.png)

**Comment by willfrd** [comment]
Ok, fixed, something I had touched and I shoud't have, thanks again @liwanglin12 for the support :D

**Comment by liwanglin12** [comment]
@willfrd Congratulations! I've also successfully run dump1090 on my router, which will allow me to get a more northwest coverage.
