### ISSUE TITLE
Flightradar24 install causing downgrade of mutability 1.15-dev

### ISSUE THREAD

**Issue by anarchydude** [jprochazka/adsb-receiver#381]
I went to do a fresh install of the adsb-receiver package, and after installing 1.15-dev and moving on to the feeders, I chose to install FlightAware, and FR24. FlightAware installs with no issues. When moving to Flightradar, the installer prompt asks if I want to overwrite the config files, and looking up I saw that it was choosing to install mutability 1.14 over 1.15-dev. Has anyone else come across this issue? I was looking into the FR24 forums to see if there was any documented issues. 

System - RPi3 with Stretch Raspbian (both NOOBS install and preloaded install from here). Small note, SSH was not enabled by default unlike what the notation had stated in the preloaded image.

Update: This also happens on Jessie as well. Basically, even after a reinstall over top of 1.14 using install.sh, you get the three distance rings, and no colored planes, and no heywhatsthat borders.

![img_2451](https://user-images.githubusercontent.com/24593180/35071042-7023884c-fbad-11e7-845f-0f0a1c90f59e.jpg)

**Comment by anarchydude** [comment]
Solved, thanks to abcd567 over on the [FA24 discussion board](https://discussions.flightaware.com/t/ads-b-receiver-project-setup-scripts/17807/1677).

> Issue #1 is caused by recent change in fr24feed installation method by FR24. It now installs dump1090-mutability v1.14 alongwith fr24feed.

Do following:

`apt-cache policy dump1090-mutability`

If you see “Installed: v 1.14”, go ahead as follows:

`sudo dpkg --purge dump1090-mutability`

Now run script again and choose dump1090-mutability ONLY, and say no to everything else.

```
cd adsb-receiver
./install.sh
```

In addition, do a `sudo rm -rf /usr/share/dump1090-mutability` to wipe all data pertaining to dump1090. I did my web interface install separate after the dump1090 install, and also a separate install for the other feeders. Now, I've got a bing screen, with the heywhatsthat terrain rings, and colored planes! Time to clone the MicroSD card, and start customizing.

![77385541a85b4cc6a09cbbd44c4408d33f2270f4](https://user-images.githubusercontent.com/24593180/35122774-eb02a05a-fc6d-11e7-980d-1db950e2787b.png)

**Comment by jprochazka** [comment]
Reopening this issue to check if I need to modify things so FlightRadar24's installation script doesn't end up messing things up resulting in being an annoyance by downgrading and breaking things...

**Comment by jprochazka** [comment]
I just went through the install process and cannot recreate an instance where dump1090-mutability 1.15 has been over written by dump1090-mutability 1.14. There apparently was a fix issued by FlightRadar24 addressing a permissions issue. Maybe this was fixed at that time as well?

**Comment by anarchydude** [comment]
Thanks for taking a look! They must have fixed it then. I can try to fire up a setup on a spare Pi this week and see if that works.

**Comment by jprochazka** [comment]
If you wish let me know how it goes on your end just incase our install options differ causing an issue.
