### ISSUE TITLE
[Question] Dump 1090 portal issues

### ISSUE THREAD

**Issue by willfrd** [jprochazka/adsb-receiver#382]
Today I reinstalled the adsb-receiver into another micro sd card with the new version and I am having various issues:
![image](https://user-images.githubusercontent.com/20045335/35198769-ac604ad4-feeb-11e7-9923-e7c9680988ba.png)
1. Every time I ty to scroll on the map to zoom it instructs me to press control in order to zoom, which is preety annoying.
2. I don't get the country flags of the aircraft.
3. I don't get the aircraft silhouettes.
4. I copied the data I had of the graphs (from rrd) into /var/lib/collectd/rrd/ but I can't see the historic data from the previous instalation displayed in the performance graphs page.
5. If I want to deactivate the heywhatsthat maximum range circles in what file can I do that?

Is there a solution for this problems?

Thanks

**Comment by willfrd** [comment]
Ok, I managed to fix the first three issues by deleting the cache of the browser.
Is there any solution for the forth one?

**Comment by jprochazka** [comment]
4) Make sure rrd files were restored to the correct folder in /var/lib/collectd/rrd/ this should be a folder named localhost. You can confirm this by checking the folder for the newly created rrd files and placing them there

5) Delete the file /usr/share/dump1090-mutability/html/upintheair.json.

**Comment by jprochazka** [comment]
Marking this issue as closed.
Feel free to reopen it if the answers supplied did not resolve your issues.

**Comment by willfrd** [comment]
Its working now ☺️ cheers.
BTW, is there any plan of enabaling custom/further (2/3 years) Performance Graphs visualisation periods, or any way to do it by ourselfs?
