### ISSUE TITLE
Updated fr24 -> messed up everything

### ISSUE THREAD

**Issue by etamtlosz** [jprochazka/adsb-receiver#383]
Last week I've updated the fr24 feeder (sudo apt-get upgrade), and since then my receiver is not working.
- http://rpi3/dump1090.php shows the ever loading spinny.gif
- Performance graphs are at 0

**Comment by Nas87** [comment]
FR24 released version 1.0.19-6 which fixed the issue for me. I updated via apt-get update, upgrade.

**Comment by mgunther68** [comment]
Some people still may have to reset the permissions if the fr24feed had messed them up:

`~ $ sudo chown -R dump1090:nogroup /run/dump1090-mutability`

**Comment by jprochazka** [comment]
OK I am getting ready to look into this just need to set up a test device...

Is this related to another post I saw where it seems, so I am guessing, Flightradar24 is once again exploring the option of installing their own version of dump1090-mutability in this case an older 1.14 version of dump1090-mutability?

**Comment by adsbxchange** [comment]
We also encountered this issue with the multi feed images. Every feeding site is trying to take over the SDR and the dump1090 directory.

**Comment by jprochazka** [comment]
Just tested this out. Installing dump1090-mutability, fr24feed, and the portal and can confirm as @Nas87 reported this has been fixed by FlightRadar24. Also dump1090-mutability 1.15 was not replaced by dump1090 1.14.

**Comment by laferrierem** [comment]
My FlightRadar24 stopped on two Pi's both around late January early February. When I run the script to upgrade I get the following: "It appears that all the optional feeders available for installation by this script have been installed already." Everything else functions and feeds fine except FR24. Is this part of the same issue?

**Comment by adsbxchange** [comment]
Possibly. However I believe that FR24 pushed an update the broke feeders. You may need to just re-image or reinstall FR24.
