### ISSUE TITLE
website registration - mail() function disabled

### ISSUE THREAD

**Issue by etamtlosz** [jprochazka/adsb-receiver#384]
Hey Joe,
Awesome news, it's good to see that the project and website is alive.
Registration on the website is not working 100%, because the mail() function is disabled.

**Comment by jprochazka** [comment]
Fixed multiple issues pertaining to portal emails.

- Token column in the administrators table was not being created.
- Postfix installation was removed from the scripts at some point.
- New random string generator function created to replace old one.

commit 7a30480044d79d5fdeafa22259755515cfa49d00
