### ISSUE TITLE
getting too many redirects error on v2.6.1

### ISSUE THREAD

**Issue by house2001** [jprochazka/adsb-receiver#387]
Getting a too many redirects error (in multiple browsers), after the latest upgrade to v2.6.1. I'm sure it's a simple config change. Anyone have ideas on what could be causing this?

**Comment by jprochazka** [comment]
Sounds like for some reason the install script did not update the version in either your xml file or MySQL/MariaDB/SQLite database. If you are running a lite install of the portal edit the proper xml file which contains the portal data.
`sudo nano /var/www/html/settings.xml`
Change the version to 2.6.0.
```
<setting>
    <name>version</name>
    <value>2.6.1</value>
</setting>
```
If using MySQL or MariaDB with the advanced portal features update the database by using the following command.

`mysql -u<USER_NAME> -p<USER_PASSWORD> <DATABASE_NAME> -e "UPDATE adsb_settings SET value =  '2.6.1' WHERE name = 'version'";`

SQLite use the following command:

`sudo sqlite3 /var/www/html/data/portal.sqlite "UPDATE adsb_settings SET value =  '2.6.1' WHERE name = 'version'"`

**Comment by house2001** [comment]
Thanks, Joe. This works!

And a special thanks for all you're doing for the community here. It's much, much appreciated!
