### ISSUE TITLE
latest FA download

### ISSUE THREAD

**Issue by orionjb2001** [jprochazka/adsb-receiver#392]
Hi,

Just setting up some new cards, downloaded, extracted and installed the FA version.  All went well but in the portal, max distance image is not showing, all others are showing ok??

**Comment by jprochazka** [comment]
By max distance are you talking about the heywhatsthat.com range rings? If so try to regenerate the panorama on heywhatsthat.com and use the new panorama id just in case the old one has expired and is no longer available.

**Comment by orionjb2001** [comment]
Hi Joe,

No, not heywhatsthat ring, it is the graph for max distance.

 

Jeff

**Comment by jprochazka** [comment]
I have to do an install of dump1090-fa to check if the AirSpy Mini will work properly with it at that time I will look into this and report back if not tonight Sunday being tomorrow is D&D night and I will be busy then. :)

**Comment by jprochazka** [comment]
I am going to look into this tonight on Raspbian Stretch. If I am unable to find anything can you give me more information such as the operating system and its version? This information helps a lot and saves me time when trouble shooting being I am not having to test things out on multiple OSs/Versions.

**Comment by orionjb2001** [comment]
Joe, where do I find what version of the OS I am working, I believe the operating system is as per your git download, what ever that sets it at.  I use naked MSD cards when setting up your version mutability.

**Comment by jprochazka** [comment]
If it is one of the images I have made available for download it is Rasbian. Since v2.6.0 they have been based on Stretch. Pre v2.6.0 they were based on Jessie. If you did not use one of the images available for download and installed things from scratch.

`cat /etc/os-release`

Should give you your answer.

**Comment by orionjb2001** [comment]
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"

**Comment by jprochazka** [comment]
The scrcipts only place the heywhatsthat.com rings. The normal circular rings are part of the dump1090 installation are placed by dump1090-mutability and/or dump1090-fa. If I can pin point an issue I will be more than happy to open an issue on either repository.

Anyways I am trying to work through a few issues posted here with the code released in the master branch and so I can get v2.6.2 out the door. If I run into the same issue will post it where needed.

**Comment by orionjb2001** [comment]
Keep up the great work Joe :)

**Comment by jprochazka** [comment]
related issue?
issue #406

**Comment by orionjb2001** [comment]
Same issue.  First notification of the problem in the early stages. :)

**Comment by orionjb2001** [comment]
Current versions all correct :)
