### ISSUE TITLE
Restore graph and data after crash ?

### ISSUE THREAD

**Issue by disquette38** [jprochazka/adsb-receiver#393]
Hey Joe,
My Raspberry has just crashed, I just rebuild my station with the last maj v2.6.1 it's all OK. 
Now I would like to reintegrate the history of the graphs but that gives nothing (no history)
I do not use SQL database. I back up the folders automatically:
Graph Data
/ Var / lib / collectd / rrd /

XML & SQLite Portal Data
/ var / www / html / data / except for settings.xml

by restoring the files below I can not find the history of the two years :(
How to do thank you !!!

**Comment by jprochazka** [comment]
If you backed up the rrd database files using the backup utility you should have ended up with a file named adsb-receiver_data_<DATE_OF_BACKUP>.tar.gz file. If you did you should be able to restore things by running the following commands within the directory you placed the backup archive.

```
tar -vzxf adsb-receiver_data_<DATE_OF_BACKUP>.tar.gz
sudo cp var/lib/collectd/rrd/ /var/lib/collectd/rrd/
```

If you backed up the rrd files manually...

`sudo cp <PATH_TO_BACKUP_RRDS>* /var/lib/collectd/rrd/localhost/`

**Comment by disquette38** [comment]
Thank you for your answer, I'm using your backup script which is in the folder /home/pi/adbs/tools/portal_backup.sh. Everything works fine every day, but when I restore the data by the commands:
 1- tar -vzxf adsb-receiver_data_ <DATE_OF_BACKUP> .tar.gz
2- sudo cp var / lib / collectd / rrd / / var / lib / collectd / rrd /, I do not find the history of the measures idem after a reboot, do I have to launch other commands?

**Comment by disquette38** [comment]
For your information, the backup script is running every day at 4am. The data is in portal version 2.5, while I try to reload with the new version 2.6.1, is this the origin of the problem?

**Comment by disquette38** [comment]
This is great news, and it will make it easier to restore and especially not lose data and graphs.
Do you have an idea for the commands rrdtool to backup the data to XML, I managed to repair the micro sd (provisionally)

**Comment by jprochazka** [comment]
This should do the trick:
`rrdtool dump /path/to/rrdfile.rrd /path/to/backup.xml`

**Comment by disquette38** [comment]
I did this in the / var / lib / collectd / rrd / localhost / dump1090-localhost folder
**for f in *.rrd; do rrdtool dump ${f} > ${f}.xml; done**
but I would like to make all the folders and sub folder from / var / lib / collectd / rrd / localhost /

**Comment by jprochazka** [comment]
This is not tested and written here first...
```
for RRD_FILE in `find . -type f -name "*.rrd"`
do
    XML=`echo $RRD_FILE | sed 's/.rrd//g'`
    rrdtool dump $RRD_FILE > $XML.xml
done
```
Currently working on the v2.6.2 release this evening so have not have time to test it.

**Comment by disquette38** [comment]
It is functional for the creation of rdd files for each folder, I will write directly on my synology to avoid the corruption of the micro SD

**Comment by jprochazka** [comment]
So I take it the dump/restore worked? If so good to hear. Will be sure to adjust the backup script to use said method from now on if so.

**Comment by disquette38** [comment]
With a compression because the size is much larger, I was able to restore the graphs and data on my new raspberry

**Comment by disquette38** [comment]
With a compression because the size is much larger, I was able to restore the graphs and data on my new raspberry

**Comment by jhonnymonclair** [comment]
Hi Joe,
I've written a script just for the purpose, maybe it can be useful meanwhile backup/restore functions are better integrated in future releases...I hope you don't mind about it, feel free to copy or modify as you like.

[backman.sh.txt](https://github.com/jprochazka/adsb-receiver/files/2042869/backman.sh.txt)

**Comment by disquette38** [comment]
Hi jhonnymonclair
Thank you for the script, I like it. I will modify it to make it work manually with a scheduled task.
Thank

**Comment by disquette38** [comment]
if error `/bin/bash^M:` bad interpreter: No such file or directory -> `sed -i -e 's/\r$//' backman.sh`

**Comment by jprochazka** [comment]
The backup script has been fixed.
I will be working on a restore option for 2.7.0 next.

BTW Thanks @jhonnymonclair for the script. I used a somewhat modified version of what you created to fix the backup process in my backup script. I am sure it will come in useful when working on the restore script as well.
