### ISSUE TITLE
Mapzen close down services

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#397]
https://mapzen.com/blog/shutdown/

**Comment by jprochazka** [comment]
I have been wondering if this was what happened. I was unable to log into the developer side of the site for awhile now. I will be removing any Mapzen scripting shortly.

**Comment by jprochazka** [comment]
Explains why I could not log into the developer side of the site to get new keys last month. Anyways removed Mapzen questions and variables in commit f8c0e7c1bc011fbea0d25b4438fb661e27053c78.
