### ISSUE TITLE
Muttability 1.15 error error: cannot open .git/FETCH_HEAD: Permission denied

### ISSUE THREAD

**Issue by orionjb2001** [jprochazka/adsb-receiver#398]
getting this error when doing a install upgrade;

error: cannot open .git/FETCH_HEAD: Permission denied

**Comment by phg2k** [comment]
same here

**Comment by jprochazka** [comment]
I have not had any issues pushing or pulling to the repository. Out of curiosity I have noticed on my home network since switching providers that my router assigns an IPv6 address to my machines. When this would happen running something as simple as `sudo apt update` I would see in the output an IPv6 address outputted as if it was trying to use IPv6 to download the update. After awhile it would I am guessing time out and switch to IPv4 which would download said update with no problem at least until the next request is made then it would stall on the IPv6 address again.

To resolve the problem I disable IPv6 DHCP in my router and had no issues since.

If you could take a screen shot or paste the output from your device here it would help.

**Comment by orionjb2001** [comment]
I just did an in place install, that fetch head has gone.  The only error in the muta process is still;

**_**dpkg-source --before-build dump1090
 fakeroot debian/rules clean
dh clean
dh: Compatibility levels before 9 are deprecated (level 8 in use)
   dh_testdir
   dh_auto_clean
dh_auto_clean: Compatibility levels before 9 are deprecated (level 8 in use)
        make -j1 clean
make[1]: Entering directory '/home/pi/adsb-receiver/build/dump1090-mutability/dump1090'
rm -f *.o compat/clock_gettime/*.o compat/clock_nanosleep/*.o dump1090 view1090 faup1090 cprtests crctests
rm: cannot remove 'anet.o': Permission denied
rm: cannot remove 'convert.o': Permission denied
rm: cannot remove 'cpr.o': Permission denied
rm: cannot remove 'cprtests.o': Permission denied
rm: cannot remove 'crc.o': Permission denied
rm: cannot remove 'demod_2400.o': Permission denied
rm: cannot remove 'dump1090.o': Permission denied
rm: cannot remove 'icao_filter.o': Permission denied
rm: cannot remove 'interactive.o': Permission denied
rm: cannot remove 'mode_ac.o': Permission denied
rm: cannot remove 'mode_s.o': Permission denied
rm: cannot remove 'net_io.o': Permission denied
rm: cannot remove 'stats.o': Permission denied
rm: cannot remove 'track.o': Permission denied
rm: cannot remove 'util.o': Permission denied
rm: cannot remove 'view1090.o': Permission denied
rm: cannot remove 'dump1090': Permission denied
rm: cannot remove 'view1090': Permission denied
rm: cannot remove 'cprtests': Permission denied
Makefile:63: recipe for target 'clean' failed
make[1]: *** [clean] Error 1
make[1]: Leaving directory '/home/pi/adsb-receiver/build/dump1090-mutability/dump1090'
dh_auto_clean: make -j1 clean returned exit code 2
debian/rules:30: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2_**

  Installing the dump1090-mutability package...**

(Reading database ... 43255 files and directories currently installed.)
Preparing to unpack .../dump1090-mutability_1.15~dev_armhf.deb ...
Unpacking dump1090-mutability (1.15~dev) over (1.15~dev) ...
Setting up dump1090-mutability (1.15~dev) ...
Enabling lighttpd integration..
already enabled
Run "service lighttpd force-reload" to enable changes
Restarting lighttpd..
Processing triggers for systemd (232-25+deb9u2) ...

  Checking that the dump1090-mutability package was installed properly...
  Creating package archive directory...

mkdir: cannot create directory ‘/home/pi/adsb-receiver/build/dump1090-mutability/package-archive’: Permission denied

  Moving the dump1090-mutability binary package into the archive directory...

cp: target '/home/pi/adsb-receiver/build/dump1090-mutability/package-archive/' is not a directory

:)

**Comment by jprochazka** [comment]
Delete the directory dump1090-mutability directory as a sudo user and try again.
`sudo rm -rf ~/adsb-receiver/build/dump1090-mutability`

I think I typed the last comment into the wrong issue...

**Comment by orionjb2001** [comment]
Oh 1 other thing I have noted, during the process, it states it has increased the maximum range to 360nm to match some cases of possible detections, however when going through the /etc/default/dump1090-mutability, I noted the maximum was still set at 300NM.  Now not sure if that is where that figure lies in the system but it is the only spot I can see a reference to that maximum range, I have manually up'd it to 360NM.. Is this the place where that data lies??

**Comment by jprochazka** [comment]
Honestly this was something brought over from romeo-golf's fork which I did not pay attention to. I will look into why it is not being set proper in v2.6.2 at the latest 2.7.0 which shouldn't be that far off.

**Comment by orionjb2001** [comment]
Fetch head??   no all good, hasn't appeared again.

**Comment by phg2k** [comment]
Hi!
Unfortunatelly, I still get the HEAD-error:

 Preparing the dump1090-fa Git repository...

  Entering the dump1090-fa git repository directory...
  Updating the local dump1090-fa git repository...

error: kann '.git/FETCH_HEAD' nicht öffnen: Keine Berechtigung

  Building and installing the dump1090-fa package...

  Building the dump1090-fa package...
