### ISSUE TITLE
unary operator expected

### ISSUE THREAD

**Issue by pbriesch** [jprochazka/adsb-receiver#401]
Hi,

I'm getting this error message:

 **/home/pi/adsb-receiver/bash/portal/install.sh: line 269: [: ==: unary operator expected**

`
Setting up the ADS-B Receiver Project Portal...
  ------------------------------------------------------------------------------

  Installing packages needed to fulfill dependencies...

  Checking if the package lighttpd is installed... [OK]
  Checking if the package bc is installed... [OK]
  Checking if the package php7.0-cgi is installed... [OK]
  Checking if the package php7.0-json is installed... [OK]
  Checking if the package collectd-core is installed... [OK]
  Checking if the package rrdtool is installed... [OK]
/home/pi/adsb-receiver/bash/portal/install.sh: line 269: [: ==: unary operator expected
  Checking if the package postfix is installed... [OK]
  Checking if the package libpython2.7 is installed... [OK]
  Checking if the package php7.0-xml is installed... [OK]
  Reloading Lighttpd...`

**Comment by jprochazka** [comment]
All fixed.
