### ISSUE TITLE
Finnisching Portal Install not possible

### ISSUE THREAD

**Issue by bdcinside** [jprochazka/adsb-receiver#403]
Hello Guys (and Girls),

I cannot complete the portal installation. Did the installation on a old very used Raspian Stretch Lite and after that on a clean fresh installed full Raspian stretch.

Installation went fine every time. No errors at all.

But it seems as the php-files are not working. Can anybody acknowledge that?

Error after Step 4:
![unbenannt](https://user-images.githubusercontent.com/37751150/37868157-a727f0f2-2fa2-11e8-8f04-c1f4298901ba.PNG)

Any guess on how solving that is welcome.

Regards
Dirk

**Comment by disquette38** [comment]
Hello, 
sudo service lighttpd status ?, it's running ?
sudo service lighttpd start

**Comment by bdcinside** [comment]
`● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2018-03-24 17:50:26 UTC; 3h 0min ago
 Main PID: 18681 (lighttpd)
   CGroup: /system.slice/lighttpd.service
           ├─18681 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─18698 /usr/bin/php-cgi
           ├─18702 /usr/bin/php-cgi
           ├─18703 /usr/bin/php-cgi
           ├─18704 /usr/bin/php-cgi
           └─18705 /usr/bin/php-cgi

Mär 24 17:50:26 raspberrypi lighttpd[18681]:         LANG = "en_GB.UTF-8"
Mär 24 17:50:26 raspberrypi lighttpd[18681]:     are supported and installed on your system.
Mär 24 17:50:26 raspberrypi lighttpd[18681]: perl: warning: Falling back to the standard locale ("C").
Mär 24 17:50:26 raspberrypi lighttpd[18681]: perl: warning: Setting locale failed.
Mär 24 17:50:26 raspberrypi lighttpd[18681]: perl: warning: Please check that your locale settings:
Mär 24 17:50:26 raspberrypi lighttpd[18681]:         LANGUAGE = (unset),
Mär 24 17:50:26 raspberrypi lighttpd[18681]:         LC_ALL = (unset),
Mär 24 17:50:26 raspberrypi lighttpd[18681]:         LANG = "en_GB.UTF-8"
Mär 24 17:50:26 raspberrypi lighttpd[18681]:     are supported and installed on your system.
Mär 24 17:50:26 raspberrypi lighttpd[18681]: perl: warning: Falling back to the standard locale ("C").  `

**Comment by jprochazka** [comment]
How old an install?
Better yet can you take a look at lighttpd's error log and post any errors it has reported there?
`sudo nano /var/log/lighttpd/error.log`
BTW guy is fine not a gal. :)

**Comment by bdcinside** [comment]
Did a reinstall and then http://localhost/install. Provided all needed data. Same error. Lighttpd log says as folows:

`2018-03-26 04:55:42: (log.c.217) server started
2018-03-26 04:57:49: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 near ",": syntax error in /var/www/html/install/index.php:359
2018-03-26 04:57:49: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2018-03-26 04:57:49: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/html/install/index.php(359): PDO->prepare('CREATE TABLE ad...')
2018-03-26 04:57:49: (mod_fastcgi.c.2543) FastCGI-stderr: #1 {main}
2018-03-26 04:57:49: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/html/install/index.php on line 359
`

settings.class.php doesn't contain any settings from my input. So how can we fix it?

Regards Dirk

**Comment by jprochazka** [comment]
This looks like the SQLite issue for which a fix has been committed to the master branch and will be part of the upcoming v2.6.3.
