### ISSUE TITLE
wrong path for socat

### ISSUE THREAD

**Issue by jhonnymonclair** [jprochazka/adsb-receiver#404]
there is an error in last commit to adsbexchange-socat_maint.sh script,
it looks for socat under /usr/sbin but actually it is under /usr/bin,
at least on my raspbian stretch lite

**Comment by jprochazka** [comment]
Distribution name?
Distribution version?

Just curious because /usr/bin/socat has not been an issue yet with my ADS-B Exchange script from which I took the path and haven't heard any issues from.

https://github.com/jprochazka/adsb-exchange/blob/master/setup.sh

**Comment by jprochazka** [comment]
Yep you are right. Gotta love how some ditros place things here and others there. Will get this fixed ASAP.

**Comment by jprochazka** [comment]
Refer to #432.
