### ISSUE TITLE
autohide navbar - missing setting

### ISSUE THREAD

**Issue by jhonnymonclair** [jprochazka/adsb-receiver#405]
autohide navbar new feature on 2.62 doesnt work for me,
I've checked the file settings.xml, I can't find any reference to the setting.
I've tried also to delete all the files in folder /var/www/html/data, doing then
a fresh reinstall of the portal, unsuccessfully.

**Comment by jprochazka** [comment]
Damn nothing works when copying and pasting from issues into the things without testing. Honestly was added from a snippet from a follower here which was meant for a future release. Working on it now. The option may be removed if it takes more than a few minutes to fix being I really need to get 2.6.2 released...

**Comment by jhonnymonclair** [comment]
thanks very much Joe, I will wait for it, as for me actually the autohide was the most interesting
feature of the new release, most of times I use to check the portal by a tablet, so increased readability
is always welcome
