### ISSUE TITLE
1090 FA stream is broke

### ISSUE THREAD

**Issue by orionjb2001** [jprochazka/adsb-receiver#406]
I have been trying to set up the FA version, I noted a fetch head error during the 3.5.3  setup.  I am left with a page, showing flight details but no planes showing on map.  Also for what ever reason, it is not logging with FA, I do not get a new site ID. Now I have loaded the stock standard version from FA and works perfectly and get a new site id. 
![fa bug](https://user-images.githubusercontent.com/21165953/37880293-9c526d80-30d1-11e8-9394-413dc9f96799.jpg)

**Comment by orionjb2001** [comment]
Further, whilst the heywhatsthat data is in the right spot, the range rings are based over FA's headquarters in the USA.  I have seen this before years ago. During the install process, there was no requested input of the location via lat long, where the site was, as is in the mutability version.

**Comment by jprochazka** [comment]
Need some further information.
Operating system distribution, version...

Once I have said information I can troubleshoot things.
FYI there are issues with Ubuntu 17.10 and PiAware.

**Comment by orionjb2001** [comment]
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian

So...... there is a problem with the FA branch at the moment??  But great to see you have raised the issue with FA. Do you think the problems with Ubutnu and PiAware will be overcome??  I believe David Baxter said there was an upgrade coming with PiAware in relation to the new model PI3 B+ and its, inabliilty at the moment to boot with current PiAware software.

**Comment by jprochazka** [comment]
PiAware will not build on Ubuntu 17.10. What you are running there should no problem. Wo9rking through making sure my socat path is correct and will look into if the ring issue has anything to do with the code found here which I highly doubt it does.

**Comment by orionjb2001** [comment]
I was wondering, to overcome the current issue, of whether you can update a Flightaware version, which is working, with your upgrades.  First thing I noted was that to start with, you have 2 directories, piaware(FA)  and ADSB-receiver after trying to do that.

**Comment by jprochazka** [comment]
Question. Did you, after claiming your receiver on flightaware.com, set you position via their website? If you log in and look at your receiver settings on their page you should see an option to set your receivers position. There is no way in dump1090-fa I can via the scripts allow you to set you position during setup. You must do so via their website.

**Comment by orionjb2001** [comment]
I thought of that, but you cant do that until you can claim your new PiAware Ground Station and presently using the FA version, their system is not picking up the new feed.  Catch 22. I have sent an email re their auto system not working, but have heard nothing back yet.  I have even tried different PI's for the setup, to see if different mac's would trigger being given a new station, but no.  Do the same thing with the mutability version, new station each time you re do a card.

**Comment by jprochazka** [comment]
My experience dump1090-fa unlike dump1090-mutabilty needs its postion setup on their website. I am gussing this is your issue and out of my hands. Might want to try asking on their forum. There are many people there willing to point you into the right direction if in fact you are unable to set your position.

https://discussions.flightaware.com/c/flightaware/ads-b-flight-tracking

**Comment by orionjb2001** [comment]
Update per Sunday.  Downloaded FA image, format sd, load image, raspi config.

Installing  got to portal install, with a fatal error here:
Installing packages needed to fulfill dependencies...

 ##### Checking if the package lighttpd is installed... [OK]
  Checking if the package bc is installed... [OK]
  Checking if the package php7.0-cgi is installed... [OK]
  Checking if the package php7.0-json is installed... [OK]
  Checking if the package collectd-core is installed... [OK]
  Checking if the package rrdtool is installed... [OK]
  Checking if the package postfix is installed... [NOT INSTALLED]
  Installing the package postfix...

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package postfix is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'postfix' has no installation candidate

  Checking if the package postfix is installed...  [INSTALLATION ATTEMPT FAILED]
  Attempting to Install the package postfix again in 5 seconds (ATTEMPT 2 OF 5)...

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package postfix is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'postfix' has no installation candidate

  Checking if the package postfix is installed...  [INSTALLATION ATTEMPT FAILED]
  Attempting to Install the package postfix again in 5 seconds (ATTEMPT 3 OF 5)...

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package postfix is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'postfix' has no installation candidate

  Checking if the package postfix is installed...  [INSTALLATION ATTEMPT FAILED]
  Attempting to Install the package postfix again in 5 seconds (ATTEMPT 4 OF 5)...

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package postfix is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'postfix' has no installation candidate

  Checking if the package postfix is installed...  [INSTALLATION ATTEMPT FAILED]
  Attempting to Install the package postfix again in 5 seconds (ATTEMPT 5 OF 5)...

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package postfix is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'postfix' has no installation candidate


  INSTALLATION HALTED!
  UNABLE TO INSTALL A REQUIRED PACKAGE.
  SETUP HAS BEEN TERMINATED!

The package "postfix" could not be installed in 5 attempts.


    IMAGE SETUP HAS BEEN TERMINISTED. #########

**Comment by orionjb2001** [comment]
Ok..... 3rd attempt, got past the postfix glitch (had caps lock on after setting up heywhatsthat???))  anyway got through the whole FA set up, set up portal, still no planes showing in map, all currently tacked flights from site showing in FA table?????

**Comment by orionjb2001** [comment]
More info, Planefinder is working fine of that install and is showing the planefinder map and current tracked A/C.  Now this is interesting, the following script entered with the strange reply:

pi@raspberrypi:~/adsb-receiver $ sudo /etc/init.d/dump1090-fa restart
sudo: /etc/init.d/dump1090-fa: command not found
?????

**Comment by orionjb2001** [comment]
Got the 2.6.1 FA to work, with circles centred over me.  Haven't tried the 2 6 2 version but suspect it should be also ok :)
