### ISSUE TITLE
FC0012 tuner

### ISSUE THREAD

**Issue by Basti77** [jprochazka/adsb-receiver#407]
Hello, I may have found a solution for FC0012 tuner.
The USB stick must first be initialized to a different frequency <980Mhz, then you can switch to the 1090Mhz.
Under windows SDR# it works!
Is there a coder that could install this in dump1090-fa?

**Comment by jprochazka** [comment]
To request features to be added to dump1090-fa it is best to ask in the dump1090-fa repository. Modifications to dump1090-fa itself is beyond the scope of this project.

https://github.com/flightaware/dump1090
