### ISSUE TITLE
Plane Finder client to attach to IPv6 address

### ISSUE THREAD

**Issue by pbriesch** [jprochazka/adsb-receiver#408]
Hi,

is there a way to make the plane finder client that runs on port 30053 not only to attach to the IPv4 but also to the IPv6 adress(es)?

Thanks

**Comment by jprochazka** [comment]
This would be any issue you would need to address with the Planfinder developers. Everything on my end addresses outside resources using FQDN's. Honestly they might not be running IPv6 addresses. Not many people do yet...

**Comment by pbriesch** [comment]
Thanks for your reply.
