### ISSUE TITLE
Web Portal wlan0 & core temperature not working

### ISSUE THREAD

**Issue by benben8888** [jprochazka/adsb-receiver#416]
Hi,

I noticed that the bandwidth usage wlan0 no longer works. I am using nanopi m1 with Armbian Stretch. Updated version. I am using the TP-Link TL-WN725N (ifconfig shown : wlx7c8bca1f3ad1) USB Wifi Dongle and works well in performance graph (wlan0) previously, unfortunately now no longer work. Any way to fix it?

Another issue is core temperature also not shown in the graph. I look forward to receiving reply from you soon. Thank you.

**Comment by jprochazka** [comment]
Run the following command:
`ip address`
Make sure that the WiFi adapter does not have a goofy name other than wlan0.

If it differs you will need to add a line to /etc/collectd/collectds.conf which addresses this awkward named WiFi interface. Look for...
```
<Plugin "interface">
    ...
</Plugin>
```
Add a line much like the two found within this code reflecting the name your OS gave the adapter. You will then need to edit ~/adsb-receiver/build/graphs/ and change only the bold "wlan0" portion of the following line to reflect the goofy name your OS gave your adapter...

wlan0_graph ${DOCUMENTROOT}/graphs/system-$2-wlan0_bandwidth-$4.png /var/lib/collectd/rrd/$1/interface-**wlan0** "$3" "$4" "$5"

**Comment by jprochazka** [comment]
Oh forgot one step to try if you made said changes which _might_ help. In the administration area under settings click the system tab and click the wlan0 button and save the new setting.
