### ISSUE TITLE
Manually assign receivers to 1090 and 978

### ISSUE THREAD

**Issue by SoNic1967** [jprochazka/adsb-receiver#420]
In case that there are two receivers, one for decoding 1090MHz ADS-B and the second for decoding 978MHz UAT, provide option during installation to choose which one is used for 1090MHz (or 978MHz). 
This way, something like the FlightAware Pro Stick Plus, with integral 1090MHz filter, is not accidentally assigned to 978MHz.
Also it is useful for the case of identical receivers, but different serials, to know which antenna gets connected to what receiver. 
Serial number can be changed previously (rtl_eeprom for example) so selection can be done via serial number.

**Comment by jprochazka** [comment]
The option to assign receivers is made available when installing dump978 when dump1090 is already present. Please refer to this wiki page for more information:

https://github.com/jprochazka/adsb-receiver/wiki/Configuring-dump978
