### ISSUE TITLE
Setting up MySQL support after installation

### ISSUE THREAD

**Issue by donslice** [jprochazka/adsb-receiver#421]
Hello,

How can I set up MySQL support after I have already installed? I have attempted to run the installer again, but I am not given the option to supply MySQL information.

**Comment by jprochazka** [comment]
Deleting the following files from your existing lite installation should give you the option to install advanced features. Keep in mind you will loose any information saved to XML files which is what the lite version uses to store data. Essentially you will be starting from scratch except for system graphs which should remain in tact.

Delete `/var/www/html/classes/settings.class.php` then execute `install.sh` reinstall the portal and choose advanced features. Follow the instructions as you would a clean installation.
