### ISSUE TITLE
Core Temperature - 404 Not Found

### ISSUE THREAD

**Issue by ciprianxl** [jprochazka/adsb-receiver#425]
Hello. Good work on the script. Making it very easy for non-coding knowledge ADS-B enthusiasts.
I have one issue with the Graph page. The core temperature graph is missing. Instead i can only see the link "Core Temperature" which forwards me to a 404 -Not found page.

Gauge temperature is working on the system information page. OpiMonitor is working also.

Using OrangePi Zero

Thanks!

**Comment by jprochazka** [comment]
Please run...
`sudo bash /home/pi/adsb-receiver/graphs/make-collectd-graphs.sh 1h`
Do you receive an error when running the above command?

**Comment by jprochazka** [comment]
It looks as though on the Orange Pi Zero a line might need to be changed in /etc/collectd/collectd.conf. The line which looks like the following...
`        <Table "/sys/class/hwmon/hwmon0/temp1_input">`
Needs to look like?
`        <Table "/sys/devices/virtual/thermal/thermal_zone1/temp`
If I could get this confirmed by someone willing to help me out who owns an Orange Pi I can look into getting a fix in place. What I will need to figure out is how to detect if the script is running on an Orange Pi and if the above fix actually dose fix the CPU temperature issue.

**Comment by ciprianxl** [comment]
Hey. Sorry for not replying. I fried my opi zero last month. Just received a new one today. Will test soon and reply. Thanks for the support!

**Comment by jprochazka** [comment]
Not a problem thanks for the help!

**Comment by ciprianxl** [comment]
Hello,

> 
> It looks as though on the Orange Pi Zero a line might need to be changed in /etc/collectd/collectd.conf. The line which looks like the following...

Do you mean to nano the collectd.conf? I cannot find ` <Table "/sys/class/hwmon/hwmon0/temp1_input">` by giving the command `nano  /etc/collectd/collectd.conf `

Sorry, my coding skills are very low.

Also...

`
root@orangepizeroplus:~# sudo bash /home/pi/adsb-receiver/graphs/make-collectd-graphs.sh 1h
bash: /home/pi/adsb-receiver/graphs/make-collectd-graphs.sh: No such file or directory
`
Thank you!

**Comment by FeverBeaver** [comment]
Hi,

I'm coming a bit late but I may be of some help. I've installed the latest release (2.6.3) yesterday on an Orange Pi Zero, and can confirm the CPU temp has the same path than on a Raspi (/sys/devices/virtual/thermal/thermal_zone0/temp)
Therefore, I solved the missing temperature graph by modifying the install script that way:
in ~/adsb-receiver/bash/portal/graphs.sh
where 

```
# Raspberry Pi specific values.
if [[ "${HARDWARE_PLATFORM}" = "RPI" ]] ; then

```
I modified it to
`if [[ "${HARDWARE_PLATFORM}" != "CHIP" ]] ; then
`

and ran the installation script once more. It works, but I have to admit this may not be the most elegant workaround.

Hope this helps.

**Comment by ciprianxl** [comment]
Proper fix can be found in. https://github.com/jprochazka/adsb-receiver/issues/489#issuecomment-460439998

Many Thanks to [Joe](/jprochazka)!!
