### ISSUE TITLE
ADS-B Max Range Graph not working for some periods

### ISSUE THREAD

**Issue by vitaliy-sk** [jprochazka/adsb-receiver#426]
Thre is an issue with ADS-B Max Range Graph, it's working for Hourly \ Six Hours \ Daily but not showing any data with Weekly \ Monthly \ Yearly periods. 

<img width="606" alt="screen shot 2018-05-06 at 23 01 12" src="https://user-images.githubusercontent.com/2773025/39677330-b8eb904a-5181-11e8-9152-6f25fe7d4476.png">
<img width="805" alt="screen shot 2018-05-06 at 23 02 50" src="https://user-images.githubusercontent.com/2773025/39677331-bb3b660e-5181-11e8-8aea-6a4e2fc7693e.png">

Portal Version: 2.6.2
DB: SqlLite

**Comment by jprochazka** [comment]
Curious as to if you are running the fr24 feeder as well?
Could this be related to this issue?

#438

**Comment by vitaliy-sk** [comment]
@jprochazka yes, I use fr24 feeder

**Comment by jprochazka** [comment]
Out of curiosity if you shut down the fr24 feeder do things work normally again? This evening I will be setting up a test device running both the portal and fr24 to see if this in fact the cause of this issue.

**Comment by abcd567a** [comment]
I use FR24 feeder on my two Pis, but never faced this problem.

**Monthly Max Range graph: PI # 1**
![PI #1](https://user-images.githubusercontent.com/28452511/41812277-11dfd0c6-76ee-11e8-9480-2cf147c4fd80.png)



**Monthly Max Range graph: Pi # 2** (fresh install about 2 weeks ago)
![Pi #2](https://user-images.githubusercontent.com/28452511/41812284-337953c4-76ee-11e8-9bd8-14e07240ee0b.png)
