### ISSUE TITLE
Install on stretch, php7.0 package not found

### ISSUE THREAD

**Issue by MDA0803** [jprochazka/adsb-receiver#427]
Joe please add:
sudo apt update after OS update. 
Otherwise setup is cancelled after 5 unsuccessfull attempts to locate php7.0 package.
"sudo apt update" is solving this problem.
Thanks in advance

**Comment by jprochazka** [comment]
That is strange the apt update executed when the script is initially executeds should get all current packages. This package list should only become out dated when a new package is added to the Debian repository.

There is a check where if the apt update command was executed within the last 30 mins it skips this command. I just added a way to override this check by using either the -u or --apt-update flag when executing install.sh.

./install.sh --apt-update

commit 6bbae71eb9915148293d5e56164a3f4a96c146d8
