### ISSUE TITLE
broken ADSBexchange feeders .. again... 

### ISSUE THREAD

**Issue by adsbxchange** [jprochazka/adsb-receiver#432]
Not sure this guy may have changed it manually.

FYI: DO NOT CHANGE MLAT PORT.
[EDIT]

/usr/bin/mlat-client --privacy --input-type dump1090 --input-connect localhost:30005  [...... ] --server **feed.adsbexchange.com:31090** --noup  --results beast,connect,127.0.0.1:30104
    

https://www.adsbexchange.com/forum/threads/another-custom-feed-question.622187/

**Comment by adsbxchange** [comment]
figured it out ... looking for socat in sbin ...  for whatever reason it's not there .... /usr/bin/socat


pi@raspberrypi:~/adsb-receiver/build/adsbexchange $ ./adsbexchange-socat_maint.sh 
./adsbexchange-socat_maint.sh: 5: ./adsbexchange-socat_maint.sh: /usr/sbin/socat: not found
pi@raspberrypi:~/adsb-receiver/build/adsbexchange $ sudo apt-get install socat
Reading package lists... Done
Building dependency tree       
Reading state information... Done
socat is already the newest version (1.7.3.1-2+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
pi@raspberrypi:~/adsb-receiver/build/adsbexchange $ socat
2018/06/04 13:31:36 socat[3543] E exactly 2 addresses required (there are 0); use option "-h" for help
pi@raspberrypi:~/adsb-receiver/build/adsbexchange $ /usr/bin/socat
2018/06/04 13:31:43 socat[3546] E exactly 2 addresses required (there are 0); use option "-h" for help
pi@raspberrypi:~/adsb-receiver/build/adsbexchange $ /usr/sbin/socat
-bash: /usr/sbin/socat: No such file or directory
pi@raspberrypi:~/adsb-receiver/build/adsbexchange $

**Comment by jprochazka** [comment]
The script now checks that socat exists in either /usr/sbin or /usr/bin then places the proper path in the maintenance script. commit 0da0c7b3b6319a5c94106f98915779e11e5f1e54
