### ISSUE TITLE
AboveTustin screenshot is not correct with dump1090-fa

### ISSUE THREAD

**Issue by donslice** [jprochazka/adsb-receiver#433]
Screenshots with dump1090-fa are not correct - only show table of aircraft. No map.

https://twitter.com/AboveWaterford/status/1003662513899278336

**Comment by jprochazka** [comment]
This issue pertains to a third party application and should be posted to the AboveTustin issue tracker.

https://github.com/kevinabrandon/AboveTustin/issues
