### ISSUE TITLE
Who can i aktivate the Graphs? and where can i switch on MLT bye piaware?

### ISSUE THREAD

**Issue by Conan179** [jprochazka/adsb-receiver#434]
Hello. i have yesterysay install adsb-receiver for fr24 and flightaware.
I have 2 problems.
1. On my installation, the Graphs, https://camo.githubusercontent.com/5641b935c447ddb28ade377546df2a7e75339497/687474703a2f2f6173736574732e6a61636f6277616c6c2e6e6574646e612d63646e2e636f6d2f616473622d72656365697665725f6c6976655f64756d70313039302e706e67
are missing.
2. Where can i switch on MLT on piaware?
I have a pi2.
greetz conan

**Comment by jprochazka** [comment]
1) You should be able to change the map displayed on dump190-mutability by clicking the light blue icon like the one located in the corner of the screenshot you linked. If you are running dump1090-fa and I remeber right the icon should be about the same but smaller.

2) You can turn on PiAware MLAT by visiting their website and turning it on in your receiver profile.

**Comment by Conan179** [comment]
1. My problem was that the install.php has created a buggy mysql database and so the protal does not even start. With an older install.php I have created a running mysql database (/var/www/html/data/portal.sqlite) and copied them in purely. Dan ran the kommplette Protal, I could not say that it was because.

2. i have found ist, my error, im sorry.

I apologize for my bad English. I speak German and used Google Translate.

**Comment by jprochazka** [comment]
Not a problem no reason to appologize.

@vitaliy-sk posted a fix for SQLite installation I merged into the master branch today. Apparently something was messed up with the v2.6.2 SQLite option causing headaches. This might have been the problem you ran into.
