### ISSUE TITLE
Planefinder Client Version Update

### ISSUE THREAD

**Issue by abcd567a** [jprochazka/adsb-receiver#440]
Update required in file adsb-receiver/bash/variables.sh, as the latest Plane finder client version has changed from 3.7.40 to 4.1.1

pfclient_4.1.1_armhf.deb
pfclient_4.1.1_i386.deb

**Comment by jprochazka** [comment]
Thanks for pointing this out.
commit e473c1679da6dbf267c394fc7ad9357750789508
