### ISSUE TITLE
dump1090-fa version on i386

### ISSUE THREAD

**Issue by abcd567a** [jprochazka/adsb-receiver#442]
The file adsb-receiver/bash/variables.sh has following

# FlightAware PiAware
DUMP1090_FA_VERSION="3.5.1"
PIAWARE_VERSION="3.5.3"

This works OK on armh (RPi/OPi).

On Raspbian Stretch x86 on i386 computer the install fails. 

On i386, after building dump1090-fa, when script runs install command (dpkg -i ), it fails, saying it did not find the package dump1090-fa ver 3.5.1.

When I checked, found that the build pkg has actually built dump1090-fa ver 3.5.3, and then trying to install ver 3.5.1.

I then manually gave command dpkg -i to install dump1090-fa 3.5.3, and it was successfully installed.

**Comment by jprochazka** [comment]
Fixed in commit e2647fa2ad600996581e3467c77b3f19747d3205.
