### ISSUE TITLE
OpenSky Network Support

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#445]
This is a must add. They are advertising the project as a base install option. To automate the process to feed their service should be made a high priority.

https://opensky-network.org/community/projects/30-dump1090-feeder

**Comment by abcd567a** [comment]
This is a good and deserving enhancement. When I visited their site to install their feeder about 2 months ago, I noted their recommendation to use adsbreceiver image.

**Comment by abcd567a** [comment]
**OPEN-SKY FEEDER ON-LINE CHARTS**
.
![opensky-feeder charts -1](https://user-images.githubusercontent.com/28452511/41819634-be8507da-7791-11e8-9a96-e3111d854e7a.png)

.

![opensky-feeder charts -2](https://user-images.githubusercontent.com/28452511/41819636-c9af7a96-7791-11e8-8d07-df205aef1bf3.png)

.

![opensky-feeder charts -3](https://user-images.githubusercontent.com/28452511/41819638-d70f3442-7791-11e8-9ec0-60c9534ab43d.png)

**Comment by gstillman** [comment]
Opensky does this with a fork of your code! Here is the intro to their Readme: This is a fork of Mutability's version of dump1090 that adds a novel method to compute high-precision Time-of-Arrival (ToA) timestamps of the Mode S / ADS-B packets. The actual precision is in the order of a few nanoseconds, depending on the packet strength. 

This might be a helpful change for passing information for MLAT calculations. 

https://github.com/openskynetwork/dump1090-hptoa
http://eprints.networks.imdea.org/1768/

Thank you for all your hard work, Beautiful code and works like a charm. 
Gene

**Comment by abcd567a** [comment]
> Beautiful code and works like a charm.
Gene

https://github.com/openskynetwork/dump1090-hptoa/issues/1

**Comment by jprochazka** [comment]
Looks interesting...
Went ahead and started work on support for dump1090-hptoa. I added commit eb417b6973b7ca9297b5e904794366cd43ed8b5b to the 2.7.0 branch. All that is there currently is a working build process. I am sure I will need to do more to get it to play nice with the protal but that should not be too long to complete.

**Comment by jprochazka** [comment]
An OpenSky feeder installation option has been added to the 2.7.0 branch.
commit 28ef0b23e5298452cf9b59a1e473dac0004d5a68
