### ISSUE TITLE
Add 2 SQL indexes

### ISSUE THREAD

**Issue by target-drone** [jprochazka/adsb-receiver#452]
Recommend adding indexes to adsb_aircraft.icao and  adsb_positions.flight.  That gives my pi3 well over a 90% decrease in time taken to run flights.py.  

Most of the gain is from the optimiser using the index for the `"SELECT message FROM adsb_positions WHERE flight = %s AND message = %s ORDER BY time DESC LIMIT 1" query.`

```
# time python2 /usr/src/adsb-receiver/build/portal/python/flights.oneshot.py

real    1m26.028s
user    1m13.218s
sys     0m11.459s

# sqlite3 /var/www/html/data/portal.sqlite 'CREATE INDEX IF NOT EXISTS idxIcao ON adsb_aircraft(icao);'
# sqlite3 /var/www/html/data/portal.sqlite 'CREATE INDEX IF NOT EXISTS idxFlight ON adsb_positions(flight);'
# time python2 /usr/src/adsb-receiver/build/portal/python/flights.oneshot.py 

real    0m5.600s
user    0m4.697s
sys     0m0.306s
# 

```

**Comment by Romeo-Golf** [comment]
looks like a useful addition :)

**Comment by jprochazka** [comment]
Added indexes in v2.7.2.
