### ISSUE TITLE
Change default google maps another maps provider

### ISSUE THREAD

**Issue by cspaveljb** [jprochazka/adsb-receiver#454]
Hello I'd like to know how can I change google maps to some other maps provider? Thanks!

![image](https://user-images.githubusercontent.com/31196306/42471078-29f60b74-83c5-11e8-8a37-9db6cec07ecb.png)

**Comment by jprochazka** [comment]
Is this an old version of dump1090 you are running? Try running ~/adsb-receiver/install.sh and choose the option to reinstall dump1090. Both dump1090-mutability and dump1090-fa removed Google Maps as an option a while ago.

**Comment by cspaveljb** [comment]
As you can see on the screenshot I'm currently running the latest 1.15dev version of dump1090. Is there any other possible solution to my problem? Thanks!
