### ISSUE TITLE
PiAware client upgrade to version 3.6.2

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#458]
https://discussions.flightaware.com/t/announcing-piaware-3-latest-version-3-6-2/18829

https://github.com/flightaware/piaware/releases/tag/v3.6.2

**Comment by mutability** [comment]
I'd suggest checking out a particular tag, not master, if you depend on a particular version.

**Comment by Romeo-Golf** [comment]
@mutability 

Thanks for the suggestion, there was already some code to do this for the mlat-client which I have replicated in the Piaware client feeder install script..  does https://github.com/Romeo-Golf/adsb-receiver/commit/87f6dd8c8ff79d0ce9130790d74f5c8645d705bc look like a sane way of doing this?
