### ISSUE TITLE
Flightradar24 client upgrade to version 1.0.19-15 (ARM only)

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#460]
https://repo-feed.flightradar24.com/CHANGELOG.md

```
# [1.0.19-15] - 2018-02-06
## Fixed
- fixed crash on locking after a certain interval [Windows]
- connect to piaware raw data port 30005 only if it is open [Linux]

## Added
- monitor DNS and NTP queries count [all platforms]
- monitor number of open file descriptors [Linux]
- display local IPs on the web interface :8754 [Linux]

## Changed
- do not use jQuery on the web interface :8754 [all platforms]

```
https://repo-feed.flightradar24.com/rpi_binaries/fr24feed_1.0.19-15_armhf.deb

The i386 package appears to still be at 1.0.18-5, which is a shame given the "linux" fixes listed in 1.0.19-15 :/

**Comment by Romeo-Golf** [comment]
Please note that the fr24 feeder is installed via apt on Pi's so should keep itself up to date, but ideally should install the latest stable version out of the box.

**Comment by jprochazka** [comment]
The variable `FLIGHTRADAR24_CLIENT_VERSION_ARM` was no longer used by the scripts after Flightradar24 changed to using a setup script of their own making to install the client. It was left in by mistake and has now been removed.

commit 8f3d74f65e9df5edcbb1d2e6a45d50757b64a35f
