### ISSUE TITLE
Some performance graphs not shown in "net-only" mode

### ISSUE THREAD

**Issue by Roofcatbusy** [jprochazka/adsb-receiver#461]
I am using adsb-receiver in "net-only" mode of dump1090 to collect ads-b data from remote station (Station is behind firewall and I cannot see map and statistics from there). Data arrived to host via ssh tunnel and feed to dump1090 via socat. Unfortunately in such setup some performance graphs dissapoeared. I see broken pic icon insead of signal level, message rate and aircraft message rate. Is there a way to correct this behaviour?
regards,
Alexey

**Comment by jprochazka** [comment]
When running in net-only mode dump1090-tools in not able to gather some information from the dongle due to the fact it is not physically plugged into the device dump1090-tools is running on.
