### ISSUE TITLE
Dump1090 (mutability) is installed despite fact that (FlightAware) was chosen

### ISSUE THREAD

**Issue by firesign** [jprochazka/adsb-receiver#464]
I'm installing on a fresh 2018-06-27-raspian-stretch-lite using the steps at https://github.com/jprochazka/adsb-receiver. When executing ./install.sh, the menu Dump1090 FlightAware is chosen, along with the PiAware feeder. However, dump1090-mutability is installed and set to start automatically, even though I did not choose it.

Is flightaware also installed but running in the background?

**Comment by jprochazka** [comment]
Just tested it out and see nothing wrong.
When selecting options make sure to highlight the option then hit space bar.
This is how the whiptail package which is used to render said options works I am afraid to say.
