### ISSUE TITLE
INSTALLATION HALTED! SETUP HAS BEEN TERMINATED!

### ISSUE THREAD

**Issue by ghost** [jprochazka/adsb-receiver#466]
Checking if the package php7.2-sqlite is installed... [NOT INSTALLED]
  Installing the package php7.2-sqlite...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php7.2-sqlite3' for regex 'php7.2-sqlite'
The following NEW packages will be installed:
  php7.2-sqlite3
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/26.9 kB of archives.
After this operation, 104 kB of additional disk space will be used.
Selecting previously unselected package php7.2-sqlite3.
(Reading database ... 189664 files and directories currently installed.)
Preparing to unpack .../php7.2-sqlite3_7.2.7-0ubuntu0.18.04.2_i386.deb ...
Unpacking php7.2-sqlite3 (7.2.7-0ubuntu0.18.04.2) ...
Setting up php7.2-sqlite3 (7.2.7-0ubuntu0.18.04.2) ...

  Checking if the package php7.2-sqlite is installed...  [INSTALLATION ATTEMPT FAILED]
  Attempting to Install the package php7.2-sqlite again in 5 seconds (ATTEMPT 2 OF 5)...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php7.2-sqlite3' for regex 'php7.2-sqlite'
php7.2-sqlite3 is already the newest version (7.2.7-0ubuntu0.18.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

  Checking if the package php7.2-sqlite is installed...  [INSTALLATION ATTEMPT FAILED]
  Attempting to Install the package php7.2-sqlite again in 5 seconds (ATTEMPT 3 OF 5)...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php7.2-sqlite3' for regex 'php7.2-sqlite'
php7.2-sqlite3 is already the newest version (7.2.7-0ubuntu0.18.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

  Checking if the package php7.2-sqlite is installed...  [INSTALLATION ATTEMPT FAILED]
  Attempting to Install the package php7.2-sqlite again in 5 seconds (ATTEMPT 4 OF 5)...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php7.2-sqlite3' for regex 'php7.2-sqlite'
php7.2-sqlite3 is already the newest version (7.2.7-0ubuntu0.18.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

  Checking if the package php7.2-sqlite is installed...  [INSTALLATION ATTEMPT FAILED]
  Attempting to Install the package php7.2-sqlite again in 5 seconds (ATTEMPT 5 OF 5)...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php7.2-sqlite3' for regex 'php7.2-sqlite'
php7.2-sqlite3 is already the newest version (7.2.7-0ubuntu0.18.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

  INSTALLATION HALTED!
  UNABLE TO INSTALL A REQUIRED PACKAGE.
  SETUP HAS BEEN TERMINATED!

The package "php7.2-sqlite" could not be installed in 5 attempts.

    ANY FURTHER SETUP AND/OR INSTALLATION REQUESTS HAVE BEEN TERMINIATED

**Comment by jprochazka** [comment]
I am guessing you are using Ubuntu 18.04+.

In Ubuntu 18.04+ this package is named php7.2-sqlite3 so when the script tries to check if the package php7.2-sqlite is installed it does not locate it and tries to install it again. This happened when PHP 7.0 was initially released as well. The fix is just a matter of checking for php7.2-sqlite3 instead of php7.2-sqlite when the version of PHP is greater than 7.0.

The fix has been added to the master branch in commit 8981f0a047a5cedffa0df8571609ce6c5b28dcc5.
