### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [jprochazka/adsb-receiver#477]
When using Firefox, the following message is shown:

> Your connection is not secure
> 
> The owner of www.adsbreceiver.net has configured their web site improperly. To protect your information from being stolen, Firefox has not connected to this web site.
> 
> This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox only connect to it securely. As a result, it is not possible to add an exception for this certificate.

When using Chrome, this message:

> 
> ubuntu@pitbull$ ./fix_mistake.sh --redesign=true --additional-features=true --wcag-compliant=true --show-status=true
> --------------------------------------------------
>     SwiftByte.com Disaster Recovery
> --------------------------------------------------
>     Recovery plan executed...
> Detected operating system as Ubuntu 18.10 Cosmic Cuttlefish.
> Configuring iptables using UFW (Uncomplicated Firewall)... [OK]
> Installing and configuring Nginx web server... [OK]
> Installing PHP 7.2 FPM (FastCGI Process Manager)... [OK]
> Setting up SSL certificate issued by Let's Encrypt for www.swiftbyte.com... [OK]
> Redirecting all HTTP requests to HTTPS... [OK]
> Obtaining an A+ rating with 100% accross all categories on SSL Lab's SSL Server Test... [OK]
>     WARNING: EXTREMELY OUT OF DATE BROWSERS MAY NOT BE ABLE TO ACCESS THIS SITE!
> Using average CSS and Bootstrap skills to create a responsive login page... [OK]
> Using average CSS and Bootstrap skills to create a responsive administration template... [OK]
> Creating SQLite database which will be used to contain website data... [OK]
> Creating login system using PHP... [OK]
> Adding reCAPTCHA v3 protection... [OK]
> Creating article management pages... [OK]
> Creating user management pages... |

**Comment by Velociraptor85** [comment]
jap got the same

**Comment by HeroCC** [comment]
Same here, anyone know what's up?

**Comment by Velociraptor85** [comment]
sadly no :/

**Comment by wiseman** [comment]
The forum link in the readme (https://www.adsbreceiver.net/forums/) is also 404.

**Comment by jprochazka** [comment]
Yeah I screwed up and terminated the wrong server on AWS...
Anyways I took some time to get the site back up and running as of today.
