### ISSUE TITLE
978 and 1090 testing

### ISSUE THREAD

**Issue by jhaab01** [jprochazka/adsb-receiver#479]
I had installed this over the weekend and so far so good. I am not sure 978 is working properly. If I pull up the 978 map, it has not seen anything. Should any reads from 978 appear in the 978 map or are they pushed over to the 1090 map? What is best way to test so I know 978 is working?
I also am feeding FA and FR24. FA is showing MLAT is not configured. How to I configure that on my receiver?

Thanks!

Jason

**Comment by BudBundi** [comment]
For MLAT on FA, configuration of the receive coordinates on the FA homepage is necessary if I remember correctly.

**Comment by jhaab01** [comment]
Ok, thanks for the help as it looked like I needed to finish the setup with FA for the MLAT and now works. I think the 978 is working as I am seeing some messages coming across but no planes over a few days. I am less that 1/2 mile from GA airport. Is there any logging or history running by default that I could pull to see any history so I can verify the 978 is working properly or not? If not, is there any other suggested ways of testing besides just watching it for something to appear?
