### ISSUE TITLE
Flights Tab - no map is displayed 

### ISSUE THREAD

**Issue by ve3sjk** [jprochazka/adsb-receiver#482]
I have a new installation of the system my database is populating with data, when i click on the flights tab i get a list of the flights in the database. I have entered a google maps api key but when i click on a flight in the list i get a blue box on the left of the screen that opens and closes quickly and no map at all is displayed on the page.

**Comment by ve3sjk** [comment]
I have added the google maps api key and now i do get a map centered on my location but it seems now i have the exact same issue as #412 in which i have a populated database but nothing shows up on the flights page map. I just get a blank map, when i click on a historical flight i do see a blue sidebar pop up and close but then i am back to an empty map

**Comment by jprochazka** [comment]
/var/log/lighttpd/error.log or it did not happen.

**Comment by ve3sjk** [comment]
the log mentioned does not contain errors but i still do not have any tracks on the history map if i go into flights and click any of the tracks logged.

![flight aca119 map](https://user-images.githubusercontent.com/7632604/56462426-d9154100-6390-11e9-837c-9bc8ef045304.png)

![flights](https://user-images.githubusercontent.com/7632604/56462418-cdc21580-6390-11e9-98df-855e3e9dda90.png)

**Comment by MCancellier** [comment]
I brought this up several version ago and still no flights in the database are mapped. Last time we checked the logs, reviewed the database and found no issues. My system displays the same as Steve's. Centered on Cleveland, with no data displayed anywhere  on the map. I'm on a RPi 3B+ running Raspbian Stretch 9.8 with the advanced portal on mySQL.

**Comment by jprochazka** [comment]
If you are running dump1090-fa they changed some of the labels in the JSON file used by the python script to read then save data to the database. A commit fixing this issue is currently in the bugfix branch. This weekend I was too busy to test the changes out before merging them into the master branch. I am hoping to be able to do so tonight.

https://github.com/jprochazka/adsb-receiver/commit/1a74077d177bdb32618839f9d182cdca34178bd1.
