### ISSUE TITLE
navbar and footer hiding interfere with dump1090 zoom controls

### ISSUE THREAD

**Issue by wiseman** [jprochazka/adsb-receiver#486]
Whenever I try to use the dump1090-mutability zoom controls (+/-), it triggers the hidden navbar to show itself, which pushes the dump1090 frame down 50 pixels, which causes the zoom controls to move away from my mouse pointer.  When I move the mouse down to try to click on the new location of the zoom controls, it triggers the navbar to hide itself, causing the zoom controls to dodge up and away from my mouse.

This feels broken.  The easy fix is to disable navbar hiding/showing. An alternative might be to keep a fixed, collapsed navbar at the top of the page, maybe 10 pixels high, and mousing over it causes it to expand.

If you have a preference for a solution I could create a PR for it.

**Comment by jprochazka** [comment]
Work is being done on an entirly revamped portal. I only have a few days of development into it but have enough to show the direction it is heading. It is a large undertaking but hoping to have an alpha quality version of the new portal avaiable within the next few weeks time permitting.

https://www.adsbreceiver.net/2019/02/02/current-project-status/

**Comment by jprochazka** [comment]
Did away with Wordpress and redesigned the site this week. v3.x progress can be foubnd at this URL from now on.

https://www.adsbreceiver.net/v3/

**Comment by jprochazka** [comment]
Navigation and footer bars will not be present in v3.
