### ISSUE TITLE
orangepi zero

### ISSUE THREAD

**Issue by Tom-Neverwinter** [jprochazka/adsb-receiver#489]
"core temperature" graph fails to propagate on graph page. otherwise functions as normal :)

**Comment by jprochazka** [comment]
Add this code block to the configuration.
Please note the value in the line `Disk "mmcblk0"` may or may not need to be changed as well.

```
# Orange Pi specific values.
<Plugin table>
	<Table "/sys/devices/virtual/thermal/thermal_zone0/temp">
		Instance localhost
		Separator " "
		<Result>
			Type gauge
			InstancePrefix "cpu_temp"
			ValuesFrom 0
		</Result>
	</Table>
</Plugin>

<Plugin "disk">
	Disk "mmcblk0"
	IgnoreSelected false
</Plugin>
```

**Comment by ciprianxl** [comment]
Solved! Core temperature is now available after the above modification. The only ones not generating are Disk I/O IOPS & Bandwith, but i assume these are related to an external disk if available, right?
Thak you very much! Will update also my post from last year.

**Comment by jprochazka** [comment]
For disk run the command `lsblk` and look for the name of your "disk".
In the above code block change mmcblk0 `Disk "mmcblk0"` to whatever the name is.

**Comment by ciprianxl** [comment]
Hello Joe,
Here is the `lsblk` result:

```
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
mmcblk0     179:0    0 15.4G  0 disk
└─mmcblk0p1 179:1    0 15.3G  0 part /
zram0       254:0    0   50M  0 disk /var/log
zram1       254:1    0 61.7M  0 disk [SWAP]
zram2       254:2    0 61.7M  0 disk [SWAP]
zram3       254:3    0 61.7M  0 disk [SWAP]
zram4       254:4    0 61.7M  0 disk [SWAP]
```
Tried both `mmcblk0 `and `mmcblk0p1` but still no graph.

**Comment by jprochazka** [comment]
```
<Plugin "disk">
	Disk "mmcblk0"
	IgnoreSelected false
</Plugin>
```
Which are the default lines which appear to match...
`mmcblk0     179:0    0 15.4G  0 disk`
I am at a lose maybe @abcd567a can help if he is able. I know he is in the know when it comes to the OrangePi.

**Comment by abcd567a** [comment]
### OrangePiPC (Armbian Stretch image)
```
pi@orangepipc:~$ grep mmcblk0\  /proc/diskstats

 179       0 mmcblk0 6466 2661 386514 23139 405711 14874 4537280 7452021 0 630528 1204384 0 0 0 0 

```

### Raspberry Pi with SD Card # 1 (Raspbian Stretch image)
```
pi@raspberrypi:~ $ grep mmcblk0\  /proc/diskstats

 179       0 mmcblk0 7037 3287 349312 26230 403410 74841 4255202 55638980 0 701950 55664940   

```
### Raspberry Pi with SD Card # 2 (Piaware SD Card image)

```
pi@piaware:~ $ grep mmcblk0\  /proc/diskstats  

 179       0 mmcblk0 7553 3892 304917 30110 1654 566 41516 759670 0 24560 789870

```

### Raspberry Pi with SD Card # 3 (Pi24 image)

```
pi@raspberrypi:~ $  grep mmcblk0\  /proc/diskstats  

 179       0 mmcblk0 5550 4010 352403 34770 730 57 6844 224230 0 19260 259020

```

**Comment by abcd567a** [comment]
## OrangePiPC - Temperature graph Empty
**(thanks to LudgerBoergerding, ieand, and idh for solution)**

```
sudo nano /home/pi/adsb-receiver/build/portal/graphs/make-collectd-graphs.sh

#Go to function temp_graph_metric() 
#and in its line “CDEF:tfin=traw,1000,/” 
#change 1000 to 1
#Save & close the file, and reboot

sudo reboot
```

**Comment by abcd567a** [comment]
## OrangePI PC - "Temperature Graph is Totally Missing"



```
pi@orangepipc:~$ sudo ~/adsb-receiver/build/portal/graphs/make-collectd-graphs.sh 24h
[sudo] password for pi:
1949 (process ID) old priority 0, new priority 5
577x298
577x298
577x298
577x298
1107x284
577x298
577x298
577x298
577x298
577x298
ERROR: opening '/var/lib/collectd/rrd/localhost/table-localhost/gauge-cpu_temp.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/localhost/table-localhost/gauge-cpu_temp.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/localhost/interface-wlan0/if_octets.rrd': No such file or directory
577x298
1107x284
577x298
577x298
577x298
577x298
pi@orangepipc:~$

```
.

![image](https://user-images.githubusercontent.com/28452511/54372891-aa4dd180-4652-11e9-9c9a-6d7fd581f666.png)

**Comment by abcd567a** [comment]
## OrangePiPC - Temprature Graph is Missing - Applied Workaround proposed by J Prochazka - SUCCESS
**1. Opened file `collectd.conf` for editing**
```
sudo nano /etc/collectd/collectd.conf
```
.

**2. At end of above file, added following code proposed by J Prochazka**
```
# Orange Pi specific values.
<Plugin table>
        <Table "/sys/devices/virtual/thermal/thermal_zone0/temp">
                Instance localhost
                Separator " "
                <Result>
                        Type gauge
                        InstancePrefix "cpu_temp"
                        ValuesFrom 0
                </Result>
        </Table>
</Plugin>

<Plugin "disk">
        Disk "mmcblk0"
        IgnoreSelected false
</Plugin>
```
Saved file (Ctrl+o) and closed it (Ctrl+x)

.

**3. Rebooted** 
```
sudo reboot
```
.

**4. Waited 5 minutes, then updated graphs**
```
sudo ~/adsb-receiver/build/portal/graphs/make-collectd-graphs.sh 24h 

2994 (process ID) old priority 0, new priority 5
577x298
577x298
577x298
577x298
1107x284
577x298
577x298
577x298
577x298
577x298
577x298
577x298
ERROR: opening '/var/lib/collectd/rrd/localhost/interface-wlan0/if_octets.rrd': No such file or directory
577x298
1107x284
577x298
577x298
577x298
577x298
pi@orangepipc:~$
```
.

**5. Cleared browser cache (Ctrl+Shift+Delete) and Reloaded Browser (Ctrl+F5)**

![image](https://user-images.githubusercontent.com/28452511/54376058-94dba600-4658-11e9-9e93-48ef2db09709.png)

**Comment by jprochazka** [comment]
Leave it to @abcd567a to come up with the fix. :)

Just an FYI restarting the collectd service should save having to reboot.
`sudo service collectd restart` or `sudo /etc/init.d/collectd restart`

**Comment by abcd567a** [comment]
I have OrangPiPC and the fix proposed by J Prochazka ([click here](https://github.com/jprochazka/adsb-receiver/issues/489#issuecomment-460439998)) worked on it perfectly well ([click here](https://github.com/jprochazka/adsb-receiver/issues/489#issuecomment-472964085)).

Unfortunately I dont have OrangePi Zero, and cannot test it on it or try to find a fix for it.
