### ISSUE TITLE
F24 installer

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#491]
Hi Joe, Nice to see you back.
Upgraded to master branch around 2 weeks ago, I had issue with flightradar feeder not installing and in the end I had to side load this (r24feed) via wget into adsb-receiver build directory and install it manually from there. Perhaps worth a look for any bugs in the fr24 feeder option.

Pi2 , Jessie lite,

**Comment by jprochazka** [comment]
Just went through the installation no problems on a Raspberry Pi running Raspbian.
Are you running diffrent hardware and/or OS?
If so let me know so I can test it out.

**Comment by jprochazka** [comment]
Cannot recreate the issue.

When adding Flightradar24 support on an RPi Flightradar24's own script is downloaded then executed if the fr24feed is not already installed. On an RPi the following command should have been exectued:

`wget --no-check-certificate https://repo.feed.flightradar24.com/install_fr24_rpi.sh -O ${RECEIVER_BUILD_DIRECTORY}/flightradar24/install_fr24_rpi.sh`

${RECEIVER_BUILD_DIRECTORY} being PWD/build.

Wonder if it was a network hiccup.
To Anyone: Let me know if this is still an issue.

If not I will be closing this issue the next time run across it.
