### ISSUE TITLE
changes to /etc/fstab to reduce SD card writes

### ISSUE THREAD

**Issue by charlie-foxtrot** [jprochazka/adsb-receiver#492]
The following changes can be made to `/etc/fstab` to mount temp filesystems in to reduce SD card writes.  I've been running with these for about a month without issue.

Using tmpfs means the files aren't persisted on reboot.  Some of these changes cause no real data loss across reboot (ie `/var/www/html/graphs` is rebuilt periodically by `adsb-receiver-performance-graphs`) but others wil (ie loosing `/var/lib/collectd/rrd` means graphs will not go back to before restart).

```
tmpfs   /tmp        tmpfs    defaults,noatime,nosuid,size=100m            0 0
tmpfs   /var/tmp    tmpfs    defaults,noatime,nosuid,size=30m             0 0
tmpfs   /var/log    tmpfs    defaults,noatime,nosuid,mode=0755,size=100m  0 0
tmpfs   /run        tmpfs    defaults,noatime,nosuid,mode=0755,size=30m   0 0

tmpfs   /var/lib/collectd/rrd       tmpfs    defaults,noatime,nosuid,mode=0755,size=20m    0 0
tmpfs   /var/www/html/graphs        tmpfs    defaults,noatime,nosuid,mode=0777,size=10m    0 0
tmpfs   /var/www/html/dump978/data  tmpfs    defaults,noatime,nosuid,mode=0755,size=10m    0 0
```

**Comment by ExplodingLemur** [comment]
Some services do not create their /var/log/blah subdirectories on execution, only during installation. There would have to be an additional script to create the appropriate directory structure under /var/log

**Comment by jprochazka** [comment]
Good information for those wishing to implement a solution such as this but I do not plan on adding support for such an operation at this time. The chances of something going wrong and being reported here as an issue with these scripts when data is lost are too great.
