### ISSUE TITLE
NanoPi K2 (S905X) Armbian Strecth Core Temperature, Disk IO - IOPS & Disk IO - Bandwidth

### ISSUE THREAD

**Issue by benben8888** [jprochazka/adsb-receiver#493]
Hello Joe,

Refer to the matter above. I notice that there are 3 graphs which will not show in the performance page.

Core Temperature

Disk IO - IOPS

Disk IO - Bandwidth

Is there a way to make it work? I've refer to your other portal raised by other users, none of them are working for me.

My SBC is FriendlyElec NanoPi K2 (S905X) CPU. I am looking for help on how to fix the graph which currently don't work. Please advise. (ARM64 Armbian Installed)

Best regards & thanks in advance.

SaiHou

**Comment by jprochazka** [comment]
I do not have a nano pi to check but guessing there is no temperature sensor for the OS to poll.
As for disk IO and bandwidth you will need to edit /etc/collectd/collectd.conf

Change "mmcblk0" in the following lines to whatever the name of the disk is which your OS reports.
mmcblk0 is normal for Raspbian installs sda for most others.

```
<Plugin "disk">
	Disk "mmcblk0"
	IgnoreSelected false
</Plugin>
```
