### ISSUE TITLE
PurgeAircraft

### ISSUE THREAD

**Issue by tomwiley** [jprochazka/adsb-receiver#494]
daemon.log is filling up with the following message every 30 seconds:

Feb 18 09:44:40 ravntrack2 rc.local[412]: Traceback (most recent call last):
Feb 18 09:44:40 ravntrack2 rc.local[412]:   File "/home/pi/adsb-receiver/build/portal/python/maintenance.py", line 57, in <module>
Feb 18 09:44:40 ravntrack2 rc.local[412]:     cursor.execute("SELECT value FROM adsb_settings WHERE name = 'purgeAircraft'")
Feb 18 09:44:40 ravntrack2 rc.local[412]: sqlite3.OperationalError: no such table: adsb_settings

Not sure how to fix this, still can't login in as admin

**Comment by jprochazka** [comment]
Thinking the login and this issue are one in the same.
Not sure how but thinking your portal source got left behind.

Do me a favor and look at the following files:

/var/www/html/classes/template.class.php
/var/www/install/index.php

Look for the variable in both named `$thisVersion` is it set to "2.7.0" if not change the version and visit http://<RECEIVER_IP_ADDRESS>/install.php once more.

**Comment by tomwiley** [comment]
Well /var/www/install directory doesn't exist, so that's a problem, $thisVersion is set to "2.7.0"

/var/www/html/classes $ grep Version template.class.php
            $thisVersion = "2.7.0";
            } elseif ($common->getSetting("version") != $thisVersion){

**Comment by tomwiley** [comment]
After the 'git fetch -all' and 'git reset --hard origin/master' I reran the install and I'm still having the same results.  Suspect the 'No core setup required...'

Setting up the web portal...

  Backing up the file /var/www/html/data/administrators.xml...
  Backing up the file /var/www/html/data/blogPosts.xml...
  Backing up the file /var/www/html/data/flightNotifications.xml...
  Backing up the file /var/www/html/data/settings.xml...
  Placing portal files in Lighttpd's root directory...
  Restoring the backup copy of the file /var/www/html/data/administrators.xml...
  Restoring the backup copy of the file /var/www/html/data/blogPosts.xml...
  Restoring the backup copy of the file /var/www/html/data/flightNotifications.xml...
  Restoring the backup copy of the file /var/www/html/data/settings.xml...
  Making the directory /var/www/html/graphs/ writable...
  Making the directory /var/www/html/classes/ writable...
  Making the directory /var/www/html/data/ writable...
  Making the files contained within the directory /var/www/html/data/ writable...
  Checking if dump978 was set up...
  Removing conflicting redirects from the Lighttpd dump1090.conf file...
  Adding the Lighttpd portal configuration file...
  Reloading Lighttpd...

  Setting up collectd performance graphs...

  Checking which dump1090 fork is installed...
  Detecting hardware platform...
  Modifying the dump1090-mutability configuration file to add noise measurements...
  Reloading the systemd manager configuration...
  Reloading dump1090-mutability...
  Backing up the current collectd.conf file...
  Replacing the current collectd.conf file...
  Reloading collectd so the new configuration is used...
  Removing previously installed performance graphs cron file...
  Adding performance graphs cron file...
  Entering the ADS-B Receiver Project root directory...

  Setting up core advanced portal features...

  No core setup required...
  Entering the ADS-B Receiver Project root directory...

  ------------------------------------------------------------------------------
  ADS-B Receiver Project Portal setup is complete.

**Comment by tomwiley** [comment]
Just realized you meant '/var/www/install/index.php' and yes, $thisVersion is set to "2.7.0" there also.

**Comment by jprochazka** [comment]
The core message can be ignored. That is just stating that some of the core components were already installed so they were skipped during the upgrade.

As for the maintenance.py issue there is now a fix for that in the master branch. The fix changes the version from v2.7.0 to v2.7.1 so when accessing the portal you should get a message that it will be upgraded after which you should be running v2.7.1. If the login issue still remains let me know after upgrading let me know.

**Comment by tomwiley** [comment]
Now running v2.7.1 with the same problem.  I should have pasted one more line before, during the install the output reflects v2.6.3, but I verified v2.7.1 is in '/var/www/html/classes/template.class.php' and
'/var/www/install/index.php'

   The ADS-B Receiver Project v2.6.3 Installer

  Setting up the ADS-B Receiver Project Portal...

**Comment by jprochazka** [comment]
OK lets try this.
First lets reset your login and version to v2.7.1 manually using the following PHP file.

Use this file to reset either a users password or version number.
Place this file in the root website directory generally /var/www/html.
Access http://<YOUR_RECEIVERS_ADDRESS/reset.php

If you do not see a login listed in the Change Password drop down skip that and try 

to add an administrator. After that reset the version using the form to set it to 2.7.1.

You may run into errors after resetting the version just tell me the details if there are any.

One last thing the script is not tested if the script errors during any of the above actions let me know.

[reset-script.gz](https://github.com/jprochazka/adsb-receiver/files/2947923/reset-script.gz)

**Comment by tomwiley** [comment]
Downloaded and installed the script in /var/www/html
 (Note:  Changed the name from reset-script to reset.php, otherwise I get a 404 - Not Found error)
No output is generated when accessing http://<YOUR_RECEIVERS_ADDRESS/reset.php
No error, no confirmation, just nothing.

**Comment by jprochazka** [comment]
Did you..
> Extract reset.php (tar -vxf reset-script.gz)

**Comment by tomwiley** [comment]
I used gzip -d reset-script.gz

**Comment by jprochazka** [comment]
Ok lets try this through the CLI.

**SQLITE INSTRUCTIONS**

First connect to the SQLite database through the CLI.

`sudo sqlite3`

Now open the SQLite database for the portal which should be located at /var/www/html/data/portal.SQLite.

`.open /var/www/html/data/portal.sqlite`

Check if an admin user exists.

SELECT * FROM adsb_administrators;

If a user does not exist you will need to add one.

**Add a user to the database.**

First visit https://www.adsb-receiver.net/tools/hash.php and enter a password for a new user and click submit to receive a hashed version of the password you entered. You will use this in the following query when you replace the values to be inserted.

`INSERT INTO adsb_administrators (name, email, login, password) VALUES ('YOUR_NAME', 'YOUR_EMAIL@ADDRESS.COM', 'YOUR_LOGIN', 'PASSWORD_HASH_YOU_GENERATED');`

**Update password if a user exists.**

If a user does exist change the users password to make sure the one you are using is correct. Either do this via the recover password link on the portal website or by generating a hash as described above and setting it manually.

UPDATE adsb_administrators SET password = 'PASSWORD_HASH_YOU_GENERATED' WHERE login = 'USER_LOGIN';

Update the version saved in the database to 2.7.1.
UPDATE adsb_settings SET value = '2.7.1' WHERE name = 'version';

Log into the portal admin page found at http://YOUR_IP_ADDRESS/admin and make sure that all settings are set properly.

**Comment by tomwiley** [comment]
Evidently the adsb_administrators table did not get created:

$ sudo sqlite3
SQLite version 3.16.2 2017-01-06 16:32:41
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open /var/www/html/data/portal.sqlite
sqlite> SELECT * FROM adsb_administrators;
Error: no such table: adsb_administrators

Link to  https://www.adsb-receiver.net/tools/hash.php also didn't work.

-Tom
