### ISSUE TITLE
Incorrect ID/Password on Image Install

### ISSUE THREAD

**Issue by jimdimcc** [jprochazka/adsb-receiver#496]
Sorry to bother you, tried to send you an email at your gmail.com email.  Just installed the adsb-1.28vlan.img and after boot up, I tried ID/Pwd - pi:adsbreceiver per the github documentation to login and it didn’t work.
 
                Any suggestions?
 
Jim

**Comment by adsbxchange** [comment]
That's not https://www.adsbreceiver.net/. That's ADSBx image.

https://adsbexchange.com/ IS NOT https://www.adsbreceiver.net/

NOT EVEN CLOSE TO THE SAME THING.

THIS:
https://www.adsbexchange.com/forum/threads/working-new-adsbexchange-base-image-v1-0.618988/

IS NOT
https://www.adsbreceiver.net/

**Comment by jimdimcc** [comment]
Thanks, sorry for the confusion

**Comment by adsbxchange** [comment]
Well if you need any help.  All the login info for the ADSBx image is where you downloaded it from the forum.
