### ISSUE TITLE
Add logging to text file.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#50]
Add the ability to log installation output to a file. This will help improve any trouble shooting encountered any time errors are encountered while using the scripts.

**Comment by dschaper** [comment]
I think you should be able to just tee the output? Maybe have to redirect stderr to stdout and then tee...

**Comment by jprochazka** [comment]
Thanks for the suggestion was thinking that or do all the work behind dialogs skipping the output all together. Have not decided yet but yes tee would be the way to go if I decide against all dialogs. Adding this to the existing format however would not be all that hard.

    (./piaware.sh 2>&1) | tee piaware.log

Either way would love to be able to document step by step what happened. Most people running into issues do not take the time to write things down, do not remember exactly what error occurred, or flat out miss it totally until it is too late.

**Comment by cy80rg101** [comment]
Suggest a live log viewer page through the web ui. 

Could also have 

"Export to File" and "copy to clipboard" for external use.

**Comment by Romeo-Golf** [comment]
> Suggest a live log viewer page through the web ui.

Hopefully this would be possible through the log viewing code from #228

**Comment by jprochazka** [comment]
Output can now be logged to a file by executing install.sh like so...
`install.sh -l`
or...
`install.sh -log-output`

Currently creates one log file for the entire process labeled by date. I may decide to break the logs up further by package being installed but that may be down the road unless I get the urge to do it before the next release. This will depend on the time I have available and the want/need/demand for things to be split up I guess.

Added in commit 6149b1948056812f3f5b57962139ffb09db91cb8.

A log viewer request should be in a separate issue already if I am not mistaken. If not feel free to open a separate one recommending it if not.
