### ISSUE TITLE
Positions not recorded in MySQL when using dump1090-fa

### ISSUE THREAD

**Issue by gleven** [jprochazka/adsb-receiver#501]
I noticed that when using dump1090-fa, the aircrafts and flights tables are populated but not the positions. 
After doing some research i realized that dump1090-fa aircraft.json, has different names for the columns than dump1090-mutability thus failing on line 158 of flights.py.
In particular the code fails for the following fields 

1. altitude
2. vert_rate
3. speed

After changing the names of those columns to the following, the database started populating also the positions table.

1. **altitude** becomes **nav_altitude**
2. **vert_rate** becomes **geom_rate**      (not sure if i should use geometrical or barometric)
3. **speed** becomes **gs** 

The changes were applied in the build/portal/python/flights.py file on lines 69 , 178 and 183.

**Comment by jprochazka** [comment]
dump1090-mutability was abandoned by @mutability. He is now focusing work on dump1090-fa.

Changes to flights.py need to be made. However there is a chance someone creates a popular fork so should take into consideration backwards compatibility.

**Comment by jprochazka** [comment]
dump1090-mutability was abandoned by @mutability. He is now focusing work on dump1090-fa. FlightAware seems to be on a change everything which was set as a standard in the past kick for some reason like they want to kick anyone who tries utilize their own codes output in the nuts...

Changes to flights.py apparently need to be made. However there is a chance someone creates a popular fork so I should take into consideration backwards compatibility.

**Comment by mutability** [comment]
Who kicked your dog? The json map output was always an internal interface; it's not "changed on a whim", it's "changed to support specific new fields". If you'd like to document a stable schema or interchange format that you want to use, I'm happy to take a PR that implements that as a _separate_ output. The dump1090/map interface is always going to be subject to change.

**Comment by mutability** [comment]
see also: the dump978-fa json output on port 30979; that's currently in flux but I'd be happy to look at stabilizing it if there is interest. (Please _express that interest_; I can't keep track of every possible downstream use of the code I write; if you don't ask for a given interface to be stable, I'm unlikely to know about it)

**Comment by jprochazka** [comment]
Hey I love you got dump978 shitting out JSON. Utilizing this was on my list I just don't understand the sudden undocumented changes in dump1090-fa's JSON output. Let us know when such things change ahead of time.

**Comment by mutability** [comment]
I could stick a version field somewhere in the json if that helps?
The documentation changes do tend to lag behind the code changes unfortunately (there is an open PR to fix the json docs)

**Comment by jprochazka** [comment]
No just give a heads up when things change.
I am a software developer by trade.

If you could let me know what has changed beyond what was reported that would be great!

**Comment by mutability** [comment]
I assume you're comparing to the 3.5.3 output.

I don't have a list of changes immediately on hand as most of these changes are quite old. For now, here's a starting point: https://github.com/flightaware/dump1090/compare/v3.5.3...flightaware:dev#diff-a3e750d7626079bbda25c66e25326c1cL1165

note that many of the fields were renamed because what was previously a single value now has multiple values (e.g. speed -> gs/ias/tas, vert_rate -> baro_rate/geom_rate, altitude -> alt_baro/alt_geom, etc). this is a consequence of dump1090 decoding more things and being more careful about reporting data unambiguously

**Comment by jprochazka** [comment]
Getting the message "There isn’t anything to compare." when following the link.
I will go ahead and setup a test environment and compare the new to the old.

Anyways, thanks for getting back to us. More data is definatly not a bad thing and I understand things change from time to time.

**Comment by jprochazka** [comment]
Fix merged into master branch.

Fix includes creating a separate python script for dump1090-fa.
