### ISSUE TITLE
Update is not restoring links.xml

### ISSUE THREAD

**Issue by hbokh** [jprochazka/adsb-receiver#505]
Just to let you know, I ran the update to 2.7.2 and the custom links (file `links.xml`) are gone.
Which makes sense from the logging:

```txt
  Backing up the file /var/www/html/data/administrators.xml...
  Backing up the file /var/www/html/data/blogPosts.xml...
  Backing up the file /var/www/html/data/flightNotifications.xml...
  Backing up the file /var/www/html/data/settings.xml...
  Placing portal files in Lighttpd's root directory...
  Restoring the backup copy of the file /var/www/html/data/administrators.xml...
  Restoring the backup copy of the file /var/www/html/data/blogPosts.xml...
  Restoring the backup copy of the file /var/www/html/data/flightNotifications.xml...
  Restoring the backup copy of the file /var/www/html/data/settings.xml...
```
The same seems to happen with `notifications.xml`, but I don't use these.

Maybe consider adding these in a next release / update / upgrade? TIA!

**Comment by jprochazka** [comment]
Thanks for pointing this out.
This issue has to have been there for quite some time...

Fixed in commit fd6900e6efe55d82833bfd0caebc4bc6f1bdc427.
