### ISSUE TITLE
forum registration activation fail

### ISSUE THREAD

**Issue by Tom-Neverwinter** [jprochazka/adsb-receiver#506]
I receive the registration email then follow the link. it then fails and outputs:

["BAD CSRF"]

Update:
This issue seems to apply to chrome but works fine on firefox.

**Comment by etamtlosz** [comment]
I was having the same issue. Thanks for pointing me to another browser.
Tried with Chrome on my Android device and it worked.

**Comment by jprochazka** [comment]
I do not host the forum but will bring it to their attention.

**Comment by Tom-Neverwinter** [comment]
https://www.adsbreceiver.net/forums/ fails :P ;)  (in readme/wiki page on github)


https://adsb.discourse.group/ will work after initial login/ registration is complete.

**Comment by jprochazka** [comment]
So much to do so little time... Thanks for pointing out the bad links. The README link has been fixe in commit c7166bb43523490c6729f4ce20dbec839fc0704e. The wiki is in the process of being shut down and moved to https://www.adsbreceiver.net/documentation/.
