### ISSUE TITLE
After install dump978 not running

### ISSUE THREAD

**Issue by cwalker51** [jprochazka/adsb-receiver#508]
I have the adsb-receceiver running with dump1090-fa and piaware. It all seem to run correctly.

I have this in the build directory.
*********************************************
drwxr-xr-x 3 cjw  cjw  4096 May  3 09:53 beast-splitter
drwxr-xr-x 3 cjw  cjw  4096 Apr 12 10:25 bladeRF
drwxr-xr-x 3 cjw  cjw  4096 Apr 12 10:05 display
drwxr-xr-x 3 cjw  cjw  4096 Apr 12 10:25 dump1090-fa
drwxr-xr-x 4 cjw  cjw  4096 Apr 12 10:50 dump1090-mutability
drwxr-xr-x 3 root root 4096 May  3 12:35 dump978
drwxr-xr-x 2 cjw  cjw  4096 May  3 09:53 package-archive
drwxr-xr-x 5 cjw  cjw  4096 Apr 12 10:05 portal
*********************************************************
I have 2 dongles serialized correctly ( I think)
*****************************************
cjw@debian-wind-pc:~/adsb-receiver/build$ rtl_test -t
Found 2 device(s):
  0:  Realtek, RTL2832U, SN: 00001090
  1:  Realtek, RTL2838UHIDIR, SN: 00000978
********************************************************************
I see no errors but dump978 is not running. 

If I run the maint.sh I do get an error.

**************************
cjw@debian-wind-pc:~/adsb-receiver/build/dump978$ ./dump978-maint.sh
(UNKNOWN) [127.0.0.1] 30001 (?) : Connection refused
fopen(/var/www/html/dump978/data/receiver.json.new): Permission denied
Failed to write receiver.json - check permissions?
Found 2 device(s):
  0:  Realtek, RTL2832U, SN: 00001090
  1:  Realtek, RTL2838UHIDIR, SN: 00000978

Using device 0: Generic RTL2832U
usb_claim_interface error -6
Failed to open rtlsdr device #0.
*************************************************************
Keeps looping with this error.

Any ideas?? If not I'll try a clean install in a couple of days.

**Comment by cwalker51** [comment]
One more piece of information. I never get a question about which dongle to use for which frequency

**Comment by jprochazka** [comment]
Looking back I am not sure I ever was able to get around to testing dump978 with dump1090-fa. So many different installation combinations... I have to look into how to set the dongle used by dump1090-fa. Hoping it is as easy as dump1090-mutability was. Can't guarentee a fix today but if not today I will be on it Sunday.

**Comment by cwalker51** [comment]
Hey Joe,
Thanks!!!
Take your time, fan in my Linux box is quitting. I ordered 1 from China and it will be at least 2 weeks to arrive.

Charlie    On Friday, May 3, 2019, 10:59:27 PM PDT, Joe Prochazka <notifications@github.com> wrote:  
 
 
Looking back I am not sure I ever was able to get around to testing dump978 with dump1090-fa. So many different installation combinations... I have to look into how to set the dongle used by dump1090-fa. Hoping it is as easy as dump1090-mutability was. Can't guarentee a fix today but if not today I will be on it Sunday.

**Comment by cwalker51** [comment]
Joe,

My new fan is installed and I am back up and running. But still in the same state. I tried a minimal system. I removed the Portal (found instruction elsewhere in issues.) In Install script I selected just Dump978 and Piaware. So after restart. Dump1090-fa is running and feeding Flight Aware. Flight Aware Sky view does not work. And Portal does not work (as expected)

During the install I defiantly saw Dump978 successful and starting with maintenance script. ( I dont have any log files or I don't know where they are)

Running the maintenance script I get the errors previous reported. These errors did not show up during install script

But serial number has changed.
cjw@debian-wind-pc:~/adsb-receiver$ rtl_test
Found 2 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001
  1:  Realtek, RTL2838UHIDIR, SN: 00000978


Im out of time for now but Ill send new hints if I figure them out.

**Comment by jprochazka** [comment]
I modified the dump978 installation script to detect if dump1090-fa is installed and if so configure dump1090-fa to use the device supplied during setup. GO ahead and pull the master branch again or if you do not want to go through the hassle of going through the setup process again edit the file /etc/default/dump1090-fa and change the --device-index flag to the proper device ID.

commit 65efe86a91b5bf4da17f7b8ee29a37d4809d0b4d

**Comment by cwalker51** [comment]
Joe,
Thanks for all the help. But I got a DUMB     question. How do you select options in the menus in the install.  I did it the first time but I can not get the asterisk to move or insert now. 
Thanks AgainCharlie
    On Tuesday, May 14, 2019, 10:43:34 AM PDT, Joe Prochazka <notifications@github.com> wrote:  
 
 
I modified the dump978 installation script to detect if dump1090-fa is installed and if so configure dump1090-fa to use the device supplied during setup. GO ahead and pull the master branch again or if you do not want to go through the hassle of going through the setup process again edit the file /etc/default/dump1090-fa and change the --device-index flag to the proper device ID.

commit 65efe86

**Comment by cwalker51** [comment]
I got past the selection in the menu. Move curser to desired option and hit space bar. 

But I have a new problem.
I get the following error


************************************************************************************************************

dpkg-deb: building package 'dump1090-mutability-dbgsym' in '../dump1090-mutability-dbgsym_1.15~dev_amd64.deb'.
	dpkg-deb --build debian/dump1090-mutability ..
dpkg-deb: building package 'dump1090-mutability' in '../dump1090-mutability_1.15~dev_amd64.deb'.
 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../dump1090-mutability_1.15~dev_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build dump1090
dpkg-buildpackage: info: binary-only upload (no source included)
dpkg-buildpackage: warning: not signing UNRELEASED build; use --force-sign to override

  Configuring dump1090-mutability to start automatically....
  Installing the dump1090-mutability package...

dpkg: error: dpkg status database is locked by another process

  Checking that the dump1090-mutability package was installed properly...

  INSTALLATION HALTED!
  UNABLE TO INSTALL A REQUIRED PACKAGE.
  SETUP HAS BEEN TERMINATED!

The package "-mutability" could not be installed.

  ------------------------------------------------------------------------------
  Dump1090-mutability setup halted.
******************************************************************************************

I get the same error withe either dump1090-mutability or dump1090-fa
I deleted everything including the /adsb-receiver directory.


Thanks

**Comment by jprochazka** [comment]
> How do you select options in the menus in the install.  I did it the first time but I can not get the asterisk to move or insert now. 

Where at in the install process are you asking about?

> dpkg: error: dpkg status database is locked by another process

Usually this means something is installing/updating/removing a package at the same time you are trying to do one of said operations. If installed unattended-upgrades might have been running an update.

**Comment by cwalker51** [comment]
Joe,

I reinstalled debian to fix anything I jacked up. 

In the install dump1090-fa its building version 3.6.3. then cant find version 3.7.1    Error shown at bottom of below.

******************************************************************************************
dpkg-deb: building package 'dump1090-fa' in '../dump1090-fa_3.6.3_amd64.deb'.
 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../dump1090-fa_3.6.3_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build dump1090
dpkg-buildpackage: info: binary-only upload (no source included)
 signfile dump1090-fa_3.6.3_amd64.buildinfo
gpg: keybox '/home/cjw/.gnupg/pubring.kbx' created
gpg: skipped "Oliver Jowett <oliver@mutability.co.uk>": No secret key
gpg: dpkg-sign.Fvj0Jsgl/dump1090-fa_3.6.3_amd64.buildinfo: clear-sign failed: No secret key

dpkg-buildpackage: error: failed to sign .buildinfo file

  Entering the dump1090-fa build directory...
  Installing the dump1090-fa package...

dpkg: error: cannot access archive 'dump1090-fa_3.7.1_*.deb': No such file or directory

  Checking that the dump1090-fa package was installed properly...

  INSTALLATION HALTED!
  UNABLE TO INSTALL A REQUIRED PACKAGE.
  SETUP HAS BEEN TERMINATED!

The package "dump1090-fa" could not be installed.

  ------------------------------------------------------------------------------
  Dump1090-fa setup halted.

**Comment by cwalker51** [comment]
Its in the variable.sh file. Changed 3.7.1 to 3.6.3 for both dump1090 and piaware.

Works fine. 

On to 978 issues

THANKS !!!!
