### ISSUE TITLE
can't install dump1090-fa package

### ISSUE THREAD

**Issue by herereadthis** [jprochazka/adsb-receiver#509]
I get this error 

```
dpkg: error: cannot access archive 'dump1090-fa_3.9.3_*.deb': No such file or directory

  Checking that the dump1090-fa package was installed properly...

  INSTALLATION HALTED!
  UNABLE TO INSTALL A REQUIRED PACKAGE.
  SETUP HAS BEEN TERMINATED!

The package "dump1090-fa" could not be installed.
```

**Comment by jprochazka** [comment]
Did you get any error messages before said message pertaining to the build? Need a bit more information such as the Linux distribution you are running and said OS's version so I can troubleshoot things.

There honestly might be an issue with older Debian releases such as Jessie being I NEED to add build support for the proper BladeRF library which is not available in the repositories for older Debian, Ubuntu, Raspian official repositorys.

**Comment by gleven** [comment]
I tried to update and i get similar messages.
The installer tries to download and build version 3.6.3 but the dpkg -i commands tries to install version 3.9.3

`dpkg-deb: building package 'dump1090-fa' in '../dump1090-fa_3.6.3_armhf.deb'.
 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../dump1090-fa_3.6.3_armhf.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build dump1090
dpkg-buildpackage: info: binary-only upload (no source included)
 signfile dump1090-fa_3.6.3_armhf.buildinfo
gpg: skipped "Oliver Jowett <oliver@mutability.co.uk>": No secret key
gpg: dpkg-sign.VXh_wApB/dump1090-fa_3.6.3_armhf.buildinfo: clear-sign failed: No secret key

dpkg-buildpackage: error: failed to sign .buildinfo file

  Entering the dump1090-fa build directory...
  Installing the dump1090-fa package...

dpkg: error: cannot access archive 'dump1090-fa_3.9.3_*.deb': No such file or directory`

**Comment by Tom-Neverwinter** [comment]
the Ubuntu variant has issues and will not work or flat out crash. make sure your image is **Debian**

**Comment by gstillman** [comment]
I had the same error recently. With some digging, I found the culprit file.

Edit ~/adsb-receiver/bash/variables.sh

Head down to the flightaware variables where you will find two entries with 3.9.3.  Change to 3.6.3

Rerun the install script. This worked for me.

**Comment by jprochazka** [comment]
Version is now updated in variables.sh. It is now set to 3.7.1 which was just released this week. The problem stems from fixes I made during final testing which I did not commit. This was not the only issue with that oversight and I apologize.

Commit: 227f87b5842b7487944954cecbb01fca43170512

@Tom-Neverwinter
An Ubuntu fix was posted a while back in commit 1a74077d177bdb32618839f9d182cdca34178bd1 which became v2.7.2. Are you still having issues installing the FLightAware software on Ubuntu? If so please open another issue specific to said issue.

**Comment by gleven** [comment]
Problem persists.
It seems that the latest version pulled with git clone https://github.com/flightaware/dump1090 is 3.6.3
Is 3.7.1 released?

**Comment by jkldgoefgkljefogeg** [comment]
master broken again for Ubuntu bionic

```
 dpkg-genchanges --build=binary >../dump1090-fa_3.7.2_amd64.changes                                                                                 [0/875]
dpkg-genchanges: info: binary-only upload (no source code included)                                                                                        
 dpkg-source --after-build dump1090                                                                                                                        
dpkg-buildpackage: info: binary-only upload (no source included)                                                                                           
 signfile dump1090-fa_3.7.2_amd64.buildinfo                                                                                                                
gpg: skipped "Eric Tran <eric.tran@flightaware.com>": No secret key                                                                                        
gpg: dpkg-sign.r44fSnZM/dump1090-fa_3.7.2_amd64.buildinfo: clear-sign failed: No secret key                                                               
                                                   
dpkg-buildpackage: error: failed to sign .buildinfo file                                                   
                                                                                                                                   
  Entering the dump1090-fa build directory...                                                                                                              
  Installing the dump1090-fa package...                                                
                                                                                                                                                           
dpkg: error: cannot access archive 'dump1090-fa_3.7.1_*.deb': No such file or directory
```
