### ISSUE TITLE
recommended geocode finder in installer is down

### ISSUE THREAD

**Issue by herereadthis** [jprochazka/adsb-receiver#510]
https://www.swiftbyte.com/ is down, so their tools are down too.

line is at https://github.com/jprochazka/adsb-receiver/blob/master/bash/decoders/dump1090-mutability.sh#L232

**Comment by jprochazka** [comment]
Forgot to update the URL after moving it to adsbreceiver.net.
The new URL is https://www.adsbreceiver.net/tools/geocode.php.

Fix has been committed to the master branch.
Commit: cb310463c7f4caac9536aea6f539784ac1e1993e
