### ISSUE TITLE
dump1090-mutability has "moved"

### ISSUE THREAD

**Issue by mutability** [jprochazka/adsb-receiver#531]
A brief note to say that I've archived (made read-only) my mutability/dump1090 fork, and the master branch now just has a note pointing out that it's unmaintained and obsolete.

I know that these scripts check out and build from github, so they are presumably broken now.
If you want to continue building the old code (I'd really prefer if you moved to something maintained instead) then you can clone the `unmaintained` branch of mutabiltiy/dump1090 (which has the old master branch) rather than `master`

**Comment by jprochazka** [comment]
The option to install dump1090-mutability will be removed in the upcoming v2.8.0 release which is taking shape in the phoenix branch.
