### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by chjohn22** [jprochazka/adsb-receiver#533]
Hello everybody

I follow this project for many years and was really hopeful in early 2019, when @jprochazka set up the new adsbreceiver.net website and discourse group. I am really thankful for this piece of software but I think development has ceased and we have not heard anything from him for a long time. So I had to move on to the custom image from ADS-B Exchange but I still think adsbreceiver has potential, it just would be good to know if Joe really abandoned this project or if he will eventually come back.

**Comment by hbokh** [comment]
The project look to be belly-up.
@jprochazka has not logged any activity on GitHub since May 14 2019.
To make things worse, https://www.adsbreceiver.net/ shows an expired certificate (valid until Dec. 31st 2019).

**Comment by etamtlosz** [comment]
did you guys find any alternatrive?

**Comment by chjohn22** [comment]
@etamtlosz  Yes, the ADSBx Custom Pi Image from adsbexchange.com can be flashed on a SD card. You just need to enter your coordinates and meters above sea level and are good to go.
https://www.adsbexchange.com/how-to-feed/adsbx-custom-pi-image/
It does use tar1090 and has some nice features such as toggles to show military aircraft only.
Additionally, it is based on Raspbian Buster and does even support the RPi 4B.

**Comment by etamtlosz** [comment]
My problem is that I'm using the manual install, not the SD card version. I'm running my servers on an IBM server. Until now, I didn't find any good solution to emulate raspberry HW on proxmox.

**Comment by kylegordon** [comment]
I do hope this project doesn't get abandoned in favour of a Raspberry Pi image.

My ADSB-Receiver setup runs on Armbian on a Banana Pi M2 Zero. It'll never work with a Raspberry Pi image. 

In many ways the Pi clone ecosystem and Armbian innovate faster than the Raspberry Pi foundation. In the foundations defence though they put more effort into standardisation and support.

I have similar hopes to what @etamtlosz is doing. I'd like to move my setup to the big rackmount server in the house, but in the meantime it'll continue running on non-RaspberryPi hardware. It might stay that way forever though, given that I also want to put the antenna up high and the Pi may join it in an IP67 box on the mast.

**Comment by rucknapucknavitz** [comment]
If anyone figures out how to get a reliable USB connection on Proxmox that supports MLAT, please holler. 

In the meantime, https://github.com/mikenye/docker-readsb/wiki/Guide-to-ADS-B-Data-Receiving,-Decoding-and-Sharing,-Leveraging-RTLSDR-and-Docker

**Comment by etamtlosz** [comment]
What's wrong with MLAT on proxmox?

**Comment by rucknapucknavitz** [comment]
Clock issue. Totally unreliable. There’s a fix for virtualbox, but haven’t found anything yet for Proxmox. 

https://discussions.flightaware.com/t/server-status-clock-unstable/19482/24

**Comment by wunderbaum** [comment]
Seems to be abandoned, what a pity!

**Comment by rucknapucknavitz** [comment]
> Seems to be abandoned, what a pity!

Yes, it does seem to be. But check out the mikenye github that I linked to above - it’s all picked up there and via docker. Super easy!

**Comment by etamtlosz** [comment]
+ the Mike is very active on discord as well. He's answering pretty fast to any question, problem.

**Comment by kylegordon** [comment]
Can confirm, Mike is great.

I have my own little docker-compose adsb-stack comprised of all of his docker work over at https://github.com/kylegordon/adsb-stack - my work isn't 100% yet, but it's getting there

**Comment by jprochazka** [comment]
I have actually started back to work on the project after a long down time. I am currently working on getting existing items up to date and working once more. The work is being done in the phoenix branch at this time.
