### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by JonMurphy** [jprochazka/adsb-receiver#534]
The certificate for your https://www.adsbreceiver.net website expired a few days ago.

<img width="693" alt="Screen Shot 2020-01-04 at 12 20 55 PM" src="https://user-images.githubusercontent.com/15616372/71769962-d9d50f80-2eec-11ea-8804-d6277877879e.png">

**Comment by chjohn22** [comment]
It seems to be fixed
