### ISSUE TITLE
Is it possible to run this software on x86 devices?

### ISSUE THREAD

**Issue by frMaciek** [jprochazka/adsb-receiver#537]
I have an old thin client (Fujitsu Futro S900) with an x86 CPU on board - is it possible to run this software on this type of CPU, or is it created exclusively for ARM processors (Raspberry Pis and other ARM-based SBCs)...

**Comment by HRmeteohub** [comment]
In theory, yes, since portal is more or less done in php, python and unix script.
However, ADS-B software should be also compiled for x86.

**Comment by jprochazka** [comment]
One of the goals of the project is to allow the installation of software across all architectures. This is done by building everything from source. I cannot say I have tested this on x86 hardware, but it does work on both x64 and ARM with nothing specific to either except maybe AboveTustin. So as @HRmeteohub stated in theory it should work.
