### ISSUE TITLE
Add the ability to install wiedehopf's fork of Readsb.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#578]
Add an option to build and install the Readsb fork @wiedehopf is currently maintaining as an additonal Mode-S/ADSB/TIS decoder option.

https://github.com/wiedehopf/readsb

**Comment by jprochazka** [comment]
Building Readsb is broken at this time due to package naming differences in Debian and Ubuntu. Until Readsb is buildable on both Debian and Ubuntu based distributions support will not be added.

https://github.com/wiedehopf/readsb/issues/74

**Comment by wiedehopf** [comment]
```
sed -i -e 's/librtlsdr0/librtlsdr2/g' debian/control
```

So this will solve the building problem, you'll still need to install tar1090 using the install script and really it has no debian package.
Otherwise there will be no webinterface.

**Comment by jprochazka** [comment]
The option to install Readsb has been added in v2.8.7.
