### ISSUE TITLE
Piaware would not install on Armbian Bullseye 23. 02. 2 due to dependecy problem

### ISSUE THREAD

**Issue by YogySK** [jprochazka/adsb-receiver#611]
Hello, the piaware package will build, but when it is to be installed, the installation fails due to dependecy problem:

dpkg: dependency problems prevent configuration of piaware:
 piaware depends on tcl-tls (>= 1.7.22-2+fa1); however:
  Version of tcl-tls:armhf on system is 1.7.22-2.

I am running Armbian Bullseye 23. 02. 2 on orangepizero.

**Comment by jprochazka** [comment]
I have merged a fix into master as part of v2.8.8. If the issue persists, feel free to reopen this issue.
