### ISSUE TITLE
Graphs for dump978

### ISSUE THREAD

**Issue by jthawkes** [jprochazka/adsb-receiver#89]
Not sure if I should put It here or in the collectd section.

**Comment by jprochazka** [comment]
I would have to take a look at the JSON data provided by dump978 in order to see what would be involved with modifying dump1090-tools to handle dump978 data. If anyone receiving a steady flow of UAT data could attach examples of all the files stored in /var/www/html/dump978/data/ in this issue I can take a look into this.

**Comment by laferrierem** [comment]
I have Dump1090 and Dump978 running on a Pi that I set up with your script. I know while this was running I have seen planes on Dump978 running on a separate pi but these two files look empty..?

**Comment by laferrierem** [comment]
GNU nano 2.2.6             File: receiver.json

{
  "version" : "dump978-uat2json",
  "refresh" : 1000,
  "history" : 0
}



 GNU nano 2.2.6             File: aircraft.json

{
  "now" : 1478355084,
  "messages" : 14594,
  "aircraft" : [

  ]
}

**Comment by jthawkes** [comment]
@laferrierem,
You need to look at the files when you see traffic.
I have found that it is a pain to get logging and port 30001/json updates to work at the same time.
Maybe we can look at the dump1090 instance used by dump978 for the stats.

When I enabled logging, I could get 20,000-40,000 messages per day. I still have to move the antenna outside to get better range. Hopefully, then I will be able to provide more information,

Note, I tried the stratux version of dump978, in the hope of getting signal levels on the webpage(and being able to do some sort of gain optimisation). It works, but I don't get a signal level.

**Comment by jprochazka** [comment]
In the near future the portal will be stored in it's own repository so there is no need to track future enhancments here. However, it is on my yet to be published portal TODO list.
