### ISSUE TITLE
Highcharts graphs instead of collectd

### ISSUE THREAD

**Issue by paranoidjack** [jprochazka/adsb-receiver#94]
It seems that it's possible to export collectd data to xml and then use that to create interactive Highcharts graphs: http://warlord.no-ip.com/howto.html

Could such graphs be considered in future revisions of adsb-feeder?

**Comment by jprochazka** [comment]
This may be a possibility in the future. I like the way it looks, a bit more fluid and clean looking than the rrdtool graphs. However at the moment most of my free time has been focused on the template system. I also have issues #69, #84, #87, and #89 to address before moving on to adding new features such as this. Being that @mgunther68 has been doing most all the work on the graphs recently I will leave it up to him if he wants to tackle the task now or in the near future before I am able to get to it. If not once I am caught up with my tasks I can see about giving it a go if this is something the community would like to see.

I was able to locate a library to allow JavaScript to read RRD databases. One example after doing a quick search was located at http://javascriptrrd.sourceforge.net/. I would rather see the data pulled directly from the RRD database as opposed to exporting to XML to cut back on disk IO.

If anyone else would be interested in the change to this style of graph let me know. Higher demand generally means higher priority when it comes to changes such as these.

**Comment by mgunther68** [comment]
Oh man, I'm just about getting to grips with rrdtool and learning about the data models, graphs, etc. I have no experience with Highcharts but I agree they look nice.
So, I would not be able to do anything in the short term but Joe if you decide to go that direction in future I should be able to help in defining and refining graphs.

**Comment by jprochazka** [comment]
Just found their site at http://www.highcharts.com. Honestly not to keen on their licensing...
It says its free for non-commercial use but not sure if I would wish to entertain the possibility of using any sort of "open but closed if..." licensing. Dual licensed GPL/MIT type libraries compatible with the MIT license this project uses is fine. I can't even find their license anywhere to take a look at it. If someone finds it let me know.

An incompatable license is a deal breaker on this one.

**Comment by jprochazka** [comment]
Not sure that licensing is compatible. Maybe later down the road we will look into a compatible option.

**Comment by cy80rg101** [comment]
Low priority ticket I agree - but when you look at this you might like to consider Google Charts API...

https://developers.google.com/chart/interactive/docs/gallery

Backed by a "pretty good" development team, ;) , with wide spread adoption...

**Comment by jprochazka** [comment]
I am actually using Google Charts on the system information page I am creating.
