### ISSUE TITLE
A way to upgrade the portal without overwriting data.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#98]
There needs to be put into place a way to upgrade the portal without resetting all XML data.

**Comment by mgunther68** [comment]
Yeah that would be good. I'm tired of resetting the password every time I run an upgrade ;)

**Comment by jprochazka** [comment]
After the next release upgrades will no longer reset current settings.

**Comment by jprochazka** [comment]
Must have closed this issue by mistake...
